linuxmint/cinnamon

data/org.cinnamon.gschema.xml.in, data/theme/cinnamon.css, files/usr/lib/cinnamon-settings/modules/cs_notifications.py, js/Makefile.am, js/ui/cinnamonDBus.js, js/ui/main.js, js/ui/osdWindow.js
Visibility and size can be controlled from Cinnamon Settings notifications.
=> Add a media keys OSD window

files/usr/lib/cinnamon-settings/modules/cs_backgrounds.py, files/usr/lib/cinnamon-settings/modules/cs_calendar.py, files/usr/lib/cinnamon-settings/modules/cs_default.py, files/usr/lib/cinnamon-settings/modules/cs_desktop.py, files/usr/lib/cinnamon-settings/modules/cs_effects.py, files/usr/lib/cinnamon-settings/modules/cs_fonts.py, files/usr/lib/cinnamon-settings/modules/cs_general.py, files/usr/lib/cinnamon-settings/modules/cs_hotcorner.py, files/usr/lib/cinnamon-settings/modules/cs_info.py, files/usr/lib/cinnamon-settings/modules/cs_keyboard.py, files/usr/lib/cinnamon-settings/modules/cs_mouse.py, files/usr/lib/cinnamon-settings/modules/cs_notifications.py, files/usr/lib/cinnamon-settings/modules/cs_privacy.py, files/usr/lib/cinnamon-settings/modules/cs_screensaver.py, files/usr/lib/cinnamon-settings/modules/cs_themes.py, files/usr/lib/cinnamon-settings/modules/cs_tiling.py, files/usr/lib/cinnamon-settings/modules/cs_windows.py, files/usr/lib/cinnamon-settings/modules/cs_workspaces.py
SectionBg wasn't removed in cs_panel since it actually served sectioning purposes.
=> Ditch (most) uses of Cinnamon Settings SectionBg

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Should fix some issues @JosephMcc mentioned on #3858
=> sound applet: check if the DBus Rate property is a valid one

js/ui/layout.js
The comment is plain wrong and inaccurate. Better remove it than confuse people.
=> Removed inaccurate comment and refactored some code

js/ui/popupMenu.js
Should we do the same for IconApplet as well?
=> Change icon properly with PopupIconMenuitem

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
=> window-list applet: add option to disable middle-click to close

js/ui/panel.js
=> Hide Panel._left/center/rightBox when hiding panel to prevent clicking of applets when panel hidden

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
=> Add "Move to another workspace" to window list menu

js/ui/runDialog.js
=> Fix Alt-F2 completion bug when string ends with whitespace

Makefile.am, configure.ac, debian/cinnamon-doc.install, debian/control, debian/rules, docs/Makefile.am, docs/reference/Makefile.am, docs/reference/cinnamon/Makefile.am, docs/reference/cinnamon/cinnamon-docs.sgml.in, docs/reference/cinnamon/js/applet.xml, docs/reference/st/Makefile.am, docs/reference/st/st-docs.sgml.in
I probably did something wrong. I have no knowledge of Makefiles and debian packaging whatsoever.
=> Add back doc building

files/usr/lib/cinnamon-settings/modules/cs_panel.py, js/ui/panel.js, js/ui/popupMenu.js, js/ui/windowManager.js
Requires https://github.com/linuxmint/muffin/pull/180
Second commit fixes a bug involving show/hide delays when one of them is 0. See the long comment put in the source for more details. This is included in this PR since both edit the same section of code
=> Add intelligent panel hide #1381 #3143

js/ui/extension.js
In the past, if we wanted to load the applet applet@cinnamon.org, we go
to /usr/share/cinnamon/applets/ (and other similar directories), list
everything in the directories, and for each item we check if it is a
directory, and see if the name is the same as the applet uuid. This is
stupid.
A much saner way of doing so would be to load
/usr/share/cinnamon/applets/applet@cinnamon.org/ directly.
=> Use a sane way to find extension directories.

files/usr/lib/cinnamon-settings/modules/cs_keyboard.py
See https://github.com/linuxmint/muffin/issues/42, https://github.com/linuxmint/Cinnamon/issues/2190.
Requires https://github.com/linuxmint/muffin/pull/181, https://github.com/linuxmint/cinnamon-desktop/pull/37.
=> Move window to monitor #2190

js/ui/cinnamonDBus.js
With https://github.com/linuxmint/cinnamon-screensaver/pull/79
=> Close expo when screensaver called

js/ui/appSwitcher/appSwitcher.js, js/ui/main.js, src/cinnamon-global.c, src/cinnamon-global.h
Picked from https://git.gnome.org/browse/gnome-shell/commit/?id=f4d8a35
Closes #2493
=> Allow using alt-tab while dragging

js/ui/applet.js, js/ui/popupMenu.js
=> Set applet popup menu max width as well as max height

js/ui/panel.js
- Panel Edit Mode style not set at Cinnamon startup
- Disconnecting invalid signal in handleDragOver
=> panel.js: fix minor bugs:

files/usr/lib/cinnamon-settings/modules/cs_screensaver.py
TODO:
- scrollbox for selection window
- make things look better
- preview occasionally randomly unpredictably doesn't work for unknown reasons
=> [WIP] cs_screensaver.py: added screensaver selection page

js/misc/signalManager.js, js/ui/panel.js, src/cinnamon-wm.c
- When the focus is the desktop (nemo window), show the whole panel
- Update panel visibility after workspace switch
=> panel.js: improve intellihide behaviour

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
Panel Launcher DND used to rely on the application name to identify
panel launchers. This causes unpredictable behaviour during dnd when two
applications of the same name are in the panel launcher (easily
reproduced by placing the same application twice). This fixes the issue
by directly identifying the launchers by the actual launcher object.
This fixes #3474 (the issue mentioned by the thread-hijacker. The
original issue was already fixed).
=> Fix panel launcher dnd

files/usr/lib/cinnamon-settings/bin/SettingsWidgets.py, files/usr/lib/cinnamon-settings/modules/cs_power.py, files/usr/lib/cinnamon-settings/modules/cs_screensaver.py, files/usr/lib/cinnamon-settings/modules/cs_startup.py, files/usr/lib/cinnamon-settings/modules/cs_themes.py
=> cinnamon-settings: be compatible with old gi

files/usr/lib/cinnamon-settings/modules/cs_themes.py
=> remove empty tooltip

js/ui/applet.js
=> applet.js: don't use deprecated MenuItem

js/misc/signalManager.js
Requires https://github.com/linuxmint/cjs/pull/24
=> signalManager.js: fix errors when disconnecting JS objects

js/ui/windowEffects.js, js/ui/windowManager.js
=> effects: bring back our window unminimize effect

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json, js/ui/tooltips.js
The theme for preview is hardcoded. Probably want to improve it later. \*hint\* \*hint\*
=> Window list window preview

files/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js
=> trash applet: do not add items to context menu on orientation changed

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
If the device status is `UNAVAILABLE` or `UNMANAGED`, hide the switch.
It just looks weird to me that my laptop shows the switch for cable next to the text "cable unplugged".
This is only a "looks nicer" change, not more.
=> Network applet: hide the switch if the switch has got no function

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, js/Makefile.am, js/ui/checkBox.js, js/ui/dbusMenu.js, js/ui/indicatorManager.js, js/ui/main.js, js/ui/popupMenu.js, js/ui/radioButton.js
This will add support for indicators. There are some things that need to be done yet, but as @dalcde recommended i will share what i have. Try to find the FIXME in the code, to find the critical areas. The Api is not binding with Main yet, and this will remove the watchdog class.
=> [2.8] Add support for indicators.

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
=> Fix menu applet's graphical oddity during search

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
Addresses the discussion in https://github.com/linuxmint/Cinnamon/pull/4813
=> menu: Add a setting to hide category icons

files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
Idea from https://github.com/linuxmint/mdm/issues/169
=> cs_startup: expand entries in edit/add custom dialog on resize

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
I've implemented feature request: (Allow multiple actions for Panel Launcher Applet icons) #3666
You may want to see how it works on screenshots available here: https://github.com/trolleyyy/MintPanelLauncher
=> [Applet][Feature request] Allow multiple actions for Panel Launchers Applet icons

data/icons/Makefile.am, data/icons/hicolor_devices_scalable_audio-speaker-center-back.svg, data/icons/hicolor_devices_scalable_audio-speaker-center.svg, data/icons/hicolor_devices_scalable_audio-speaker-left-back.svg, data/icons/hicolor_devices_scalable_audio-speaker-left-side.svg, data/icons/hicolor_devices_scalable_audio-speaker-left.svg, data/icons/hicolor_devices_scalable_audio-speaker-right-back.svg, data/icons/hicolor_devices_scalable_audio-speaker-right-side.svg, data/icons/hicolor_devices_scalable_audio-speaker-right.svg, data/icons/hicolor_devices_scalable_audio-subwoofer.svg, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Requires https://github.com/linuxmint/cinnamon-control-center/pull/134 and https://github.com/linuxmint/cinnamon-settings-daemon/pull/112
=> Move sound settings to python as a native module

js/ui/windowAttentionHandler.js
=> Viber stealing focus fix

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
Added buttons to change your default source code editor and change your default rich document editor, add application picker if desired application is not on the list
=> [3.0] Add new default application buttons

files/usr/share/cinnamon/cinnamon-slideshow/cinnamon-slideshow.py
https://github.com/linuxmint/Cinnamon/issues/4280
=> Fixed cinnamon slideshow error (Issue #4280)

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
fixes https://github.com/linuxmint/Cinnamon/issues/5155
=> Extensions: Fix the "Disable all extensions" not working

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
This pull request is for issue #4758. It uses hashlib.sha1 to uniquely and deterministically identify images with their name and last modified time as below then caches the thumbnail in `$XDG_CACHE_HOME/cs_backgrounds/`
h = hashlib.sha1(('%f%s' % (os.path.getmtime(filename), filename)).encode()).hexdigest()
Suggestions welcome if there is a better way I could be approaching this.
=> Persistently Cache Background Thumbnails

files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
=> 5287 settings startup module fix markup escaping

cinnamon.pot, data/theme/cinnamon.css, docs/reference/cinnamon-tutorials/using-documentation.xml, docs/reference/cinnamon-tutorials/write-applet.xml, files/usr/bin/cinnamon-settings, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/xrandr@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py, js/ui/applet.js, js/ui/extension.js, js/ui/modalDialog.js, js/ui/notificationDaemon.js, js/ui/placesManager.js, js/ui/popupMenu.js, js/ui/search.js, js/ui/tweener.js, src/cinnamon-app.c, src/cinnamon-global.c, src/cinnamon-jhbuild.in, src/cinnamon-recorder.c, src/st/st-im-text.c, src/st/st-scrollable.c, src/st/st-texture-cache.c, src/st/st-theme-context.c, src/st/st-theme.c, src/st/st-widget.c
Fixes code mistake in  files/usr/share/cinnamon/applets/xrandr@cinnamon.org/applet.js
=> Fix spelling mistakes

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, js/ui/messageTray.js, js/ui/soundManager.js
Closes https://github.com/linuxmint/Cinnamon/issues/5467
=> Add the ability to play a sound effect when showing notifications

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
Added Remove button for Xlets (applets, desklets, etc.). Button is disabled if there are no instances.
=> Add button to remove Xlets

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
NB: mouse buttons 4 and 5 (aka back/forward buttons) are numbered 8 and 9 by X
=> sound applet: bind mouse buttons 4/5 to previous/next track

js/ui/panel.js
This was not done before, now it is.
=> Remove panel barriers on panel removal

js/ui/boxpointer.js
as all the ifs are mutually exclusive
=> minor change into a more natural case statement

js/ui/panelMenu.js
We were checking the same thing twice.
=> panelMenu.js: fix incorrect logic

js/ui/panel.js
and also clean up an if sequence, a few related comments, and a misalignment
=> centre align the centre box in a vertical panel

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, js/ui/panel.js
also corrected an erroneous variable reference in a log message
=> Indentation corrections to remove inadvertent tabs

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
Properly format conditionals, fix indentation, and remove some trailing
whitespace
=> systray: Clean up code formatting

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
1) an issue that looks to have been there before the vertical panels change where
drag and drop within the panel launcher would drop icons in unscaled rather
than at the same scale as the other icons
2) a vertical panels issue where the drag and drop code was assuming horizontal orientation
and so was calculating both the position in the list of icons and the new position in the
actor incorrectly
3) took the opportunity to correct a number of minor indentation issues - getting rid of inadvertent tabs and standardising brackets
=> Correct drag and drop bugs in panel launcher

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
1) The override on the allowable drag direction was not set to allow vertical dragging
also previous override needed clearing when orientation changed
2) Removed a few stray tabs etc.
3) Calculated the drop position correctly for vertical panels
=> correct window list internal drag and drop for vertical panels

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
We are missing most of the standard menu items available in the applet context
menu. Reorganize a bit and add these. Also allows easy removal of a single
instance of the window list.
=> window-list: Add the standard applet context menu items

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
Now that we have support for launcher specific actions in the menu, put some of
the less used options in a submenu. Also add an additional submenu to hold the
menu items common to the right click context menu for most applets. This also
gives an easy way to remove a single instance of the panel launchers. Something
that is currently missing.
=> panel-launchers: Redesign the launcher context menu

files/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js
The issue is that sticky keys make use of the applet label to display
and this is not compatible with a vertical panel.
Resolve this by re-purposing the applet tooltip to show the sticky keys in a vertical panel
The functionality in a horizontal panel is unchanged.  The tooltip also shows
normally in all cases excepting when the relevant keys are actually pressed
=> make accessibility applet suitable for vertical panels

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
fixes https://github.com/linuxmint/Cinnamon/issues/5820
=> [menu-applet] Sometimes places and recent documents were shown in AllApplications.

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
My own mistake from https://github.com/linuxmint/Cinnamon/pull/5834
=> window-list: Fix an undeclared variable warning

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
https://github.com/linuxmint/Cinnamon/pull/5833#issuecomment-258122050 put some
of the additional panel-launcher options in a submenu. Make sure to pass the
proper arguments to the function callbacks for activating the submenu items.
=> panel-launchers: Fix 'Add' and 'Edit' not working

js/ui/popupMenu.js
Do this by first testing if the menu is originating from the panel or a source
actor that is located on the panel. If it is, grab all the panels located on the
monitor and insert the menu just below the lowest panel. This prevents weird
visual artifacts where the menu can slightly overlap the panel in many themes.
=> popupMenu: Insert menus that open from the panel below the panels

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
Closes #5809
Thanks to @itzexor and @mtwebster, who helped me preventing the popupMenu to change width.
rebased version of https://github.com/linuxmint/Cinnamon/pull/5849
=> [sound-applet] add option: show percentage next to volume slider

js/ui/applet.js
Since the removal of box pointers (menu arrows) from Cinnamon's UI, there isn't a visual guide that inform us to which applet the currently opened menu belongs to.
This commit adds a mechanism that will set or unset the "checked" pseudo class to applets with menus. When the main menu of an applet (or its context menu) is open, the "checked" pseudo class will be applied to the applet. When either of the previously mentioned menus are closed, the "checked" pseudo class will be removed.
Only *"standard"* applets are affected. *"Special"* applets like **Window list**, **Panel launchers** and **Workspace switcher** aren't affected and might need to be *"dealt with"* individually. (Read **Technicalities** for more details)
Cinnamon themes will need to be modified to style the …
=> [applet.js] Added a mechanism to highlight applets with open menus.

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/misc/fileUtils.js
This will provide a way to use Gio in replace of the spawnCommandLine for change the file mode. Also was applied to the menu applet.
=> Use the Gio library for establish the file permissions 

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, js/ui/panel.js
- All settings -> System Settings
- Networking -> Network
fixes https://github.com/linuxmint/Cinnamon/issues/5931
fixes https://github.com/linuxmint/Cinnamon/issues/5889
=> uniform names: All settings, Networking

data/theme/cinnamon.css
Commit https://github.com/linuxmint/Cinnamon/commit/69a01ca058372952653393d62e18904d5fc9fc8c
broke the styling of the workspace switcher buttons so fix them
=> theme: Fix theming of the workspace switcher

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
Xlets settings system currently doesn't have a translation mechanism to translate installed xlets. So, when an xlet with .po files is installed, its settings window wouldn't use the translated strings.
This commit adds the ability to use the corresponding translations for the installed xlet.
- Since the **xlet-settings.py** file switched from using Python2 on Cinnamon 3.0.7 to use Python3 on Cinnamon 3.2.x and the **gettext** module doesn't have a **ugettext** method on Python3, ~~I used the **lgettext** method for getting the translations. As I understand it, they are equivalent(?)~~. **Edit:** I switched to the **gettext** method.
- I don't know if I used the **decode()** method the right way inside the **translate** function. Someone more skilled should take a closer look at that. …
=> [Xlet settings] Added translation mechanism to xlets settings windows

data/icons/Makefile.am, data/icons/hicolor_devices_scalable_cpu-symbolic.svg
Add a simple cpu-symbolic.svg for the new icons used the menu applets context
menu.
=> icons: Add an icon for the "Run with NVIDIA" option in the menu

data/theme/cinnamon.css
Change introduced by linuxmint/Cinnamon/pull/5951
=> Default theme: Added support for applets with :checked pseudo class.

js/ui/panel.js
will require testing by 3rd party
=> remove rtl code in vertical panel

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
Consecutives switches occuring on touchpad devices due to
uncontrollable scroll units. This avoids that by giving you a small
time to react and stop scrolling.
This does not apply when you go and come back from a workspace.
Relating #5603
=> workspace-switcher: avoid fast consecutive moves

debian/control
https://github.com/linuxmint/Cinnamon/commit/09acd40194fddc1394dc8e47552051320e53fe51
=> add depends wget

files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py
Fixes https://github.com/linuxmint/Cinnamon/issues/6059
=> Add setting to disable automatic screen rotation on tablet's

js/ui/panel.js
this was causing the context menu animation to fail to complete
causing the user not to be able to exit edit mode
fixes #6140
=> panel: rework allocation logic to avoid looping in edit mode

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This fixes a segmentation fault that happened when menu animations were disabled.
Fixes #5977
=> [Sound applet] Fix a segmentation fault

src/st/st-theme-node.c
From upstream https://github.com/GNOME/gnome-shell/commit/72bfa9125945919e9d69505d3e739480855f331e
=> theme-node: Fix leak on stylesheet change.

files/usr/share/cinnamon/applets/recent@cinnamon.org/applet.js
Thanks to gh9000 for tracking down the reason
Closes: https://github.com/linuxmint/Cinnamon/issues/6295
=> recent-applet: Fix wrong menu placement

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
Currently, the keyboard applet is impossible to move when there are no extra layouts available. This pr causes the keyboard applet to show a generic keyboard icon in panel edit mode if there is nothing else showing already.
=> Keyboard applet: always show something in panel edit mode

js/ui/settings.js
=>  	settings.js: Handle corrupt settings the right way. Fixes several issues with the previous implementation.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
=> Add Manjaro Support in System Info #6387

src/cinnamon-screenshot.c
=> remove ENABLE_EXPERIMENTAL_API defines

js/ui/panel.js
See commit messages for a detailed description.
=> Panels: clean up _showPanel and _hidePanel and fix shadow with autohide

src/cinnamon-window-tracker.c
A running gnome terminal window previously lost its association to its
desktop file during a cinnamon restart.
This adds listening to changes in the g_application_id. Upstream, this
fix was intended for Wayland support, but also helps in this situation.
Based on
https://git.gnome.org/browse/gnome-shell/commit/src/shell-window-tracker.c?id=aa3aea75201120226e04450aaf5d58115482031e
=> Fix gnome terminal losing desktop file association during cinnamon restart

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
This fixes #6374, avoiding excessive disk writing, verified by iotop.
=> [cs_panel.py] Better fix for jumping spinbuttons

data/theme/cinnamon.css, js/ui/applet.js, js/ui/boxpointer.js, js/ui/panel.js, src/st/st-theme-node-private.h, src/st/st-theme-node.c, src/st/st-theme-node.h, src/st/st-widget.c, src/st/test-theme.c, src/st/test-theme.css
From upstream https://github.com/GNOME/gnome-shell/commit/2935fd4ffe9176d28f68192bb34bdba1a0e57a2b
and https://github.com/GNOME/gnome-shell/commit/216e996f6680a3ffb797caafe1ed29990360c8f1
=> St: support css margin property

src/st/st-widget.c
https://github.com/GNOME/gnome-shell/commit/4d1358b7ed483b3822ab889e4851cca2c3fa8841#diff-9ad11fdf581414b0f2501e50921d1052
=> st-widget: use g_clear_pointer

data/theme/cinnamon.css
- missing semicolon added
- 3 spaces with 4 spaces replaced
- 5 spaces with 4 spaces replaced
- leading zero (rgba) added
- unnecessary spaces removed
- wrong alpha parameter (rgba) corrected
=> reformatting and fix css

js/ui/main.js
Prevents an error when calling the dbus method
org.Cinnamon.LookingGlass.GetErrorStack
g-io-error-quark: GDBus.Error:org.gnome.gjs.JSError.ValueError: Service
implementation returned an incorrect value type (36)
=> main.js: improve logging of GLib.Errors and objects 

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
caused by commit 3870e42fe58533598ef8998ffb7d6bd3f213cbec
=> Sound applet: avoid spacing problem in vertical panel

js/ui/workspace.js
Please see commits for detailed information. Thank you.
Related issue #6707 (already closed & also referenced as fixes on the commit)
=> workspace.js: Fix scale view zooming, and a harmless warning.

js/ui/deskletManager.js
that the drag logic depends on, and remove the variables that were initialised but never used
=> deskletManager: initialise some variables

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
`nm_device_wifi_request_scan_simple ()` (libnm-glib) wasn't available last time we investigated this.
=> [3.6] network applet: Add a menu item to re-scan for wireless networks.

src/st/st-theme-node-drawing.c
https://github.com/GNOME/gnome-shell/commit/d8540819af7978b3c244877ddb85109a55278bee#diff-8a01b40c2c1be22ef97916811be0ab65
=> [3.6] st-theme-node-drawing: Group multiple cogl_rectangle calls

src/st/st-private.c
https://github.com/GNOME/gnome-shell/commit/7e5f1fe41104dfcf4ca2a104651441ae49ee5865#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6] st-private: Don't create attr lists if we don't need them

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
fixes https://github.com/linuxmint/Cinnamon/issues/4374
=> Translation: fetch some strings with ngettext

js/ui/panel.js
(cinnamon:30929): Cjs-WARNING **: JS ERROR: ReferenceError: i is not defined
Panel.prototype._moveResizePanel@/usr/share/cinnamon/js/ui/panel.js:2678:1
=> Fix regressions when resizing panels, changing monitors

js/ui/panel.js
+ minor correction to regression from 718ce025dc360d62c6e510b5b57483553bf80c1c
=> panel: correct margin calculation in hidpi

src/st/st-drawing-area.c
from upstream https://github.com/GNOME/gnome-shell/commit/ad75739fc5fc03173648a5c7a636b7d7ee0918e5#diff-b0a9fbb0a9269c620f76c568a690c7aa
=> st-drawing-area: Fix Cogl deprecations

src/cinnamon-embedded-window.c, src/cinnamon-generic-container.c, src/st/st-bin.c, src/st/st-box-layout.c, src/st/st-scroll-view.c, src/st/st-table.c, src/st/st-widget.c
I doubt this is suitable for LMDE2
=> various: replace deprecated macros

js/ui/main.js
This allows _logInfo to accept unlimited arguments. In the base _log function, it iterates arguments like before, but now uses a new function called formatLogArgument to format types, inspect nested objects, and format them with indentation. The original logging format with colons for two arguments has been preserved as well.
=> main: Improve logging

src/cinnamon-embedded-window.c, src/st/st-scroll-bar.c
cinnamon-embedded-window changes need correcting from previous commit
=> cinnamon-embedded-window.c, st-scroll-bar.c: Fix deprecations and a minor regression

src/st/st-texture-cache.c
adapted from https://github.com/GNOME/gnome-shell/commit/4184edc7f8cd17e0dbfe5c6c3422b2bf94e85e45#diff-3ca4e78fe4368510730192b6d59c2c80
Premise is that GtkIconTheme now pads icons, so it's dead code. Please comment if you think this premise is not right on the 16.04 base.
=> texture-cache: Remove FBO path for padding icons

src/st/st-texture-cache.c
from https://github.com/GNOME/gnome-shell/commit/f2731d4d6a9ca1338dbc38c8f33fdde0113f9b50#diff-b948bb195b709c61ce7275142a2fbdfd
and https://github.com/GNOME/gnome-shell/commit/df0b465e76305e011c5106d78b6fd19891db900d#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-texture-cache: port to GTask

src/st/st-box-layout.c
From upstream https://github.com/GNOME/gnome-shell/commit/8dab692f93522e3adbe3d03e59ddaca5c9a1e6ee
=> st-box-layout: Fix Cogl deprecations

src/st/st-widget.c
https://github.com/GNOME/gnome-shell/commit/ea55c36a3a2f1abcaa8e202e0f67a29ed807cebe#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-widget: Don't add hidden actors to the paint volume

src/st/st-theme-node.c, src/st/st-theme-private.h, src/st/st-theme.c
https://github.com/GNOME/gnome-shell/commit/f7af96dbb2152c796c5877585e7d1e555471d6ce#diff-c391ade4ef6206f5dd58f1a00c6a6217
https://github.com/GNOME/gnome-shell/commit/9860b1c677430fe96f6afdd95a2958bce398ca62#diff-c391ade4ef6206f5dd58f1a00c6a6217
=> St: avoid blocking IO to resolve relative urls

src/st/st-texture-cache.c
https://github.com/GNOME/gnome-shell/commit/2dc41c944e3594bc0d9636d2515c50a1cbc4f88c
=> st-texture-cache:remove unused base64 code path

src/st/st-icon.c
https://github.com/GNOME/gnome-shell/commit/f5431612341887a339f545ddef5268d362c62755#diff-b9152792660693113ebfebfbd89105a2
=> st-icon: remove custom size request/allocate

src/st/st-scroll-view-fade.c
https://github.com/GNOME/gnome-shell/commit/ce5cd3bf30f9778746b94daa1f68c07854d2cfaa#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-scroll-view-fade: Refuse to work without GLSL

js/ui/cinnamonEntry.js, src/st/st-clipboard.c, src/st/st-clipboard.h, src/st/st-entry.c
e.g. in alt-F2  or menu search entry
=> st-entry: implement middle click paste

src/st/st-scroll-bar.c
https://github.com/GNOME/gnome-shell/commit/2492dc50db89042d19edb2210fdeac7f5c54d8db#diff-b948bb195b709c61ce7275142a2fbdfd
=> scroll-bar: Remove jitter on the scroll bar when moving the mouse

src/st/st-theme-node-transition.c
https://github.com/GNOME/gnome-shell/commit/50f96d1c9cfc422128c5325fbbb03c0ab256d069#diff-58ec506f144fcf489b16beab596a99af
=> st-theme-node-transition: stop using clutter alpha

js/ui/panel.js
This is pretty ugly, but since we add the corners after the fact, they
have their own style class, and they are a child actor of the panel, I
can't think of a cleaner way of handling the extra allocation entirely
inside the panel code.
fixes: ee662c0c178a0ec panel.js: refactor _moveResizePanel
=> panel.js: add some hacks to account for panel corners in clip region

src/st/st-bin.c, src/st/st-widget.c, src/st/st-widget.h
https://github.com/GNOME/gnome-shell/commit/660b801775b9a58428def543edb541e882bf1167#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-bin: delegate popup-menu signal to child if we have one

js/ui/boxpointer.js
https://github.com/GNOME/gnome-shell/commit/d77fc015801e60bb491eac5c5e65cbc347ebb0f4
Do we still use boxpointer ?
=> boxpointer: Don't hide when we're already hidden

js/ui/tweener.js
https://github.com/GNOME/gnome-shell/commit/5bc8a0860a066bba1a1b2b11573e057a20da1a3f
=> tweener: Remove the onAnimationStart/onAnimationComplete callbacks

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
=> window-list: Make sure the progress is shown if its greater than 0 on init

js/ui/main.js
=> main.js: Add search_providers to xlet types in _addXletDirectoriesToSearchPath

js/ui/dnd.js
https://github.com/GNOME/gnome-shell/commit/fce2930b859af8530c4fed9f258e8186649455d2#diff-902d56799170f0dc27500667c665b683
no observable difference in use
=> dnd: Don't queue an idle handler if we already have one

src/st/st-texture-cache.c
https://github.com/GNOME/gnome-shell/commit/44e80f4c46d69d017d495e2ce20d83b4fda66ecf#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-texture-cache: Plug some pixbuf refcount leaks on async operations

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
* search applications by their name first
* match only at word boundaries
* only if nothing was found this way, do the old search
=> improve menu search results (#4053)

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, js/ui/appSwitcher/appSwitcher.js
Implemented an option relating to #6864. This commit adds  an alternative method of alt-tab to the alt-tab appSwitcher utility.
=> Add alternative alt-tab behaviour to appSwitcher

js/ui/workspacesView.js
Fixed spacing. 
Added missing semicolon.
=> code formatting for workspacesView.js

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
-Rework the workaround in 1c513b225a so that the overlay
box only contains the actor we want to overlay, and the
overlaying actor itself. This simplifies the vectorBox
calculations and positioning a bit.
-Reduce code duplication by doing the calculations in a
separate function.
-Ignore invalid coordinates. If the mouse is outside the
overlay box, then we can just destroy or not create the
vectorBox.
-Position the vectorBox to the same size as the
categoriesBox and only change the "point". Avoids having
to reposition the box every time or rely on an ActorAlign.
-Some comments explaining the vectorBox.
fixes #7109
=> menu-applet: rework vectorBox

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
Fix issue #7114: power applet spamming log file with error message on laptop
=> Fix Issue #7114

js/ui/overrides.js
Based on:
https://github.com/linuxmint/cjs/commit/ed7abaa82f0efded5ca155b81d0da47fef4cf956
https://github.com/linuxmint/cjs/commit/a029c273bb195ff9e943ecae922c5a8f7282e004
Before each override, there are checks ending the functions if the patches are already defined.
Tested on CJS 3.4.4 and GJS 1.49.
=> overrides.js: Add Tweener and Signals patches from CJS

src/st/st-theme-node-drawing.c, src/st/st-theme-node-private.h, src/st/st-theme-node-transition.c
https://github.com/GNOME/gnome-shell/commit/882f5fa79e8fd5ef3535a0b190a5ebe04f332286#diff-b948bb195b709c61ce7275142a2fbdfd
adapted
=> st: fix some cogl deprecations

src/st/st-adjustment.c, src/st/st-bin.c, src/st/st-box-layout-child.c, src/st/st-box-layout.c, src/st/st-button.c, src/st/st-clipboard.c, src/st/st-drawing-area.c, src/st/st-entry.c, src/st/st-focus-manager.c, src/st/st-icon.c, src/st/st-im-text.c, src/st/st-label.c, src/st/st-scroll-bar.c, src/st/st-scroll-view.c, src/st/st-theme-node-transition.c, src/st/st-widget.c
https://github.com/GNOME/gnome-shell/commit/cd7d56412544379c877ff0808357cdada3ce4c2d#diff-b948bb195b709c61ce7275142a2fbdfd
=> st: Use G_DEFINE_TYPE_WITH_PRIVATE()

js/ui/magnifier.js
run time warning about unreachable code.  Just commented it all out.
=> magnifier: remove a run time warning

js/ui/dnd.js
https://github.com/GNOME/gnome-shell/commit/69da686fa9dc5dbe8c1dae1b8775108d7117f506
=> dnd: declare some js variables to avoid warning

js/ui/dbusMenu.js
Added spaces when necessary.
Fixed indentation to show the logic being implemented by conditional statement.
Added parenthesis to show order of logic in conditional statement.
=> dbusMenu.js: Formatted code to allow for better readability. 

js/ui/dbusMenu.js
Remove second check `name in MandatedTypes` becouse in this `if` it always `true`.
=> Remove needless check in compareNew

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/ui/dnd.js
Dragging a favorite icon over Catgories/ApplicationsBox changes the cursor to pointing hand, to indicate, that you can remove the favorite from the favorites box.
=> menu-applet: fix dnd cursor icon

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
Hello everybody. 
I opened a pull request (#6988) proposing the same as this one. It was closed due to one-liner code. I removed the one-liner and replaced it with a more expressive code. For details about this commit, please refer to #6988.
=> Improving a piece of code in cinnamon-settings.py (again)

src/st/st-private.c, src/st/st-texture-cache.c
https://github.com/GNOME/gnome-shell/commit/59c2ace98c99db57d085c2fe61f85d2dceff95e4#diff-b948bb195b709c61ce7275142a2fbdfd
=> st: Do not try to unref potentially NULL CoglObjects

generate_additional_files.py, generate_cs_module_desktop_files.py
Note: this requires #6992 to work. Also, fixed a regression caused by e6575fe
=> desktop file gen scripts: port to python3

configure.ac, src/cinnamon-tray-manager.c, src/tray/na-tray-manager.c, src/tray/na-tray-manager.h
https://github.com/GNOME/gnome-shell/commit/ccf1bd9f274fba5fd4951abdb7293e346909fb11#diff-be3d099d55b689509efa06021d82b4f1
=> tray manager: resolve some GdkColor deprecations

src/cinnamon-gtk-embed.c
https://github.com/GNOME/gnome-shell/commit/f563fb124ec9dae29695daefba6f543981f5f36d#diff-488e440b6b0de4e8c39991f999faab35
=> gtk-embed: fix null pointer dereference

src/cinnamon-tray-manager.c, src/tray/na-tray-child.c, src/tray/na-tray-child.h
https://github.com/GNOME/gnome-shell/commit/9acdb8012cdfb99479628df9471afd8c4c46843c#diff-ce7ed307675c0793350595d93693da22
=> tray: remove some deprecations for gdk_window_set_composited

js/ui/search.js
=> Simplify for loop in search

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, js/ui/appSwitcher/appSwitcher.js
=> Added app switcher option for cycle windows on current workspace

files/usr/share/cinnamon/applets/inhibit@cinnamon.org/metadata.json
Also available in Adwaita/Gnome icon theme
=> inhibit applet: use even more common icon

files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
Rework the authentication handling to work with either backend module:
- python pam, ctypes bindings created by Chris Atlee, available on PyPI
and some distros. Forked for python3 support, and available at PyPI as
python-pam and https://github.com/FirefighterBlu3/python-pam
- python PyPAM, CPython binary extension, available on some other
distros, and referencing a dead upstream website (Debian hosts and
builds from *_orig.tar.gz so it is still able to be built).
The current method allows importing either module without failure, but
then spawns internal errors if pam is used instead of PyPAM due to the
two modules containing entirely different APIs.
Also re-raise internal errors and change the tooltip to indicate that
something went wrong. If something unidentifiable happened, error …
=> cs_user.py: Add compatibility for multiple pam modules

src/cinnamon-recorder.c
=> cinnamon-recorder: Update for new cogl apis

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
`microphone-sensitivity-none` does not exist in Adwaita, it's `microphone-sensitivity-muted`.
=> Sound applet: fix missing muted icon

files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js
Adwaita has a new icon `system-switch-user` https://github.com/GNOME/adwaita-icon-theme/commit/eb790fa0dcc572ba51f980db14e3114b13faf479?short_path=ec09c29#diff-ec09c29e420ceb72ba8b7188b3923bf4
=> user applet: use system-switch-user icon

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
=> keyboard applet: horizontal centering text

data/icons/Makefile.am, data/icons/hicolor_apps_scalable_removable-drives.svg
I want it to use for the removable-drives applet.
It's the icon `usermount` from the Mint-X theme
=> hicolor icon: Add removable-drives icon

js/ui/messageTray.js
-Improves mouseover performance with long notification text.
-Allows scrolling the notification tray through notifications.
See commits for more information.
=> Notifications fixups

js/ui/messageTray.js
* Reduce huge gap in top notifications (it was twice the top panel height).
* Fix bottom notification position with multiple monitors (it appeared in the middle of the monitor above the main one).
=> Fix notifications position

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
=> Sound applet: move close button to the right

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Hi,
This PR is made to solve the issue #7375.
Best regards.
claudiux
=> sound@cinnamon.org applet - Solves issue #7375

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
=> Sound applet: make optional horizontal scroll to move between tracks

js/ui/popupMenu.js
This also avoids calling functions that call functions in some cases and improves readability.
Avoid using filter + map, that created two arrays
=> PopupMenu.js: Use some lambdas to create half the functions on each action

js/misc/util.js, js/ui/main.js
This adds more clear logging of GObject properties via `global.log`, so the object keys and values are printed like any other JS object. There are some objects it cannot log due to a `non-null` pointer error, mainly MetaScreen, and those are indicated in the logging output.
`getGObjectPropertyValues` is added to util.js, which could also possibly be used by Melange.
=> Debugging: Add GObject property value logging

js/ui/radioButton.js
Use `for of` instead of `for in` for arrays for performance.
=> Use for of for arrays

files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py, js/ui/hotCorner.js
=> Allow colons in hot corners commands

js/ui/notificationDaemon.js
GNOME/gnome-shell@326d5c7fb8d07b9751edf315668a85cd6b5a9b32
=> notificationDaemon: Fix fallback icon names

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
* Causes an error in a download to only display a single error message rather than one for each file. A missing image from the image cache will still cause the download to abort, but the user will now only get a single dialog instead of many.
* Better fault tolerance.
Should fix #7499 though I'm not sure how to test that particular case.
=> Spices.py: refactor downloading code for better error handling

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
Display a keyboard backlight section on the brightness tab if it's found (and only if there's a brightness section.)
=> cs_power.py: Display a keyboard backlight section on the brightness tab

js/ui/keyboard.js, js/ui/messageTray.js, js/ui/panel.js, js/ui/popupMenu.js, js/ui/tooltips.js
=> Fix various cases of invalid object access

docs/search-providers-examples/calc@cinnamon.org/search_provider.js
Remove unused imports and avoid creating unnecessary objects on each key press.
=> Update calculator search provider example

docs/search-providers-examples/apt@cinnamon.org/search_provider.py
=> migrated print to py3 - line 19

js/ui/lookingGlass.js
Fixes window tracker updating when non-string window properties are encountered, also filters windows to the same as alt-tab/window-list/etc use.
=> looking glass window tracker cleanup/fix

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Found via reddit user Kokefageln.
```
Cjs-Message: 08:21:48.140: JS LOG: [LookingGlass/info] entry.get_app_info(...) is null
Cjs-Message: 08:21:48.140: JS LOG: [LookingGlass/trace]
<----------------
_loadCategory@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:2660:22
_refreshApps@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:2519:21
_refreshAll@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:1198:13
---------------->
```
```
(cinnamon:1487): Cjs-WARNING **: 08:24:51.624: JS ERROR: TypeError: this._activeContainer is null
_onMenuKeyPress@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:1822:21
```
=> menu: Fix issues preventing the container children from rendering

src/st/st-scroll-view.c
=> StScrollView: Clean up gsettings on dispose

js/ui/tooltips.js
Generic tooltips already supported margins.
> EDIT: I squashed both commits.
=> Allow margins in panel tooltips

docs/search-providers-examples/trackerprovider@cinnamon.org/search_provider.py
=> migrated print to py3 - line 62

js/ui/appFavorites.js, js/ui/overrides.js, js/ui/panel.js
Style/Maintainability autofixes by CodeFactor.
=> CodeFactor style fixes

files/usr/share/cinnamon/applets/inhibit@cinnamon.org/applet.js, js/misc/gnomeSession.js
I needed to track down what was inhibiting my computer from suspending, came across #7175 in my searching, and followed @troxor's helpful instructions in one of the comments to do so. Figured I'd take a stab at implementing the feature so the next guy/gal doesn't have to retrace my steps. :)
Screenshot in St.Side.BOTTOM orientation. The list appears below the switches in other orientations.
=> inhibit applet: Display list of inhibiting programs

js/misc/params.js
Fixes #7941 regression caused by 310e57c.
It also broke notifications.
=> Fix broken hot corners and notifications

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
Left clicking active window on the window list will minimize
the window. This adds a setting to disable that behavior.
=> Issue #7922: Add setting to window-list applet for minimizing.

js/ui/panel.js, js/ui/popupMenu.js
```
Cjs-Message: 01:55:27.248: JS WARNING: [/usr/share/cinnamon/js/ui/panel.js 2919]: reference to undefined property "height"
```
=> panel: Fix undefined height warning

README.rst
- Merge lines 3 and 4 to remove an instance of "the"
- Rewrite line 5 to be more concise, to remove "the", and to remove an instance of "and"
=> Reduce word duplication in README.rst

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/constants.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json, js/ui/environment.js
This is intended to help improve the readability of the window count numbers with light themes such as Mint X.
=> gwl: Give the number label badge styling, misc. clean up

js/ui/indicatorManager.js
Adapted from https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/5ed40db2f4a9dc8dd31ff3d06dbe2e2115f1c6ad
Closes #6143
=> indicatorManager: Fix icons not appearing

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This PR fixes several issues, which were introduced by changing the favoritesBox to a scrollable Box
=> menu-applet: several fixes

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
Keep track of unmanaged networks (and listen to their
state changes) but don't let them show up in the network lists, and
don't have them count when it comes to section titles.
This follows up on a an initial effort to hide unmanaged networks but
which didn't take into account the possibility of those networks later
becoming manageable.  The revert commit, link to the original, as well
as some explanation is here: a1281a5d12584cbb6d0a183.
=> network applet: Keep track of, but don't show, unmanaged networks

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json
=> gwl: Improve thumbnail scaling for lower resolutions

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
Fixes a regression from
https://github.com/linuxmint/Cinnamon/pull/7986/commits/d8363555dda871694dd60f70599cb7f069165171#diff-6d205dd604643e038132e5ec87136ae4R561
Closes #8043
=> gwl: Fix focus change

js/ui/runDialog.js, src/cinnamon-global.c
Depends on https://github.com/linuxmint/muffin/pull/385
=> Make transitions between restarts seamless

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
=> gwl: Round the actor transformed position

files/usr/share/cinnamon/applets/slideshow@cinnamon.org/applet.js
the icons were invisible and the applet was therefore barely usable
Fixes #8024
=> fix broken slideshow applet

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, js/ui/environment.js
Thumbnail menu and context menu construction now occurs when they are needed, and removes some left over timeout_add deferring from ITM.
=> gwl: Speed up initialization

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
Closes https://github.com/linuxmint/mint-19.1-beta/issues/49
=> gwl: Always check the skip-taskbar hint

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
Closes https://github.com/linuxmint/mint-19.1-beta/issues/47
=> gwl: Fix DND ops originating from menu items leaving large gaps

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
Closes https://github.com/linuxmint/Cinnamon/issues/8131
and fixed some indentations
=> Preferred Applications: Add entry for "PDF" viewer

src/st/st-entry.c
https://github.com/GNOME/gnome-shell/commit/e2838a7e06508cd412592e621572d7fda27130ec#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-entry: remove an explicit destroy

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
Closes https://github.com/linuxmint/mint-19.1-beta/issues/78
=> gwl: Fix progress not fully resetting when the last window from a group is closed

js/misc/util.js
Fixes the error callback not being invoked.
=> misc/util: Fix typo in tryFn function

src/st/st-bin.c
https://github.com/GNOME/gnome-shell/commit/b719744e75e56502cf0340066f9311fdcc755628#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-bin: Destroy child in ClutterActor:destroy vfunc

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
The progress code was originally based on the Cinnamon window list's code, but it didn't account for things GWL needs to account for, such as multiple windows with progress sharing a single button.
This also splits the progress allocation into a stand-alone function so we don't have to call `queue_relayout` when just the progress is changing, and fixes the progress not showing after the applet or Cinnamon is restarted.
This was tested by using the [xapp-gtk-window](https://github.com/linuxmint/xapps/blob/master/test-scripts/xapp-gtk-window) script in the xapps repository, clicking "Create shortcut" in GWL's context menu, and opening the script from the generated desktop file so it can be pinned/grouped.
Depends on #8160
=> gwl: Average the progress of all windows belonging to an app group button

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
=> gwl: Fix thumbnails not populating the menu when opened by click

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
- Fixes very minor memory 'leak' where we added the application id string to a list of known apps every time it was launched, instead of once the first time the app became known.
- Fixes transient and search provider buttons possibly being left around forever.
- All the rest is code simplification, duplication reduction, and removal of unneeded code
=> Various menu improvements

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
=> gwl: Fix the thumbnail menu not closing on leave after closing a window

js/ui/windowManager.js
Reduce the number of signal listeners
=> WindowManager: JS code optimizations

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, js/ui/workspace.js, src/cinnamon-screenshot.c
Depends on https://github.com/linuxmint/muffin/pull/410
=> Replace MetaShapedTexture usage with MetaWindowActor

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Avoid creating functions inside loop warning by adding a new callback
params argument to RecentContextMenuItem class so we don't have to
capture scope within the loop.
=> menu applet: fix last eslint warning

files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py
Adding natural scrolling for mouse using 2 different namespace for the setting
Depends on https://github.com/linuxmint/cinnamon-settings-daemon/pull/246
=> Mouse settings: Add natural-scroll support for mice

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
This improves the workspace switcher visual style in the following ways:
- The clutter.actor with layout manager was removed and buttons are now added directly to the actor box. Part of this change means that the spacing is no longer hard-coded and can be conrolled by the theme.
- Events that trigger the creation of new buttons now queue said creation in an idle callback rather than recreating them directly. This potentially reduces the number of times they are recreated (for example at startup there could be several events that trigger them to be regenerated, but they really only need to be regenerated once, after all the signals are fired).
- An issue is now fixed where the creation of struts didn't trigger the regeneration of the buttons, so the wrong workarea was often used in size …
=> Workspace switcher applet: various improvements to the graph style

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/applets/printers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/printers@cinnamon.org/cancel-print-dialog.py, files/usr/share/cinnamon/applets/printers@cinnamon.org/lpstat-a.py, files/usr/share/cinnamon/applets/printers@cinnamon.org/metadata.json, files/usr/share/cinnamon/applets/printers@cinnamon.org/settings-schema.json
This applet is a fork of the printers applet from cinnamon-spices (https://github.com/linuxmint/cinnamon-spices-applets/tree/master/printers@linux-man) by @linux-man. Thanks and credits to @linux-man for his great work on this applet!
=> Add printers applet

files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py
Depends on https://github.com/linuxmint/muffin/pull/452
=> Make the sync method configurable

js/ui/layout.js
Ref https://github.com/linuxmint/cinnamon/issues/8454#issuecomment-493791789
=> layout: Ensure regions update after the keyboard is hidden

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/misc/util.js, js/misc/windowUtils.js, js/ui/appSwitcher/appSwitcher3D.js, js/ui/layout.js, js/ui/messageTray.js, js/ui/windowEffects.js, js/ui/windowManager.js, js/ui/workspace.js, src/cinnamon-screenshot.c
Reverts rect caching and obstructed windows optimizations.
See https://github.com/linuxmint/muffin/commit/15b2621bfe3b881c5d27ab97d3aca4f970bd1f05
=> Revert rect caching and obstructed windows optimizations

files/usr/share/cinnamon/cinnamon-settings/modules/cs_privacy.py
https://bugzilla.gnome.org/show_bug.cgi?id=737362
=> Privacy settings: Add support for connectivity checking

data/theme/cinnamon.css
Fixes https://github.com/linuxmint/mint19.2-beta/issues/76
Before
After
=> Stock theme - improve modal and run dialog layout

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
=> menu applet: fix typo in system box nav fix

src/cinnamon-global-private.h, src/cinnamon-global.c, src/st/st-theme-node.c
=> Fix some compile warnings.

js/ui/panel.js
Organized the panel-related items into a panel submenu, some other
reorganization.
=> panel.js: Simplify the initial panel context menu.

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
as suggested by @clefebvre in https://github.com/linuxmint/cinnamon/pull/8775#issuecomment-522583675
=> xlet-settings.py - Adding option to reload the xlet in the burger menu of its configuration screen

js/ui/panel.js
=> panel: minor correction to context menu code

files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py, files/usr/share/cinnamon/cinnamon-screensaver-lock-dialog/cinnamon-screensaver-lock-dialog.py, files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/desklets/launcher@cinnamon.org/editorDialog.py, makepot
~~Second part to fix~~ Fixes entirely https://github.com/linuxmint/mint19.2-beta/issues/66 and https://github.com/linuxmint/cinnamon/issues/8737.
=> Fix translation issues

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Uses SignalManager for most signals, and makes sure more stuff is cleaned up over the applet lifetimes.
This fixes the invalid access warnings when toggling panel edit mode with a window-list added.
=> panel-launchers/window-list signal cleanup

cinnamon.pot, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
This feature work on linux mint mate.
=> Added option to open gnome-disks

files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js
Possible solution for #8843 
I also padded/truncated the window titles to arbitrary 30 characters for aesthetics.
=> Fix window closing for windows quick list applet. Truncate titles.

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
Depends on https://github.com/linuxmint/xapps/pull/77
=> SettingsWidgets: Add the ability to set the default category

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
-don't try to destroy menuManager for alerts
-use only one mainloop function to flash alert style
-use signalmanager for style-changed signal
-unbind all applet settings on remove from panel
=> window-list: fixups

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py, js/ui/panel.js
=> Per-zone scalable symbolic icons, text

files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js
Switch to a themeable container and give 2px padding on either end of the icon container for bringing up the applet menu.
Make ctrl-right-click perform this as well.
=> xapp-status@cinnamon.org: allow removal from the panel

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
fixes: https://github.com/linuxmint/mint19.3-beta/issues/13
=> menu-applet: fix order of places

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/settings-schema.json
=> notifications: add button in applet settings, to open system settings

js/ui/placesManager.js
Hi @mtwebster,
This PR replaces the #8978 one and closes #5377.
EDIT2: ~~This must be tested.~~ Successfully tested on many real and virtual machines, with many type of drives and devices (USB sticks, external disk, data DVD, video DVD, music CD).
EDIT: The `ci/circleci: lmde3` errors do not come from this script.
Best regards.
Claudiux
=> placesManager.js: Management and notifications improvements - Solves #5377

debian/control, files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
=> python 3.8 compatibility fix for platform.linux_distribution()

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py
It's redundant since the widget already knows it changed anyway. In the case of the editable list in particular, it causes noticeable performance issues and visual jumping when the list is large enough.
Fixes #9157
=> JsonSettingsWidgets: don't call callback on the widget that was changed

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Added new keywords "microphone" and "headphones" for sound.
=> Added new keywords

debian/control, files/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py
tinycss’s last commit is in 2016, port it to tinycss2
=> Port tinycss to tinycss2

js/ui/backgroundManager.js
I just refactored one module to modern class from old prototype style
=> backgroundManager: refactor from prototype to es class

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py
fixes #9305
The import was removed by this commit https://github.com/linuxmint/cinnamon/commit/532cb60fa7d51c7000cb1c7260e7c008946d8f61
I recommend its inspected for other regressions.
=> Readd import, fixes #9305

js/ui/edgeFlip.js
I just refactored one more module to modern class from old prototype style
=> edgeFlip: refactor from prototype to es class

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
=> Correct Disks icon in System Settings

js/ui/osdWindow.js
Code taken from https://forums.linuxmint.com/viewtopic.php?t=312162
Related to issue #9327
I'm guessing there's a reason this change hasn't been proposed on GitHub yet, but I did a quick search and I didn't see anyone attempt it so :sweat_smile:
It's really @smurphos  code
=> Add Percentage Label to OSD for Volume Control

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
=> [sound@cinnamon.org] Update applet.js - Fixes #9283

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
- Buttons are sorted before they're sorted into their respective
lists, so their original order within the app box can always be
restored.
- When a search is made, an index is assigned to resulting items,
corresponding to the position of the pattern within the search
string. The four app search strings (name, keywords, description,
id) are weighted, so name matches come before keywords, and so on.
- Places will always display after apps, and recents after places,
maintaining their original respective positions.
Sorting is done simply by comparing the search indices for all
matching buttons:
Examples:
- Given two apps with with the names "File" and "The File", and
search string "file", "File" has an index of 0 (matched at start of
string), "The File" has an index of 4 (matched at position …
=> menu@cinnamon.org: Allow items to be re-ordered to better reflect the search outcome.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
=> Update cs_panel.py: Fixes #9487

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/ui/panel.js
Fixes:
- dragging applets in panel edit mode
- dragging windows in ```grouped-window-list@cinnamon.org```
- dragging windows in ```window-list@cinnamon.org```
- dragging launchers in ```panel-launchers@cinnamon.org```
=> Fix RTL bugs in panel and applets

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
This consists of 3 PRs (involved repositories: cinnamon, cinnamon-session, cinnamon-settings-daemon)
=> add suspend-then-hibernate (issue cinnamon-settings-daemon:#237)

js/ui/applet.js, js/ui/appletManager.js
Added uuid formatted ex from menu@cinnamon.org to 
menu-cinnamon-org-applet, this allow for a better css property apply, so 
theme more better tuned is possible
=> [FEAUTURE] [BETTER THEMING] add applet uuid formatted as style class name

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
This PR addresses #9229 
Adjusted the logic to correctly check the values set for the left click action and mouse wheel scroll action.
=> Fix for issue 9229 (GWL)

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
The technical explanation is in the commit description
This will hopefully fix issue #9567
=> Fix issue 9567

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
@mtwebster  
Hi Michael,
Can you review these changes, please?
Regards.
Claudiux
=> Update xlet-settings.py: Code debug

man/cinnamon-looking-glass.1, man/cinnamon-screensaver-lock-dialog.1
These was added in debian packages some years ago by Nicolas Bourdaud and
Maximiliano Curia did a minor changes on cinnamon-looking-glass.1
=> Add 2 man pages from debian packages

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/network@cinnamon.org/settings-schema.json
Add possibility to quick change VPN, network, etc.
=> network@cinnamon.org - add keybinding to show applet menu

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
This fixes #9650, fixes #9219, fixes #8377.
=> GWL appList.js: Fix issues #9650 #9219 #8377

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
Found this while working on  #9634
=> Fix placeholder size in panel-launchers not scaling correctly

files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
"Browse for more images" has a missing import  when adding a image.
=> Add missing GdkPixbuf import

js/ui/applet.js, js/ui/desklet.js
Modified files:
* js/ui/applet.js
* js/ui/desklet.js
=> Adapt configureApplet and configureDesklet to xlet-settings which has a -t option to select the tab to display (default: 0)

js/ui/checkBox.js
I just refactored one more module to modern class from old prototype style
=> checkBox: refactor from prototype to es class

js/ui/extension.js
a leftover from previous commit, was giving a message in the log file about unreachable code
=> extension.js: remove superfluous line causing warnings

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
depends on https://github.com/linuxmint/xapp/pull/119
=> menu-applet: change favorites category icon

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
This PR resolves [issue 49](https://github.com/linuxmint/mint20.1-beta/issues/49) from 20.1 beta.
=> Adds Cycle Apps functionality back

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
=> Power applet: Use spaces after commas.

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
Fix #9200, #9080, #9153, #9822
Those changes solve a set of GWL bugs that occur depending on how an app window is moved to another workspace. Please,
see the video attached.
https://user-images.githubusercontent.com/38897885/104819947-06b24700-5810-11eb-8026-3438db913d53.mp4
=> GWL-fixes: move window to another workspace

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
Grouped-Window-List: Fix list refreshes after closing a window causing a reordering of the window list.
Caused since 4c1aa69b4662c7091e5a2d29e72aa404ad801424
Fixes #9802, Fixes #9845, Fixes #9900
=> Grouped-Window-List: Fix list refreshes reseting window order after close

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
Fixed a problem where if you finish a launcher darg move outside of the applet area, the changes are not saved.
=> Grouped-Window-List: Fix changes not saving after dragging a launcher

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, js/ui/appletManager.js, js/ui/cinnamonDBus.js, js/ui/deskletManager.js, js/ui/extensionSystem.js
=> Issue 9097. Send signal when applets, desklets, or extensions are done loading.

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
=> Issue#10052: fix window-list drag+drop for windows from other desktops

src/cinnamon-window-tracker.c
This fixes #9951 by moving the match against the info from the .flatpak-info file further down the line
=> Fix a flatpak window mismatch

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/misc/fileUtils.js, js/misc/util.js, js/ui/main.js, js/ui/placesManager.js, js/ui/popupMenu.js, js/ui/workspace.js
I applied spread operator where appropriate.
=> Use spread operator instead of concat

js/ui/dnd.js
=> Issue 10089. Cancels escaped drag on desklets

js/ui/deskletManager.js
=> Issue 9834. Desklets snap functionality works as expected

js/ui/dbusMenu.js
I refactored dbusMenu from prototype to es class syntax.
=> Refactor dbusMenu to es class

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
=> Properly hide JavaEmbeddedFrame on Grouped Window List

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
insensitive is the common style class that most themes are going to be
expecting.
=> sound-applet: use insensitive not disabled

data/theme/cinnamon.css, js/ui/modalDialog.js, js/ui/runDialog.js
Right now these dialogs are a little ugly. Add some titles and proper styling so they look a bit nicer.
=> Add some styling to Cinnamon's dialogs

js/ui/windowManager.js, src/cinnamon-util.c, src/cinnamon-util.h
Everything works well except the unminimize animation. Not sure what is
going on there.
=> windowManager.js: Restore the remaining window animations

js/ui/boxpointer.js
This block of code appears to be a copy and paste of the ResX code just
above. It looks like one variable was missed in fixing this up.
=> Fix a typo

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
use requests library instead of low level APIs to simplify code
=> Spices.py: simplify _url_retrieve

debian/cinnamon-common.install, debian/control, debian/copyright, debian/rules
- d/control: require cinnamon-settings-daemon >=5.3
- readd dh-python and add override_dh_python3 from debian packages
- restore override_dh_makeshlibs
- wrap and sort
- update debian/copyright
=> [muffin-5.2-test] improve debian packaging

files/usr/share/cinnamon/cinnamon-settings/bin/KeybindingWidgets.py
There are some valid cases for wanting to be able to do this.
Closes #9518
=> keybindings: Warn, but don't forbid assigning normal keys for shortcuts.

src/st/croco/cr-utils.c
As the title says. Bug report already suggested the fix.
=> Fix a typo #9756

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, js/ui/slider.js
=> Slider.js: Support inverting on rtl layout

files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js
When the XApp Status Applet is placed on a vertical panel the location
of the tooltip is always in the same place (middle of the applet box
rather then aligned with the app status icon that the mouse is hovering
over). This fix uses a unique Tooltip instance for each status app icon
so that the tooltip will be properly aligned with the icon in all cases.
=> Fix the XApp Status Applet tooltip placement on vertical panels

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_privacy.py
This pull request boosts the startup time of cinnamon-settings noticeably by making the following changes:
1. ~Compile all python files in the `cinnamon-common` package during installation by using the python3 debhelper~ Edit: dropped as discussed below
2. Defer loading of heavier python packages (like `requests` or `imtools`, both ~50ms on my AMD Zen 3 dev machine). This has a noticeable effect, because all loaded python modules (`cs_*.py`) and their dependencies will be loaded at start time. Instead, import them before they are really used. Thus, the startup time will be shorter in any case.
3. The largest change attacks the before mentioned behavior that **all** modules are loaded in *any case*. This means that the "import (time) heavy" settings modules like the cinnamon spices x-lets …
=> cinnamon-settings: noticeably accelerated startup time

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
Fixes https://github.com/linuxmint/cinnamon/issues/10659, maybe also https://github.com/linuxmint/cinnamon/issues/10306
=> power applet: fix device duplicates

debian/control, files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
Added copy to clipboard button in system settings.
Screenshot:
=> [WIP] Add copy to clipboard in system settings

js/ui/windowManager.js
This was the last remaining thing in windowManager.js. Do a bit of cleanup
and port to ease_property().
=> windowManager.js: Port the dimmer to the new ease() functions

files/usr/share/cinnamon/cinnamon-settings/bin/util.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
This fixes a problem where testsounds for specific channels would be played via all channels
=> Fix testsound channel usage

data/theme/cinnamon.css
https://github.com/linuxmint/mint21-beta/issues/70
=> theme: Fix artifacts in the menu applet when scrolling the applications

files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
fixes https://github.com/linuxmint/mint21-beta/issues/106
=> Menu applet: Fix typo.

data/theme/cinnamon.css
A previous PR fixed some of the theming but I missed a part of it. This
completes it.
=> theme: Finish fixing the gwl thumbnail theming

js/ui/locatePointer.js
In tandem with linuxmint/muffin#638
=> Support multiple key bindings for 'locate-pointer-key'

files/usr/share/cinnamon/cinnamon-screensaver-lock-dialog/cinnamon-screensaver-lock-dialog.py, files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
In python triple quoted strings should be used for docstrings.
=> fix python docstring style

files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py, js/ui/messageTray.js
In tandem with linuxmint/cinnamon-desktop#215
Closes #3896
=> Add a setting for notification duration

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
- Split all the preferred applications into different categories like System, Office etc.
- Add separate option for MS Excel files
- Fix a few gettext strings
=> Categorize default applications

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
=> Add key bindings to move window to workspace up/down

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py
Cario is currently not unused in this file, so I removed it
=> remove unused import cairo

docs/search-providers-examples/chromium-history@cinnamon.org/search_provider.py, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/utils.py, files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py, files/usr/share/cinnamon/desklets/launcher@cinnamon.org/editorDialog.py, tests/interactive/urgentwindow.py
I have done some simplification to boolean expressions.
The main change is instead of inverting an `in` condition with `not`  I used `not in`.
=> simplify boolean expressions

files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/settings-schema.json
When you hover the cornerbar and make a scroll-move, e.g. with two fingers up/down on touchpad, you will slide through your workspaces.
=> cornerbar@cinnamon.org: added scroll-event from SW++@mohammad-sn

data/org.cinnamon.gschema.xml, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, js/ui/appSwitcher/appSwitcher.js
* Add a second commit to fix whitespace
=> Add a setting to warp mouse pointer after Alt+Tab action completes

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Discussion here https://forums.linuxmint.com/viewtopic.php?p=2227731#p2227731
=> feat(menu@cinnamon.org): Add Menu editor entry to applet context menu

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py
Fix scope error that prevents user from accessing Themes page
=> update ChooserButtonWidgets.py: Fix scope error that prevents user from accessing Themes page

js/ui/placesManager.js
=> Update placesManager.js to fix #11623

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
requires: https://github.com/linuxmint/cinnamon-settings-daemon/pull/379
please refer to that PR for more info.
thanks!
=> power: Add settings to disable low battery warnings for connected devices

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
Fix list of available themes not updating when theme added or removed from a theme directory.
+fix an inline code comment.
fixes #11696
=> cs_themes.py: fix themes not updating

js/misc/fileUtils.js
@mtwebster 
About https://github.com/orgs/linuxmint/discussions/48
=> Update fileUtils.js to avoid error messages

data/org.cinnamon.gestures.gschema.xml
Closes https://github.com/linuxmint/mint21.2-beta/issues/27
=> Gestures: Update the default swipe actions

files/usr/bin/cinnamon-close-dialog
=> cinnamon-close-dialog: Fix dialog text

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This is in tandem with linuxmint/mint-themes#453
Discussion: linuxmint/discussions#79
=> sound@cinnamon.org: Word wrap for artist and title labels

docs/reference/cinnamon-tutorials/write-applet.xml
=> Updated write-applet.xml for Cinnamon 4.6 to 5.8+

files/usr/share/cinnamon/applets/calendar@cinnamon.org/eventView.js
=> Fix issue #11810

js/misc/state.js
This is a follow on from commit https://github.com/linuxmint/cinnamon/commit/e4b39d33273cdf5f83f786063a68de5e437db18b (PR #11871)
=> state.js: replace util.js polyfills with js natives

docs/reference/cinnamon-js/meson.build, docs/reference/cinnamon-tutorials/meson.build, docs/reference/cinnamon/meson.build, docs/reference/st/meson.build, meson.build, src/st/meson.build
Similar to linuxmint/cinnamon-control-center#318
Similar to linuxmint/cinnamon-desktop#234
Similar to linuxmint/cinnamon-menus#67
Similar to linuxmint/cinnamon-screensaver#444
Similar to linuxmint/cinnamon-session#155
Similar to linuxmint/cinnamon-settings-daemon#383
Similar to linuxmint/cjs#119
Similar to linuxmint/muffin#675
Similar to linuxmint/nemo#3316
Similar to linuxmint/nemo-extensions#496
Similar to linuxmint/xapp#172
=> Fix meson.build deprecations up to 0.56.0

.git-blame-ignore-revs
Discussion: linuxmint/discussions#38
=> Add .git-blame-ignore-revs for commits

js/ui/gestures/gesturesManager.js
Add a missing declaration and fix the mis-naming of a variable
=> gesturesManager.js: Fix a couple small issues

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Work for me, it's usefull sometimes to checkout run command.
Please consider merging this Pull Request
=> Added menu details option

python3/cinnamon/harvester.py
Fixes https://github.com/linuxmint/cinnamon/issues/11964
=> actions: fix update procedure

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
Maybe fixes #10225 (at least partially).
=> [network@cinnamon.org] - Try to fix #10225

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
=> sound applet: Fixes #12035

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js, js/ui/polkitAuthenticationAgent.js, js/ui/userWidget.js
Ported from Gnome Shell as a convenient widget to use in the new Polkit dialog. Also use in the user applet and can be used in other places like a new screensaver implementation.
=> Add userWidget.js

data/icons/hicolor_categories_scalable_cs-actions.svg
IMHO something easier to understand
@rcalixte  any opinion?
=> New action icon for Mint-X theme

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js
Updates to https://cinnamon-spices.linuxmint.com/strftime.php
Fixes https://github.com/linuxmint/cinnamon/issues/12162
=> Update Show information on date format syntax URL to working one

files/usr/share/cinnamon/applets/show-desktop@cinnamon.org/applet.js
=> show desktop applet: Fix desktop peek

js/ui/main.js, js/ui/overrides.js
Remove overrides that don't do anything on mozjs 102. Also remove String.prototype.first_cap as it's not used by cinnamon or any xlets.
=> Remove unused js overrides

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
=> Prevent window randomization on connecting a monitor

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/constants.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
I also made a slight improvement to the scale animation adding a small bounce back on the end of the returning to the original Icon size.
=> gwl: Port to Clutter animations

js/ui/userWidget.js
The design for this was taken from Gnome shell and does more then we really need. It also doesn't seem to work properly when using the UserWidget object. Simplify it down a bit to fit our needs and make it actually work.
=> userWidget: Simplify a bit

js/ui/environment.js
Add hookup_style() to bind layoutManager properties to CSS properties
=> environment.js: Add some convenience LayoutManager monkey patching

js/ui/deskletManager.js
resolves https://github.com/linuxmint/cinnamon/issues/11398
=> deskletManager: Only display drag placeholder for desklets

data/theme/cinnamon-sass/widgets/_dialogs.scss, js/ui/audioDeviceSelection.js, js/ui/main.js
Requires: https://github.com/linuxmint/cinnamon-settings-daemon/pull/401
=> Add a clutter audio device selection dialog

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
closes https://github.com/linuxmint/cinnamon/issues/12393
=> sound applet: player icon should not take priority over mute icon

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
Fix merge conflict caused by previous two commits. https://github.com/linuxmint/cinnamon/commit/3e1fca6a33961bed0a18eb773565db8cfbfb6122 and https://github.com/linuxmint/cinnamon/commit/2047cb35a60e44e063d7f80191f44293ab5d561a
=> GWL: Fix merge conflict

data/theme/cinnamon-sass/widgets/_dialogs.scss, js/ui/cinnamonDBus.js, js/ui/dialog.js, js/ui/endSessionDialog.js, js/ui/main.js
Move all cancel buttons to the left
Ensure ESC closes the dialogs
Restyle inhibited apps
Make the default styling work in themes without support
=> endSessionDialog: Restyle the dialog

files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
=> Update TreeListWidgets.py: Fixes #12545

data/theme/cinnamon-sass/widgets/_menus.scss
https://github.com/linuxmint/mint22.1-beta/issues/23
=> theme: Fix rounding in submenus

data/theme/cinnamon-sass/widgets/_windowlist.scss
Missed a couple things in a previous commit. Should have them all now.
Fixes: https://github.com/linuxmint/mint22.1-beta/issues/61
=> theme: Fix more radius issues in GWL window previews

data/theme/cinnamon-sass/widgets/_windowlist.scss
Fixed a issue #12663 Window preview corners on the left are spiky when hovering over it
=> Fixed issue with grouped-window-list-thumbnail-menu hover

js/ui/polkitAuthenticationAgent.js
=> polkitAuthenticationAgent.js: Allow root authentication if there are no admin users

js/ui/polkitAuthenticationAgent.js
Following up 9c8a15b62f573, user accounts marked as system accounts in AccountsService needed to be treated similarly to root accounts when authenticating in a non-admin session.
Fixes linuxmint/linuxmint#765.
=> polkitAuthenticationAgent.js: Handle system accounts properly.

files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/applet.js
when the workspace settings "cycling trough workspaces" is enabled, user can cycle trough workspaces with mouse wheel on cornerbar applet
=> cornerbar applet workspace cycle with mouse wheel
