files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Changed the flow on which you change between windows using the mouse scroll. At first I thought it was just me, but hey, this is inconsistent with the workspace switcher, for example. And also other programs like Google Chrome(changing between tabs with the scroll).
(This is my first contribution to a project, so sorry if I was inconvenient in any way)
=> window-list applet: Tiny fix on funcionality

files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py, js/ui/settings.js
As an applet author, I want to clarify what certain settings do when applied together, or give additional instruction to the user within the configuration pane of my applet. Currently the only way to do this is through extensive use of tooltips, which the user may or may not see (or bother to read if they are too long).
This `label` type is the same as `header`, except the markup comes from the description. It may read as duplication of code but I'd like the ability to use regular labels amongst settings and not have bolded text everywhere.
@mtwebster please review and consider either this or another way of supplying parameters to the `header` type such that it could be used as a label. The ability to use our own limited markup from settings schemas would be very nice though.
Sample use …
=> Settings: Add xlet widget of type=label for plaintext labels

files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py
Currently all settings widgets allow the use of a `tooltip` property except the Keybinding widget. This is a minor and harmless change to enable it here as well.
=> Settings: Add missing tooltip for Keybinding xlet widget

js/ui/runDialog.js
If you run rt (reload theme) at Alt-F2, xlets' stylesheet do not get reloaded and they will look broken. xlets listen to theme manager to reload stylesheet when necessary, so calling themeManager instead of main can solve the problem
=> Update xlet stylesheet as well on rt

data/org.cinnamon.gschema.xml.in, files/usr/lib/cinnamon-settings/bin/SettingsWidgets.py, files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py, files/usr/lib/cinnamon-settings/bin/tweenEquations.py, files/usr/lib/cinnamon-settings/bin/windowEffects.py, files/usr/lib/cinnamon-settings/modules/cs_effects.py, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json, js/Makefile.am, js/ui/settings.js, js/ui/windowEffects.js, js/ui/windowManager.js
Depends on linuxmint/cjs#18
new super class `BaseChooserButton`
- For cs_effects
- displays static previews (can be improved)
- starts an animation on hover
#3603
- For cs_effects and Xlet settings
- displays static graphs
- starts an animation (a little arc moving up)
#1682
Effect | Mapping | Closing and Minimizing
-----|-------|------
Blend | Window fades in and scales from 1.5 down to 1 | Window fades out and scales to 1.5
Move | starts at the current mouse pointer position and then scales and moves to the destination. | scales down to 0 and moves to the current mouse pointer position
Fly up | starts at the bottom edge and moves to the destination | moves to the top edge
Fly down | starts at the top edge and moves to the destination | moves to the bottom edge
All effects are now in a …
=> several window effects changes

files/usr/lib/cinnamon-settings/modules/cs_panel.py
This is actually three fixes
1. #3922 Don't set the panel_id as -1 when not supplied (since it is never supplied if accessed through navigating cinnamon settings as opposed to right clicking panel)
2. Update the panel_id property of the widgets when panels-enabled is changed
3. Don't cast int(self.panel_id) since self.panel_id is always an int
=> Fix broken panel settings. Fixes #3922

js/ui/modalDialog.js
This fixes the website link in the spices about dialog.
=> Add missing import to modalDialog.js

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Since the recent rework of the sound applet, when a new player is added to the list of compatible players, the sound applet doesn't currently refresh the menu until after a restart because ```item.remove();``` is not a valid function, and causes ```this._updateLaunchPlayer()``` to fail silently. This fixes it (and simplifies the code in the process :) ).
Edit: added another similar fix from @pixunil that fixes a bug when multiple players are open and you try to switch between them.
=> Fix sound applet app list not refreshing when player is added

files/usr/lib/cinnamon-settings/modules/cs_info.py
* Use `df -l` to find system hard disk size (Possible fix for #3801?)
* Use a × (U+00D7) instead of an x to count CPU cores.
* Reformat Operating System checking, preventing empty fields such as `debian 8.0 '' (x86-64)` from showing up.
`platform.linux_distribution()` doesn't always have all 3 fields filled out: e.g. Arch Linux gives `('arch', '', '')`
=> Minor improvements to System Info applet

data/org.cinnamon.gschema.xml.in, files/usr/lib/cinnamon-settings/modules/cs_desklets.py, files/usr/lib/cinnamon-settings/modules/cs_tiling.py, js/ui/windowManager.js
cs_desklets: change "General desklet settings" to "General settings" to avoid an extra large stack swithcer button
cs_tiling: change a couple labels and adjust the settings to match
=> tweak a few labels in cinnamon settings

files/usr/lib/cinnamon-settings/modules/cs_power.py
- fixed calls to `get_timestring`
- brightness slider has got 20 steps (like applet)
- update battery page when properties in csd changes (hacky, not in sync with the applet, more or less a bandage for now)
=> Cinnamon settings power fixes

files/usr/lib/cinnamon-looking-glass/cinnamon-looking-glass.py, files/usr/lib/cinnamon-looking-glass/page_extensions.py, files/usr/lib/cinnamon-settings/bin/ExtensionCore.py, js/ui/extension.js, js/ui/lookingGlass.js
- Remove unused imports in lookingGlass.js (leftover from legacy St lg)
- Show xlet that failed to load correctly in page_extensions
- The tooltip displays the relevant error message (albeit not always helpful)
- Double clicking errored xlet brings you to page_log
- Use xdg-open instead of gnome-open in page_extensions to open xlet website (on gnome-like sessions, xdg-open simply calls gnome-open if available, but this will still work if gnome-open is not installed)
- Fix theme installer complaining theme not compatible with current version (we don't do version check for themes, partly because themes don't have a metadata.json)
=> Looking glass work

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
- replace whitespace characters by spaces
- limit to 1000 characters (possible Cogl Error)
=> window applet: handle properly "broken" window titles

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, js/ui/popupMenu.js
{span: 0} can be passed as argument to the addActor method of a menu item
- after the actor doesn't begin a new column, but spacing is respected
- multiple actors with {span: 0} can be in the same column
=> PopupMenu actors with {span: 0}

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, js/ui/panel.js, js/ui/popupMenu.js, src/st/st-button.c, src/st/st-widget.c, src/st/st-widget.h
Replaces the frequently used
if (foo)
this.actor.add_style_pseudo_class('bar')
else
this.actor.remove_style_pseudo_class('bar')
with
this.actor.change_style_pseudo_class('bar', foo)
=> Added st_widget_change_style_pseudo_class function

files/usr/lib/cinnamon-settings/bin/XletSettings.py, js/ui/settings.js
There was a regression introduced by https://github.com/linuxmint/Cinnamon/commit/b1a6bce1dd879a05b480cc78f3496cab9d0ef3e2 which was causing multi-instance applets to not be recognized as multi-instance by certain Cinnamon components, which was causing it to not recognize the settings for the first instance of the applet.
=> Fix regression in multi-instance applets

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json, js/ui/popupMenu.js
- moved raise and quit player buttons next to the player info
- setting for player control (closes #3332)
- loop and shuffle buttons, configurable, default off
- position slider styling: no icon, labels left and right to the slider (closes #2165)
- position slider countdown option
- track infos uses `PopupMenu.PopupIconMenuItem`
=> sound applet: player changes

js/ui/windowManager.js
This affects the animation in several cases:
- Animation of windows changing workspace:
If you use Ctrl-Shift-Alt Left/Right to move a window to an adjacent workspace, or switch workspaces while dragging a window (which will move the window with you), what used to happen is that the window disappears from the "from" workspace, appears in the "to" workspace, and animates in like any other window from the "to" workspace. With this commit, the window stays at its position while the "from" and "to" windows animate.
- Stacking of "Visible in All Workspaces" windows:
In the past, when we switch workspaces, "visible in all workspaces" windows are stacked oddly during animation. They are stacked below all windows on the "from" workspace, and above all windows on the "to" workspace.  With this …
=> Improve workspace switch animation (fixes #3524)

files/usr/bin/cinnamon-file-dialog, js/Makefile.am, js/misc/fileDialog.js
This introduces a file dialog to Cinnamon. The dialog itself is Gtk, but uses the Util.spawn_async method to open the dialog and return the results. It supports 
* open, save, and open folder types
* single or multiple selection
* setting default directory, path and/or name
* custom file filters
Typical usage might be something like:
const FileDialog = imports.misc.fileDialog;
let params = {};
params.directory = "~/Pictures/";
params.name = "untitled";
params.selectMultiple = true;
let anyFilter = new FileDialog.Filter("any");
anyFilter.addPattern("*");
let imageFilter = new FileDialog.Filter("image");
imageFilter.addMimeType("image/jpeg");
imageFilter.addMimeType("image/png");
imageFilter.addMimeType("image/svg+xml");
params.filters = [anyFilter, imageFilter]; …
=> Add file chooser dialog to Cinnamon javascript

src/cinnamon-plugin.c, src/cinnamon-wm-private.h, src/cinnamon-wm.c
The kill-switch-workspace signal is used when before switch-workspace
signal is fired for the existing switch animation to be cancelled.
However, this mechanism is not ideal since the switch-workspace and
kill-switch-workspace events are separated.
Using the old model, say we switch to left workspace, and during that
animation, we press Ctrl-Alt-Right to switch back to the right
workspace. What would happen is that we will finish the animation early,
land on the left workspace, and start a new animation.
By letting the wm handle the killing work when receiving the
switch-workspace, we can do better. We can immediately halt the windows'
movement, and let them animate to where Ctrl-Alt-Right would bring them
to, from the position where they started, which would look smoother.
This new way …
=> Remove kill-switch-workspace signal

docs/reference/cinnamon-js/tutorials.xml, docs/reference/cinnamon-js/tutorials/xlet-versioning.xml, js/ui/extension.js
This commit provides the option for extensions to ship different
versions for different Cinnamon verions. To enable this, extensions have
to set
````
"multiversion": true
````
in metadata.json. The different versions should be put in different
subdirectories. For example, the version for 2.6 should be put in
`<extension-uuid>/2.6/`. The contents in `2.6/` should be exactly what you
will normally put in `<extension-uuid>/`, apart from metadata.json, which
should always be put in the parent directory, ie. `<extension-uuid>/`.
You do not need to create a subdirectory for every single Cinnamon
version out there. Cinnamon looks for the most recent subdirectory that
is not newer than the running Cinnamon version. For example, if you are
running 2.6 and there are 2.4, 2.8 directories, the 2.4 …
=> Add extension versioning support

files/usr/lib/cinnamon-settings/modules/cs_calendar.py, files/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js, src/cinnamon-util.c
Default setting is still the locale's default.
Sunday and Monday can be set in Cinnamon Settings, other days can be easily added in the python code if necessary.
#3655 
Requires linuxmint/cinnamon-desktop#28
=> Configure first day of week in calendar

configure.ac
```
src/Makefile-gvc.am:15: warning: source file 'gvc/gvc-channel-map.c' is in a subdirectory,
src/Makefile-gvc.am:15: but option 'subdir-objects' is disabled
src/Makefile.am:77:   'src/Makefile-gvc.am' included from here
src/Makefile-gvc.am:15: warning: source file 'gvc/gvc-mixer-card.c' is in a subdirectory,
src/Makefile-gvc.am:15: but option 'subdir-objects' is disabled
src/Makefile.am:77:   'src/Makefile-gvc.am' included from here
src/Makefile-gvc.am:15: warning: source file 'gvc/gvc-mixer-sink.c' is in a subdirectory,
src/Makefile-gvc.am:15: but option 'subdir-objects' is disabled
src/Makefile.am:77:   'src/Makefile-gvc.am' included from here
src/Makefile-gvc.am:15: warning: source file 'gvc/gvc-mixer-source.c' is in a subdirectory,
src/Makefile-gvc.am:15: but option 'subdir-objects' …
```
=> Stop build spam

debian/control
This eases upgrades from earlier versions of Cinnamon (such as the 2.2.x in Debian's repos), as they have clashing files with the current cinnamon-common.
=> debian/control: bump Conflicts: version to "<< ${cinnamon:Version}"

files/usr/lib/cinnamon-json-makepot/cinnamon-json-makepot.py, files/usr/lib/cinnamon-settings/bin/ExtensionCore.py, files/usr/lib/cinnamon-settings/bin/XletSettings.py, files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py, files/usr/share/cinnamon/applets/notifications@cinnamon.org/metadata.json, makepot
translation improvements
cs settings:
- translate xlet metadata (name and description)
- moved translate method to a central point
cinnamon-json-makepot:
- don't create duplicates
- parse metadata.json
makepot:
- no more need to use msguniq, removed it
- separate each language (C, JavaScript, Python) into an own xgettext call, surpresses errors
notification applet:
- use cs-notifications as icon (not a translation improvement, only a general one)
=> xlet translation improvements

js/ui/appletManager.js, js/ui/panel.js, src/st/st-box-layout.c, src/st/st-box-layout.h, src/st/st-types.h
If there is enough space, centered applets will be placed at the very center of the applet. Otherwise, the centered applets will appear as close to the center as possible. See centered menu applet:
#3849, #3100
=> Add proper panel center region. Applets are actually at the center if possible

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json, js/ui/dnd.js, js/ui/panel.js, js/ui/windowEffects.js, js/ui/windowManager.js
- Refactor code to make more sense - this applet was hack on top of
hack and was a huge mess. A lot of things were done in convoluted
ways.
- Add option to scroll window list in the other direction with mouse
scroll wheel
- Disconnect signals properly when destroyed
- Listen to windows demanding attention in addition to urgent-windows
(might solve #3812)
- Changed window-list dnd to firefox-tab style
- Fix broken applet style when changing panel orientation (in the past,
after changing panel orientation, it will simultaneously have top and
bottom styles).
- Added a brief overview of the code structure
Might fix #3574
=> Rework window-list applet

src/st/st-texture-cache.c
I've seen some cases with users experiencing a crash in Cinnamon with a stack trace indicating cogl_famebuffer_allocate was getting called with a null framebuffer. This doesn't fix whatever underlying issue was causing that, but handles the error case to ensure we at least don't crash.
=> Ensure we handle cogl functions that return NULL in data_to_cogl_texture

files/usr/lib/cinnamon-settings/modules/cs_screensaver.py
Including:
- Don't hardcode `/usr/lib/xscreensaver` (some distros use
`/usr/libexec/xscreensaver`). Instead, hardcode
`/usr/share/xscreensaver/config/`, which should be universal (and
that is also what we really want). For the record, in the
xscreensaver source itself, the path is set to
`${datadir}/xscreensaver/config/`.
- Fix non-webkit non-xscreensaver screensavers not loading
- Read the description and name of xscreensaver hacks properly, instead
of making them up ourselves
- Automatically select the xscreensaver hack in use (used to work for
webkit only)
- Fix error when xscreensaver is not installed
=> cs_screensaver.py: fix broken stuff

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
An error appears in the looking glass log when the window list applet is removed from a panel. The object is caused by the object ```this.workspaces```, which doesn't exist anywhere else in the applet. All workspace signal connections elsewhere are handled by the connection manager, so the code is apparently useless. I therefore deleted it and it works fine.
=> Fix error from window list trying to disconnect non-existant signals

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Prevent the window list items from "jumping" by hiding the source actor
at the same time as adding the placeholder, instead of first hiding,
then adding.
Make placeholder position calculation make sense.
=> window-list applet: fix dnd

files/usr/lib/cinnamon-slideshow/cinnamon-slideshow.py
Fixes #3622
The original issue is probably due to race conditions when a file is
quickly deleted after creation. Regardless, put it in a try/catch just
to be safe.
=> cinnamon-slideshow.py: fix crash when file change

files/usr/lib/cinnamon-settings/modules/cs_general.py
When the user selects a new HiDPI setting, update the value in
org.gnome.desktop.interface scaling-factor as well, since some
applications specifically listen to that. Fixes #3899
=> cs_general.py: Sync GNOME HiDPI settings

files/usr/lib/cinnamon-settings/bin/ExtensionCore.py, files/usr/lib/cinnamon-settings/modules/cs_extensions.py
Added missing method to `ExtensionSidePage` class, which blocked the update of the indicator of the active theme.
=> Little cinnamon settings themes fix

files/usr/lib/cinnamon-settings/modules/cs_startup.py
Addition to https://github.com/linuxmint/Cinnamon/pull/4091
=> Load default icon if icon theme doesn't have application icon

js/ui/appletManager.js
Whenever an applet gets added to the panel and causes the notification applet to be re-added to the panel, it automatically causes it to unhide. You can test this bug by setting the notification applet to hide when the tray is empty and then dragging other applets around it.
This checks the state of the applet before it gets re-added, and sets it to the same state after. It should work for any other applets that get hidden as well, though I haven't tested.
=> Make sure notification applet always stays hidden when it's supposed to

js/ui/osdWindow.js
Volume OSD now uses monitor.x and monitor.y of primary monitor to display properly when secondary monitor is on any side ( top, bottom, left, right) of primary monitor.
=> Fix issue #4252 

js/ui/panel.js
Prevent hidden panel from being visible with vertically stacked
monitors. Fixes #4275
=> panel.js: fix panel autohide glitch

files/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js
Remove the custom empty trash dialog and use a ModalDialog.ConfirmDialog() instead. This is the perfect use case for it. Also will allow removal of the only current uses of the .polkit style class in the default theme.
Replace the two uses of gtk stock icons with the named symbolic versions. They are deprecated and on my current system the stock icons don't even show in the menu.
=> Some improvements to the trash applet

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
What was wrong:
When the primary device does not change its icon string after an update, `battery-full` will be used.
Fixes #4329
=> Power applet: Fixed a logical bug

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Fixes #4305
Theme designers can use `.sound-button:small` (`width` and `height`) and `.sound-button:small StIcon` (`icon-size`) to resize the buttons. (I didn't want to screw with `!important`)
=> Sound applet: Use .sound-button-container:small for quit and raise button

src/st/st-entry.c
St.Entry doesn't currently honor the text-decoration or text-align properties, but St.Label and St.Button do. This has St.Entry use the same code that labels and buttons do to set the text properties. This has the added advantage of simplifying the code as there were several lines that were duplicated in both functions.
See https://github.com/linuxmint/Cinnamon/blob/master/src/st/st-private.c#L297.
=> [2.8] Fix St.Entry not honoring some css text properties

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/power@cinnamon.org/settings-schema.json
Cinnamon 2.4 had an option for displaying the estimated battery time remaining in the power applet, but the feature was removed in Cinnamon 2.6. This pull request fixes that regression, fixing #4245.
=> Restore time remaining option for power applet.

files/usr/lib/cinnamon-settings/modules/cs_startup.py
=> cs_startup: fix crash on NameError when copying a desktop file fails

files/usr/bin/cinnamon-preload
Main goal is to limit Cinnamon's network usage on systems with
a large number of users over LDAP or otherwise.
Take 2 on PR #4462, which was rejected mostly due to my changes breaking if there were extraneous files in `/home`. This version fixes that problem.
The issue with doing, as was suggested in #4462, `pwd.getpwall()` and then filtering on `/home` is that I don't actually care if a user is in `/home` for pre-loading. All I want to do is proxy for remote users by checking `/home` and if they are remote, then the value added by pre-loading the theme is definitely less than that of getting every user from the LDAP server.
I could check for ldap users directly, but that would add more requirements.
The issue this is designed to fix is a real world lab which has at most 1 local user on …
=> Only get local users from /home - Take 2

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js
The calendar applet currently updates once per second, even if a date format that does not include seconds is used. This patch changes this behaviour such that unless a format specifier that includes seconds is used, the timeout is instead set such that the update is performed at the next full minute (one second later actually, to account for possible inaccuracy).
=> [2.8] Calendar applet: Avoid unnecessary wakeups

files/usr/lib/cinnamon-json-makepot/cinnamon-json-makepot.py, js/ui/modalDialog.js
Addition to #4102, using the translations there.
Also compatible with 3rd party.
Provides following changes:
- hides the optional info box when there is no
- `contributors` can be an array (feels more natural imo), otherwise should be a string where all entries are comma-separated
- `name`, `description`, `contributors` and `comments` translated via xlet and Cinnamon domain
- labels translated via Cinnamon domain
- `cinnamon-json-makepot` updated to create pots translating `contributors` and `comments`
=> [2.8] Also translate xlet metadata in about dialogs

js/ui/main.js, js/ui/popupMenu.js
This is an attempt to fix this type of problems: https://github.com/linuxmint/Cinnamon/issues/4044, partially reverted this commit https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00
The last one was produced with the intention of filter out button-release events while a popup is opening, to avoid unintentional selection of popup items due to busy event handling.  But also this prevented capture the button-release events in other actors who need to know the status of the mouse, leaving in an inconsistent state some applets.
=> [2.8] Be more selective when filter the mouse release events.

js/ui/windowManager.js
In windowManager.js, for workspace switch animations, we use Tweener to
perform the animation. However, to call the cleanup function after the
animation finishes, we use Mainloop.timeout_add instead. This cuases a
problem if cinnamon is run with CINNAMON_SLOWDOWN_FACTOR!=1, since the
CINNAMON_SLOWDOWN_FACTOR slows down tweening animations but not Mainloop
timeouts. The result is that if we have a slowdown factor > 1, the
workspace switch animation will be cut before it finishes.
=> windowManger.js: use Tweener for timeout

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js
This fixes #4588, related to my previous pull request #4361. See the bug for the missing part.
The code checks if clock-show-seconds is set in org.cinnamon.desktop.interface, and connects to the changed::.. events for all related seconds for immediate updates on configuration changes.
=> Fix for #4588

src/Makefile.am
test-recorder #includes st.h, which pulls in lots of headers, some of which might not be in TEST_CINNAMON_RECORDER_CFLAGS, depending on how clutter and gstreamer were configured.
Fixes build failure reported at https://bugs.gentoo.org/559794 :
In file included from ./st/st-bin.h:27:0,
from st.h:4,
from cinnamon-recorder.c:19:
./st/st-types.h:26:21: fatal error: gtk/gtk.h: No such file or directory
=> build: append ST_CFLAGS when building test-recorder

files/usr/lib/cinnamon-settings/bin/XletSettings.py, files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py, js/ui/appletManager.js, js/ui/cinnamonDBus.js, js/ui/deskletManager.js
Fixes #4634 where an instance identifier was arbitrarily corresponding to the wrong type of xlet.
Additionally:
- Fixed initial instance not actually being selected on multi-instance xlet "Configuration" page (and so there's an error when clicking "Highlight" and nothing happens)
- Changes `cinnamonDBus.js` signatures for `activateCallback` and `highlightApplet`. Now passing just *uuid* and *instance_id* - both are equal when multi-instance is not allowed.
- Corrects order of instance tabs in XletSettings configuration to reflect the order instances were added in, previously this was determined by arbitrary order returned by `os.listdir` which meant it might load `15.json`, `14.json` and then `13.json`. The first tab will now correspond to the first instance you added, and so on.
=> Fix multi-instance tracking, highlighting

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
When there are many devices present, the current list isn't helpful. Example:
This minimal change adds a trailing label with the second line description so devices can more easily be identified. Example:
**Note**: the style applied on the right is `menuitem-detail`, inherited from the desktop-capture applet. Cinnamon *should* have a similar style, and when that style is selected and implemented this pull request can be updated and considered.
=> Show additional audio device description in sound applet

js/ui/messageTray.js
Notifications are broken due to invalid format supplied. Calling toLocaleTimeString with "%l:%M %p" format gives a RangeError exception with "invalid language tag" message.
=> Removed dateFormat from toLocaleTimeString() call

debian/cinnamon.lintian-overrides, debian/control, debian/rules, debian/source/lintian-overrides
By the way the `binary-or-shlib-defines-rpath` warning could probably be turned off by replacing the absolute rpaths with relative rpaths using chrpath:
```
chrpath -r '$ORIGIN/../lib/gnome-bluetooth' usr/bin/cinnamon
chrpath -r '$ORIGIN/../gnome-bluetooth' usr/lib/cinnamon/libcinnamon.so
```
=> Packaging: fix and override more Lintian warnings (new PR)

js/ui/keybindings.js
This avoids rebuilding the keybindings when nothing has changed, and consolidates the work into only one rebuild when many keys receive the signal at the same time.
See https://github.com/linuxmint/Cinnamon/issues/4691 for more information.
=> Optimize rebuilding of media-keys hotkeys (fixes #4691)

js/ui/keybindings.js
(improves #4692)
Upon reviewing the code it was noted that it could potentially be racy and that setting the variable should be done as soon as possible to avoid this.
=> Reorder setting delay_setup_started variable to avoid possible races

js/ui/checkBox.js
This fixes some issues with checkboxes introduced by #4298:
* Hard-coded style removed (this caused the CheckBox class to not work properly with a label, and should be handled in the theme anyway - especially since different themes use different sizes for the checkbox image)
* CheckBox and CheckButton classes now both inherit from a new CheckButtonBase class - this is both a more correct way of doing this, and also prevents the unnecessary adding and immediate removal of an actor in the CheckBox class
* Renamed some variables to make more sense
One issue that still needs to be resolved is the styling of checkboxes in menuitems - they don't line up properly in some themes, and are huge in some as well (e.g. Cinnamon and Mint-x themes). It can currently be styled separately with a child …
=> Fix some problems with the checkbox api

js/ui/appletManager.js
In arrow filter functions, check if the value exists (when iterating over appletObj)
Fixed the bug when the button in applet settings has no effect.
Error was:
```
(cinnamon:2680): Cjs-WARNING **: JS ERROR: Exception in method call: activateCallback: TypeError: x is undefined
get_object_for_uuid/<@/usr/share/cinnamon/js/ui/appletManager.js:439
overrideJS/Array.prototype.find@/usr/share/cinnamon/js/ui/overrides.js:149
get_object_for_uuid@/usr/share/cinnamon/js/ui/appletManager.js:439
Cinnamon.prototype._getXletObject@/usr/share/cinnamon/js/ui/cinnamonDBus.js:261
Cinnamon.prototype.activateCallback@/usr/share/cinnamon/js/ui/cinnamonDBus.js:329
_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:261
_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:331
``` …
=> appletManager fix for callback buttons in applet settings

files/usr/share/cinnamon/cinnamon-screensaver-lock-dialog/cinnamon-screensaver-lock-dialog.py
Entering ```$( any command )``` into the lock screen dialog box will currently pass that command through to ```os.system()```.
I replaced os.system() calls with subprocess.call() and did some PEP8 formatting
Fixes #4652
=> Fixed code injection bug in screensaver lock dialog (Fixes #4652)

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
Caused issues when adding, moving or removing items
Fixes a regression of 402c5be6 and closes #4745
=> Panel launchers applet: fix TypeError

files/usr/share/cinnamon/cinnamon-looking-glass/lookingglass_proxy.py
```dbus.exceptions.DBusException``` is referenced without being imported first, and would throw a ```NameError``` if the exception condition were ever evaluated.
And some PEP8 formatting.
=> Fix potential NameError

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
Currently, if any file in one of the background picture directories contains name like \`gedit\`.png or $(gedit).png, the command will be executed by ```commands.getoutput()``` on [Line 391](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py#L391) if that directory is selected in the "Backgrounds" settings tool.
Demo:  Name a file in ~/Pictures to \`gedit\`.png or $(gedit).png, open up the Background settings app, select the "Pictures" folder in the sidebar, and gedit will be executed.
It turns out that the "safe" way of performing the same task was already being done in the ```PixCache.get_pix()``` method, so I pulled it out into a separate function and used it in both places.  
Also did some PEP8 formatting.
Fixes #4658
=> Fix shell command injection when changing background picture (#4658)

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
```commands``` is deprecated, vulnerable to shell injection, and was dropped from Python 3
=> Replaced all uses of the commands module with subprocess

js/ui/windowAttentionHandler.js
update windowAttentionHandler.js to suppress stealing of Autofocus for Instant messenger Psi+ (http://psi-plus.com/) and RetroShare (http://retroshare.org/)
=> attentionhandler suppress autofocus

src/st/st-box-layout.c
This fixes an off-by-one error in the allocation of STBoxLayout, fixing #4778
=> Fix allocation error when STBoxLayout is align_end

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/ui/tooltips.js
In rare cases, two enter events occurred without a leave event in between, leaving an orphaned _showTimer behind. Maybe fixing #4750
=> Fix a timer issue in TooltipBase

js/ui/settings.js
The user_data was not passed to the specified callback when binding a property via bindProperty().
=> Fix: user_data is not passed to callback

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Players also can set Shuffle or Loop at the very beginning, and the sound applet does not know it.
=> Sound applet: Fetch the status of Loop and Shuffle at the beginning

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml
The label, tween, and textview types were missing from the xlet settings documentation.
=> Settings Tutorial: Add some missing settings widgets types

js/ui/cinnamonDBus.js
Methods are currently unreachable via D-Bus due to mismatched method names, and parameters. This error was my own.
Signatures exposed via D-Bus don't match the methods:
`qdbus org.Cinnamon /org/Cinnamon | grep Screenshot`
To repro, send a dbus message for one of the capture modes, e.g. area capture (x, y, width, height, flash, filename):
`dbus-send --print-reply --type=method_call --dest=org.Cinnamon /org/Cinnamon org.Cinnamon.ScreenshotArea boolean:true int32:50 int32:50 int32:200 int32:200 boolean:true string:"/home/radams/Pictures/blah.png"`
All of the screenshot-related methods could use an update, but this is at least corrects the problem and provides another route to the capture functionality.
=> Fix D-Bus methods for screenshots

js/misc/util.js
Instead of trying to change the error message, just don't handle the exception at all. Since err.message is read-only, this code fails. This should (hopefully) not change any functionality but removes warnings such as:
```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/misc/util.js 130]: "message" is read-only
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/misc/util.js 153]: "message" is read-only
```
=> util.js: do not modify error message

js/ui/settings.js
duplicated enum in settings module triggers warning errors in log file
=> remove duplicated enum radiogroup

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This fixes the volume slider offset in the sound applet, fixing #4830.
This also fixes the padding for device entries in the same popup menu.
=> [3.0] Fix volume slider (second attempt)

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
Located in Settings > Windows > Behavior > Moving And Resizing Windows.
=> GUI option for gsettings > org.cinnamon.muffin > edge-resistance-window

files/usr/share/cinnamon/desklets/photoframe@cinnamon.org/desklet.js
Avoid using unescaped file names by using spawn, store the path in order
to use it. fixes #5184
=> Fix middle click action in the photo frame

files/usr/share/cinnamon/desklets/photoframe@cinnamon.org/desklet.js
Forwarding the Debian bug 761310 (http://bugs.debian.org/761310)
originally reported by Martín Ferrari:
Hi, much to my surprise, the photoframe desklet will not show pictures
in subdirectories, which is a useful feature if you want to have all
your pictures shown.
=> photoframe doesn't recurse into subdirectories

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
I use a dock application so thought the favorite apps section in menu applet is a redundancy for those who use dock applications. So I added an option to menu applet to be able to show/hide favorite apps section.
=> [3.0] add option to show/hide favbox in menu applet

js/ui/windowManager.js
This prevents desktop effects on dialogs and menus from being used if desktop-effects is turned off. It's like already like this in the effects settings dialog.
=> Fix desktop effects on dialogs and menus

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
Errors in cs_backgrounds brought to my attention on the commit comment page [here](https://github.com/linuxmint/Cinnamon/commit/a4342d34f4cc84f3ce2eaea4a95e26c57915f508#commitcomment-17393968). I'm not sure why .close() is causing the issue, but this commit removes it.
@brownsr In case you'd like to test this change (though it's pretty much exactly the change you said you made)
=> cs_backgrounds fix image close

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Not addressed by this pr:
- Some icon themes do not include the "audio-card" icon name (e.g. Numix)
=> Fix handling of device icon where gicon is None (mostly fixes #5248)

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
prevents duplicate search results for apps with the same
desktop entry name when searching with a more specific
term
=> menu applet: use app id instead of app name for searches

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
There seems to be no reason to select the rows themselves and doing so just causes them to get the themes selected_bg_color which isn't really the look we're going for here.
=> cs_sound: Set selection mode to none on the SoundBox() object

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
While seeking does work, after the first time you seek the amount
seeked is incorrect. It appears to seek the amount between the
beginning of the seek bar and where you released the click instead.
Artist metadata was sent as an unhandled type so check for type
and handle accordingly.
=> sound applet: smplayer: fix artist metadata display and disable seek

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
A follow up to https://github.com/linuxmint/Cinnamon/commit/4268aa9847adb0f407952d36d04c6656b982911e "media-optical-cd" doesn't exist as part of the gnome/adwaita icon set so not all themes support it. Use "media-optical" instead.
=> sound-applet: Fix an icon name

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This fixes the uncleared drag placeholder in the favorites box,
if an application was dragged over, but not dropped on the favorites box
This is for #5322
=> [Menu applet] Fix not cleared drag placeholder in favorites box

data/icons/Makefile.am, data/icons/hicolor_devices_scalable_bluetooth.svg
The sound settings needs this. Since the default gnome icon theme doesn't contain one just add it to the hicolor icon theme.
Fixes https://github.com/linuxmint/Cinnamon/issues/5350
=> Add a generic "bluetooth" icon

docs/search-providers-examples/trackerprovider@cinnamon.org/search_provider.js
remove the url garbage text that can take up a lot of space when searching in the menu
=> Clean up output filenames on the tracker search provider

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
I tiled a window by keyboard shortcut while the window preview was open, and the preview became stretched. That is fixed with this pull request.
The problem is seen in this image:
=> Resize a thumbnail when the window resizes

js/ui/applet.js
This small change introduces the applet name into the right click applet menu item that removes the applet, so instead of "Remove this applet" the user will see "Remove 'Systray'" for example. I hope this will make a user less likely to remove an applet in error.
fixes feature request #5214
=> More informative applet menu item

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
At the moment a long applet description will push the subsequent icons off the visible screen
which is likely to confuse some.  Scaling up font or text scaling exacerbates this
Some simple column wrapping avoids the issue
=> wrap a long applet description in applet settings

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Corrected "output" to "input" in ## Input page section of buildLayout method. This was preventing the ability to switch between input devices.
=> Corrected "output" to "input"

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
Due to recent changes in the settings widgets and some upstream changes from Gtk/Gdk, the ColorChooser widgets stopped working in the background settings. This fixes them so that they work again.
Please note that this is only temporary as the relevant objects and functions involved in this commit are deprecated, and could break at any time. A proper fix would be to update the background handling to use ```Gdk.RGBA``` instead of ```Gdk.Color```.
=> Fix background settings color chooser not working

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
This doesn't seem to provide anything useful to the user and according to https://github.com/linuxmint/Cinnamon/issues/5601 some users actually mistake this for an email address.
In the current layout it's so tiny as to be barely legible on a high res screen in any case.
=> ExtensionCore.py: Don't show the uuid to the user

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Instead show the current workspace and set it insensitive. This seems to make more sense and keeps it consistent with the window titlebar menu
closes https://github.com/linuxmint/Cinnamon/issues/4288
=> window-list: Don't hide the current workspace in context menu

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
With this commit Cinnamon menu applet shows in the right click context menu a new option: "Run with nVidia GPU", useful in systems using Bumblebee to manage the GPUs. 
I made this change because I found annoying the fact that I had to open a terminal, than type _optirun ..._ and keep the terminal window in the background while working. This solution is much cleaner: right click, run with nVidia, and you're done.
It isn't too much annoying, in fact it only shows up when _optirun_ (part of Bumblebee) is installed.
I could have made a more general mechanism, such as nemo actions, but I don't think it is necessary, because, apart from adding to the favourites, adding to the panel, adding to the desktop, uninstalling and running with dedicated GPU, there aren't many other possible actions for …
=> Menu applet: Show 'Run with nVidia GPU' in context menu

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
I changed the maximum delay for the GSettingsSwitch from 120 minutes to 1440 minutes (24 hours).
This is to respond to this feature request:
linuxmint/cinnamon-control-center#151
It would be better if there are were two fields, one for minutes and another one for hours, but I encountered some complications while trying to implement them.
=> change the maximum delay for backgrounds slideshow

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
1. Make each BalanceBar insensitive when the channel map is changed so it's clearer that the user can't actually change balance, fade, sub etc.
2. Fix some device icon spacing issues, specifically for 4K
=> Cinnamon-Settings: Fix some annoying bugs in the sound module

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js
This keeps things central in the panel and avoids problems with the panel width being able to accommodate icon+text label unless there are many, many notifications [should never happen in normal use, would probably need 1000 unread notifications].
Feels like a 'least bad' solution to be honest.  The icon+text style does not really suit a vertical panel, whether the text is to the side or below.
=> vertical panels: put the notification count under the notification icon

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
This prevents a crash introduced with the mimtypes change if
mimetypes.guess_type() is called when filename = None.
=> cs_backgrounds.py: Don't check mimetype if filename is None

files/usr/share/cinnamon/applets/removable-drives@cinnamon.org/applet.js
Use Gio to open the default file manager at 'computer:///'.
Note that nemo is not hardcoded anywhere else on the panel, so please consider to not hardcode it for this menu item too.
=> removable-drives applet: don't hardcode Nemo

files/usr/share/cinnamon/applets/show-desktop@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/show-desktop@cinnamon.org/settings-schema.json
This feature allows you to take a peek at the desktop, if you hover with your mouse over the show-desktop applet. (If you want to take a quick look at your files or desklets (for example weather) stored on the desktop and you are to lazy to press the show-desktop applet for that ;)
You are in control of the following settings:
(1) It's up to you using this feature. Turned off by default
(2) Blur effect for the transparent windows, when peeking at desktop
(3) Time you have to wait, till windows are getting transparent, after you hovered over the applet
(4) You decide how transparent you want the windows to be
This commit tidies this previous messy pull request: https://github.com/linuxmint/Cinnamon/pull/5703
=> [show-desktop applet] new feature added: Peek at desktop

docs/reference/cinnamon-tutorials/importer.xml, docs/reference/cinnamon-tutorials/using-documentation.xml, docs/reference/cinnamon-tutorials/write-applet.xml, docs/reference/cinnamon-tutorials/xlet-versioning.xml
These are the same changes as in this pull request:
https://github.com/linuxmint/linuxmint.github.io/pull/9
except made to the *.xml files.  Thanks!
=> Fix grammar mistakes in source files

js/ui/boxpointer.js
Thanks @lestcape
Solves an issue where the applet context menu gets deformed when moving a panel between orientations.
=> correct applet context menu on panel orientation move

docs/reference/cinnamon-tutorials/write-applet.xml
The argv parameter of the spawn function in utils.js needs to be an array of strings.
=> write-applet.xml: fix incorrect example code

files/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/separator@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/spacer@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, js/ui/applet.js
Fix the layout of applets on vertical panels. Currently in a vertical panel the container widget holding our applet actors does not properly fit to the full width of a vertical panel the way it does the height of a horizontal panel. This is really obvious in themes such as Mint-Y that color a filled box on applets when hovered. Applets are depending on this small box to clip the items it doesn't want the applet to show in vertical panels such as text labels. Because of that, fixing the layout of the applets also required adapting some of the individual applets to work properly when moving them between different panel orientations.
Since I went through a lot of the applets individually I also cleaned up some of the code formatting issues in those applets.
Some applets could use further, …
=> Vertical panel applet layout improvements

js/ui/panel.js
This prevents an error when you remove a panel that has auto hide
enabled.
Cjs-WARNING **: JS ERROR: TypeError: this.monitor is null
Panel.prototype._hidePanel@/usr/share/cinnamon/js/ui/panel.js:3535
=> panel.js: don't try to hide the panel if it's destroyed

js/ui/panel.js
If the user removes the last remaining panel, pop up a dialog asking if they
want to launch panel settings. This can help prevent situations where the
desktop isn't usable for users that don't know how to get to panel settings
other than through the panel/menu applet.
=> panel.js: add dialog to launch settings when the last panel is removed

js/ui/appletManager.js
The function signature of removeAppletFromPanels has been changed and the
second parameter is not the element index. Since forEach invokes the
callback with the element index as the second parameter, we can't use that
anymore.
=> appletManager.js: fix removeAppletFromPanels

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
The following pictures are saying pretty much everything about this commit:
I saw this here https://cinnamon-spices.linuxmint.com/applets/view/261 and liked it.
Maybe you can use/create different icons.
This is especially helpful if you take a close look at the first picture.
In German the words "Restore" and "Unmaximize" are translated with the same word "Wiederherstellen".
Without the icons you can't tell the difference.
Before I saw this applet with icons, I wasn't even aware, that there was a difference xD
=> [window-list applet] using icons on context menu

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
When opening the menu you can see, that the "All Applications" button is highlighted:
Imagine the following two scenarios:
1. You would expect to get the next category by pressing the  down key on your keyboard, because the first category is already highligted. Wrong.
Instead you get the first application in the "All Applications" category.
2. You press the right key on your keyboard and expect to get the first application in the "All Applications" category. Wrong again. You get the first category "All Applications", which is already highlighted.
I think the suggested way is more intuitive, due to the fact, that the "All Applications" button is highlighted, when you open the menu.
The only thing I wasn't sure about was what the `this._scrollToButton(item_actor._delegate);` function is …
=> [menu-applet] a more intuitive way of keyboard-navigation in menu

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
Currently when we have a theme of the same name in both the /usr and /home
directory both themes are shown in the theme chooser buttons. When choosing either
of the themes in the settings the one in /home will be given precedence. When
both exist, only show the one from the users home directory since that is the
one that will be applied regardless of which the user chooses.
Fixes https://github.com/linuxmint/Cinnamon/issues/5778
=> cs_themes: Don't show duplicate themes

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
The applet was missing an `instanceof TransientButton` query, which caused the following bug:
https://github.com/linuxmint/Cinnamon/issues/5338
=> [menu-applet] fixed filesystem path search keynavigation

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/separator@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, js/ui/applet.js, js/ui/appletManager.js, js/ui/panel.js
Currently an applet has to override getDisplayLayout() to allow itself in a
vertical panel which doesn't really make sense. An applet should be setting the
type of allowed layout it can have. Add an _allowedLayout variable to the base
applet class that is set by default to AllowLayout.HORIZONTAL. Then add two
functions that allow getting and setting that variable. Now to allow an
applet in non-horizontal panels an applet should call setAllowedLayout with the
appropriate value.
=> applets: Change how applets set the type of panel they are allowed in

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_effects.py
There are at least 2 benefits to doing so:
1. The effects and tween chooser button code had a great deal of duplication with the BaseChooserButton class in SettingsWidgets.py, but they couldn't be subclasses of BaseChooserButton because SettingsWidgets.py was already importing EffectsWidgets.py. With BaseChooserWidget in the same file, this is no longer an issue, which allows simplification of code and makes it easier to maintain
2. SettingsWidgets.py is getting very large. This change makes it easier to maintain the settings widgets.
=> Move all settings chooser button code to it's own file

js/ui/tooltips.js
This fixes the tooltip position on the first show of a tooltip.
Previously, the extents fetched from the actor were wrong,
because the actor had never been allocated before.
=> Fix tooltip position

src/st/st-scroll-view.c
For whatever reason, this comment hangs g-ir-scanner indefinitely
with version 1.50 of gobject-introspection in Arch Linux, at least
on my machine. Moving the comment onto its own line fixes this issue.
=> st-scroll-view.c: move comment up and remove indentation

files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
This fixes linuxmint/cinnamon-screensaver#103 by making the strings clearer.
=> Re-order and re-word idle-delay and re-word lock-enabled.

src/cinnamon-global.c
This function has no return, so I've removed the return annotation and added
a symbol description instead.
Fixes:
Warning: Cinnamon: cinnamon_global_get_memory_info: invalid return annotation
=> cinnamon-global.c: fix a gi warning

js/ui/messageTray.js
Now that we allow vertical panels we need to take them into account when
placing notifications to avoid them overlapping the panel.
=> messageTray: Fix the placement of notifications

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
When the favortiesBox was turned off and you restarted Cinnamon, you couldn't get the favoritesBox to show again, i.e. the checkbox favBoxShow didn't worked, because the favoritesBox was never created at the first place.
=> [menu-applet] create favBox, even if it's not shown at Cinnamon restart

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
When pressing the ENTER/RETURN-key on the RecentClearButton nothing happened.
Now it clears the recent list, when you hit ENTER.
=> [menu-applet] clear recent list applet with ENTER-key

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
Straightforward change to add a vertical style class when in a vertical panel.
No code is needed to remove it on a move to a horizontal panel,  as buttons are rebuilt from scratch
when panels are moved between orientations.
Linked to a change to improve appearance of this applet in vertical panels in Mint-X themes
=> add vertical style class to workspace switcher in a vertical panel

files/usr/share/cinnamon/applets/inhibit@cinnamon.org/applet.js
On initial show the first menu item is overly large. This seem to be caused by
the way we show and hide _statusIcon object. Switching from using show/hide to
hiding the icon by using it's opacity fixes the issue.
Fixes https://github.com/linuxmint/Cinnamon/issues/5810
=> inhibit-applet: Fix an oversized menu item

data/theme/cinnamon.css
fixes #5748.
There was a tiny bit of spacing there in the css.  Removed it.
=> correct unreactive top/bottom strip in vertical panels

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
At the moment the graph is suppressed in vertical panels because a long wide
workspace resulting from multiple monitors results in an unworkable graph
when scaled to fit the panel width.
Change this to test on the workspace size ratio, as this will permit single
monitor setups to have the workspace graph
=> workspace switcher - change whether graph is shown or not in a vertical panel

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/misc/docInfo.js, js/ui/placesManager.js
The app description doesn't handle some characters (e.g. german umlaute ö ü ä) properly.
Fixes https://github.com/linuxmint/Cinnamon/issues/5595
Edit: fixes https://github.com/linuxmint/Cinnamon/issues/3620 and fixes https://github.com/linuxmint/Cinnamon/issues/3250
=> [menu-applet] decodeUriComponent in app description

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, js/ui/popupMenu.js
The new PopupSwitchIconMenuItem is the same as PopupSwitchMenuItem, but allows icons to the left of the label.
(comparable with PopupMenuItem and PopupIconMenuItem)
It is used in the contextMenu of the sound-applet, to show icons for mute switches.
This commit is a response to the feature-request https://github.com/linuxmint/Cinnamon/issues/4940,
but it only implements the requested icons. It is missing the requested alignment of the text of 'Applications' and 'Output devices'.
The new icons in the contextMenu are changing, when the input/output values are changed.
=> added PopupSwitchIconMenuItem and used it in sound-applet

data/theme/cinnamon.css
* Added buttons styling same as other in the theme
* Change color to fit the theme
Before (left) vs after (right):
=> [sound-applet] Match style to the controls overlay

files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
The switches showalbum and showtrack had no effect, when the switch playerControl was turned off.
So I added dependencies for these two switches. Therefore the Menu settings and the Panel settings had to be switched.
=> [sound-applet] added dependencies in the settings-schema

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
**EDIT:**
_What's new?_
- New keys for menu navigation were added (see below)
- Some bugs were fixed (see below)
- The code, which handles the keynavigation was rewritten. I have splited it into two codeblocks.
1. One codeblock handles the navigation of the menu, without having to worry, which button you have to press to get this action done. It means, you check where you are (`appsBox, catBox or favBox`) and what should happen if you go right/left/up/down (`whichWay`) from your current position.
2. In the other codeblock you decide, what you want to do, if a certain key is pressed, for example if you press TAB, you want to go right. At this point you don't have to worry, how this will be handled, because that's the problem of the above mentioned codeblock. You can add restrictions in …
=> [menu-applet] rewritten keynavigation codeblock

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py, js/ui/hotCorner.js
This pull request adds the ability to set a hover delay to activate hot corners. Its main purpose is to 
avoid accidental hot corners activation. I also added tooltips to the hot corners icons that reflect their current action, as suggested by @anandrkris.
The new Hot Corners settings window would look like this:
- File js/ui/hotCorner.js 
- This PR also fixes some minor white-space *inconsistencies* on this file (some missing spaces and some extra tabs). But, as I use a code formatter plugin, it also expanded some objects. Let me know if I should revert back those objects expansions.
- File files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py
- Here I had to add a timer to the **on_widget_changed** function to avoid repeated triggering from the new **SpinButton** elements. …
=> [Hot Corners] Added hover delay functionality.

js/ui/popupMenu.js
We need this so theming from the default theme is used in themes that don't yet
support the new style class for menus.
=> popupMenu: Mark the new 'menu' style class as important

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
https://github.com/linuxmint/Cinnamon/commit/2633e4bbedb3447a3c344644ff194249cb47e424
added a vertical style class to the workspace switcher. We need to add the
style class to the button whenever it is vertical not only when applet scale
mode is enabled.
=> workspace-switcher: Fix the vertical style class

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This fixes a problem, when the menu orientation is not St.Side.TOP.
the menu box layout was is reverse order.
=> Fix menu item order in window list

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Previously the outside couple of pixels were unreactive.  This was done to avoid recursion errors
but these seem no longer to be there, so this resets to the desired behaviour
=> Window-list applet - ensure that the edge of the screen reacts to mouse clicks

js/ui/panel.js
We want to do this so that when using a box shadow on the panel to draw a
border, the border is drawn the full width of the panel. Currently it works on
the top panel but the side panels cover the one drawn by the bottom panel.
=> panel.js: Change the order which panels are drawn

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
I have renamed the "Date" page to "Customize" and added the new lock screen settings there. I think the away message stuff should probably be in customize too, but the whole reason I added the new stuff on the "Customize" page is to avoid having one page be too long and require scrolling by default. Let me know what you all think of the wording, layout, etc.... 
By the way I recommend we also merge #5342 as it is still compatible with the rewritten screensaver.
preview:
=> cs_screensaver.py: expose new cinnamon screensaver settings + bugfix

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
Allow the new menu animations to be enabled on the main Cinnamon menu. In the
past there were complaints about the menu being too slow open and the new
animation may add to that perception. Set it off by default but allow users
to enable it.
=> menu-applet: Add a setting for the new menu animations

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js
Use of `%e` causes uneven spacing in the date display on the tool-tip and the applet itself on single-digit days, e.g.—
```
Sunday November  6, 2016
^        ^^  ^
```
Use of `%-e` ensures uniform spacing across the entire string, e.g.—
```
Sunday November 6, 2016
^        ^  ^
```
=> avoid varying space between month and day

js/ui/lookingGlass.js
Prevents an error when trying to call toString() on undefined or null when
a key exists in the result but has no value.
=> lookingGlass.js: inspect: better handle undefined and null values

js/ui/applet.js
The logic in the common applet code has been changed so that the scaling
is not overridden by the local function.
The applet will end up doing the central function and then its local one,
if it has one. The central function has the common scaling code, this
way it doesn't get skipped inadvertently.
This also corrects related errors associated with turning scale mode on and off.
One more associated change to the window-list applet in a vertical panel will be needed
but as there are changes queued up for that I think it's best done subsequently
fixes #5700
=> [bugfix] ensure applets that override on_panel_height_changed  scale OK

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
By default, "entry" and "iconchooser" editable fields are too small on xlet's setting windows. In addition, they don't expand their width when the window is resized. This makes those elements *uncomfortable to work with*.
This commit adds to the "entry" and "iconchooser" elements a new boolean option (optional) called "expand-width". When set to **true**, the editable fields for "entry" and "iconchooser" elements will occupy all available space in the row and at the same time will expand if the window is resized.
This is how "entry" and "iconchooser" elements looks like on current Cinnamon stable (3.0.7). Editable fields occupy all the available space and they expand on window resize.
This is how those elements looks like on Cinnamon nightly with the new proposed option ("expand-width") …
=> [Xlet settings] "entry" and "iconchooser" elements modifications.

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, js/ui/cinnamonDBus.js, js/ui/extensionSystem.js
By default, "button" elements aren't functional when used inside the settings windows for extensions. There isn't a mechanism to store the callback declared in the "callback" keys of said elements.
This commit adds to the extensions system a mechanism similar to what applets and desklets managers uses. It stores an object containing one or more functions (defined by the extension creator) returned by the `enable()` function defined in extension.js. These functions can then be called from "button" elements defined in the extension's settings file (settings-schema.json).
Corrected some minor indentation/white space inconsistencies and removed a couple of undeclared/unused arguments.
This commit closes linuxmint/Cinnamon#5842
Given the following "button" elements...
```json
"button_id_001": …
```
=> [Xlet settings] Added support for "button" to extensions settings windows.

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Recent files, which are no longer available, will be hidden in the recent files category after next call of refreshRecent.
If the file is available again, because it was on a CD or USB, it will appear again.
If a file is no longer available, but the recent files are not refreshed yet, the description of the file shows a warning "**This file is no longer available**".
=> [menu-applet] hide recent files, which are no longer available 

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
We need to remove the keybind when the applet removed so it doesn't keep the menu alive, and make the keybinding name unique per-instance otherwise we have conflicts between instances' overlay-key setting.
This still needs additional work as multiple menu applets will share the default keybinding and it will activate one instance per keypress in sequence.
=> Fix up keybind handling in menu applet

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
The latest changes to the menu applet added the possibility to open the context menu for menu items with the keyboard, but the context wasn't navigable. This pull request adds the ability to navigate the context menus with the keyboard.
- The **Arrow Up/Down** and **PageUp/PageDown** keys will navigate through the menu items of an open context menu.
- If the **Arrow Left/Right** or **Tab** keys are pressed, it will continue navigation outside the applications box.
- If the **Escape** key is pressed while a context menu is open, first it will close the opened context menu and if it's pressed again it will close the applet menu.
=> [Menu applet] Added keyboard navigation for context menus.

js/ui/tooltips.js
Currently, tooltips created with the **new Tooltips.Tooltip()** constructor are aligned to the top-left corner of the mouse pointer. This leads to having tooltips overlapped by the mouse pointer. And the bigger the mouse pointer, more of the tooltip is covered by it.
This commit aligns the tooltip to the bottom-right corner of the mouse pointer (approximately), reducing the possibility of the mouse pointer to overlap the tooltip.
- This change only affects tooltips created with the **new Tooltips.Tooltip()** constructor.
- As I didn't want to use a fixed size, I used the global preference _cursor-size_.
=> [Tooltips] Fixed positioning of tooltips.

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, js/ui/dbusMenu.js, js/ui/indicatorManager.js, js/ui/main.js, js/ui/popupMenu.js
- Resize the status indicator and the appindicator icons in the same way.
- Dynamically enable and disable the appindicators using the value of the global.settings.
- Dynamically enable and disable the appindicator when an applet with a same role will do the opposite action. This also will unregistered the appindicator Dbus iface.
- Added shortcut support.
- Encapsulate the blacklist functionality inside the manager.
- Reorganize the position of starting, to allow the access to the systray in the initialization.
- Can be decided the behavior for the indicators menu (right click or left click): https://github.com/linuxmint/Cinnamon/pull/5790/commits/4077efe1a02ac647ae6fe550add910bcb44672b8#diff-05db65ea5625e393ffab82cc7a763e9cR961 **Please use gsettings or create a applet setting to be …
=> Improving slightly the appindicators.

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
- fix "undefined item_actor" warning, when navigating right/left is supposed to do nothing
- when pressing DELELTE-key, check if the button in the favsBox is a favoriteButton or a systemButton
- before opening contextMenu, check if it's an applicationButton or recentButton (and not a placesButton)
=> [menu-applet] fix warnings caused by keynavigation

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
[Xlet settings] Fix for icon choosers stuck dialogs
Currently, after choosing an icon file from a "filechooser" element on a settings window for any xlet, the file chooser dialog will not close itself after clicking the **Accept** button.
This commit fixes that behavior and other minor Gtk warnings.
Fixes linuxmint/Cinnamon#5774
=> [Xlet settings] Fix for icon choosers stuck dialogs

files/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py
With the redesign of the xlets settings system, there is a new UI element called "page". These elements have a key called "title" that needs to be translated.
This commit adds the ability to the `cinnamon-json-makepot` command to extract from the settings-schema.json file those keys when said command is used to create a .pot file.
=> [cinnamon-json-makepot] Added support for "title" key

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
The PIL version in LMDE2 doesn't seem to support width and height properties
for Image objects, so use Image.size instead.
Fixes #5986
=> cs_backgrounds.py: fix thumb generation on LMDE2

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
There may be a better/more correct fix for this. I'm not sure if this was introduced with the popupMenu.js changes or if it has existed for a while unnoticed.
If we destroy the menu while it is open then a callback set by pushModal removes
the grab when it recieves the actor's destroy signal. Shortly after, we attempt to
remove it again in popupMenu.js via the menu state change signal and fail. Closing
the menu before destroying the actor avoids this issue.
Fixes #5968
=> panel-launchers: close the menu before destroying when removing launcher

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
The feature to show the timer/minutes in the sound-applet, was removed a long long time ago.
This removes remained code of this feature, which also includes the remained option "countdown/song lenght" in the settings of the applet.
=> [sound-applet] removed ancient code for timeLabel

files/usr/share/cinnamon/cinnamon-settings/modules/cs_effects.py
When disabling window effects the menu effects setting is hidden. Make sure to
disable the menu effects when that happens.
Fixes https://github.com/linuxmint/Cinnamon/issues/5936
=> cs_effects: Disable menu animations when turning off window effects

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
- make sure to check activeContainer is categoriesBox, before checking if button is RecentCategoryButton
- when favBox is hidden and no recent files are existing, searchBar looses focus pressing TAB on recentCategoryButton
=> [menu-applet] fix keynav issues with TAB

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
Workspace applet buttons didn't get proper height (or width in vertical mode), like any other button, if the auto-scale font setting was not enabled.
Here is a screenshot of the problem:
=> [workspace-switcher] Fix buttons' size

js/ui/indicatorManager.js
Ensure a default icon size of 16px if the icon-size is not set in the indicator icon theme class.
This is an attempt to fix: https://github.com/linuxmint/Cinnamon/issues/5932
=> Indicators: Ensure a default icon size of 16px

js/ui/applet.js
In Cinnamon version 3.0.7, when new menu items are added to the context menu of an applet/desklet, a separator automatically appears, dividing the default menu items (**About**, **Configure...** and **Remove...**) from the just added menu items. In Cinnamon version 3.2.x, the same behavior was observed until [this commit](https://git.io/v6rI7) removed it.
This commit brings back that behavior to the context menu for applets
=> [applet.js] Re added ability to display a separator on applets context menus.

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
Remove the option to show the percentage value besides slider, which was introduced in https://github.com/linuxmint/Cinnamon/pull/5854
If implementing something like that, it should be made consistent and globaly. Means the other applets, which use slider, e.g. brightness slider, should have this option too. It's not very clever to add this option individually for each applet. If it's done, it should be one switch, which turns on/off this option for every applet, and not having many switches for each applet on it's own.
Also this option has no significant additional benefit. A siginificant additional may (or may not?!) be, if the sound-applet gets the feature to turn the volume to more than 100%. So considering this maybe in the future and removing it for now, because of the first said …
=> [sound-applet] remove show percentage label for slider option

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
For the four default options in the contextMenu icons are used, which already exist in the Cinnamon packages.
For the last option "Run with NVIDIA GPU" a new symbolic icon is needed. (Coming soon... cpu-symbolic.svg by JosephMcc)
Also changed (the old notation) nVidia to NVIDIA.
=> [menu-applet] symbolic icons for contextMenu of appsButtons

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
If checking for existence of a file, the URI has not to be decoded.
Else E.g. files, which contain % in their name, are not shown in the recent category.
The rest is fixing some indentation.
=> [menu-applet] fix file-exists-query and indentation

js/ui/popupMenu.js
Please see the iteration happen inside updatePanelsVisibility. This fix: https://github.com/linuxmint/Cinnamon/issues/6023
=> Do not make unnecessary iteration on popup menu close function

files/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py
Fixes
```
$ python2 /usr/bin/cinnamon-menu-editor
/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py:20: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gtk, GObject, Gio, GdkPixbuf, Gdk, CMenu, GLib
/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py:20: PyGIWarning: CMenu was imported without specifying a version first. Use gi.require_version('CMenu', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gtk, GObject, Gio, GdkPixbuf, Gdk, CMenu, GLib
```
=> Fix gi import version warning

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
It seems Gio.File.new_for_path() will always return a value, even when passing
an empty string as a path. To avoid having a directory name shown in the button,
first check if the string is empty and bypass setting the label if it is.
=> SoundFileChooser: Fix showing incorrect names

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
Change the icon from a stock icon to a symbolic version. We should change this
for two reasons. One, the use of stock icons has been deprecated for quite some
time. For another, we want to support the use of dark themes by using symbolic
icons whenever possible.
=> SoundFileChooser: Change play icon

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/misc/docInfo.js
There used to be a reason to limit the number of files before d5ff93e034d46aedf2c7f29252f19db9608bd194 removed costly computational steps. Now it works fine without this limit.
fixes #5928
=> Remove the 20 recent files limit

js/ui/appletManager.js
The element at index 2 is the applets order on the panel, the uuid is
at index 3.
=> appletManager.js: fix max instance check when pasting applet config

files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
This button brings up http://www.foragoodstrftime.com/ where the time
and date format is explained. Similar to the Cinnamon Calendar Applet
Configuration.
This should fix Cinnamon Issue #4535 (a Feature Request)
=> screensaver settings: Add button with info on custom format

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
A couple of buttons were added to the settings outside of list boxes. Move them
into the list boxes so they don't completely break the layout we created.
=> cinnamon-settings: Fix a couple of ugly buttons

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.ui, files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_effects.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_privacy.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
We are running into cases where either translations or long label lengths in
applet settings are putting a horizontal scrollbar on the window. This can cause
the "action" widget, like a switch, to be hidden outside of the viewable area.
To better deal with these situations, line wrap the labels instead. This ensures
that whole settings widget is viewable when opening the window at the default
size.
=> cinnamon-settings: Do a better job of handling long labels

js/ui/magnifier.js
This is only a little improvement which makes the magnifier pull the mouse position more often. 
As this is assistive technology, CPU impact shouldn't matter much to those who really need the magnification.
=> Smoother screen magnification

src/cinnamon-window-tracker.c
from upstream https://github.com/GNOME/gnome-shell/commit/ac22172a6ec37a158ca4cecf8c18f8fb29c1aa97
=> window-tracker: fix memory leak

files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py
If the custom icon file no longer exists, use the default panel launchers
icon instead. Without this an uncaught Glib.Error is generated which causes
the panel launchers edit action to do nothing.
Fixes #6156
=> cinnamon-desktop-editor: use the default icon when file is nonexistent

js/ui/hotCorner.js
This fixes a "Invalid or null source id used when attempting to run Mainloop.source_remove()" when leaving a hotcorner.
The timeout is already destroyed by returning false in the callback, but we still knew about the timeout id and tried to remove the non-existing timeout.
=> Fix hotcorner hover delay timeout removal

js/ui/expoThumbnail.js
Using the 'position-changed' signal repositions thumbnail while the expo is open. It is unnecessary as the positions are updated elsewhere (not sure where, but testing it seems fine) and is also sometimes signaled too much (very obvious with gnome-system-monitor on 'Resources' tab, but happens occasionally elsewhere).
fixes #5442
=> Expo: Don't reposition thumbnails on position-changed.

src/main.c
from upstream https://github.com/GNOME/gnome-shell/commit/7f1a258ff9fc768a7fc13e5c37e1fd6d7ab5c33b
=> cinnamon_dbus_acquire_name: Don't leak error

src/main.c
from upstream https://github.com/GNOME/gnome-shell/commit/3f0fbae7e213b2fbe7267b9d25ac7fcfaa8afcff
=> cinnamon_dbus_acquire_name: don't leak the result

src/cinnamon-screenshot.c
Should fix https://github.com/linuxmint/Cinnamon/issues/6229
Based on https://git.gnome.org/browse/gnome-shell/patch/src/shell-screenshot.c?id=cdc4f85e478f2bf59dcffe1a1449af54b9086381
=> Fix cursor black background when taking screenshot

js/ui/panel.js
For vertical panels we need to make calculations based on the panels x not the
y.
Closes: https://github.com/linuxmint/Cinnamon/issues/6111
=> vertical-panels: Make proper calculations for panel intellihide

js/misc/util.js
This is a CLI utility method that invokes a callback after the process has exited cleanly, or an error callback if it does not. Neither callback will be called if the functions are not passed to the method. Having callbacks allows more precise handling of the asynchronous behavior involved with calling processes from JS.
This uses GLib.child_watch_add to return the callbacks after the process exits. https://people.gnome.org/~gcampagna/docs/GLib-2.0/GLib.child_watch_add.html
=> JS API misc/util.js: Add spawnCommandLineAsync

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
Currently, the power applet is impossible to move (or remove without opening cinnamon-settings applets) when there are no batteries and nothing on which the brightness can be changed. This pr causes the power applet to show a battery icon in panel edit mode if there is nothing else showing already.
=> Power applet: always show something in panel edit mode

js/ui/windowManager.js
We are missing the workspaceOSD and switch effect in some cases like assigning
a hotkey to direct navigation. Move showing the workspaceOSD and playing the
sound effect to _switchWorkspace since it always gets called.
=> windowManager: Move handling of workspace switch effects to one place

js/ui/keyboard.js
from upstream https://github.com/GNOME/gnome-shell/commit/9d933356e171a1dc49b61b5864826531c0f24d97
Am not convinced I have exercised this code path in testing, so would be grateful if someone who understands 'extended keys' could check, or give me some idea on how to do it.
=> keyboard: destroy the key's boxpointer

src/st/st-box-layout.c
from upstream https://github.com/GNOME/gnome-shell/commit/aa6f352cb06d3ae8940af323f048c8c7886fa0cd
=> st-box-layout: Don't report a paint volume when we have no allocation

src/st/st-theme-node.c
At the moment we have an outer loop on i, and then a separately declared internal loop on i
This changes the name of the variable in the internal loop to avoid confusion.
adapted from upstream. https://github.com/GNOME/gnome-shell/commit/a025b151efa892ede252af851a6d484fc8f0d8dd#diff-ea7efd941b083a785ba5e4b928a26d59
=> st-theme-node.c: rename a confusing variable

src/st/st-theme-node.c
from upstream https://github.com/GNOME/gnome-shell/commit/1d235395765226a981fd31f16adae505ad8642de#diff-ea7efd941b083a785ba5e4b928a26d59
Can be tested on the New Minty theme, which has   height: inherit   which triggers it
=> st-theme-node: Improve error reporting for length errors

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
Greetings, I was planning to create an app that would allow us to manage and edit the systemd units and services on Cinnamon, but I just stumble across an app called systemd-manager (you can check all of the information here: [systemd-manager](https://github.com/mmstick/systemd-manager). Now I would like to explain some points which you might disagree with at first, but I would like to let you know anyway:
1. I do understand that you do not like CSD apps (don't hate them either but you have your reasons to dislike them, and I understand), but leaving aside that first fact it has the basic things along with the options of enable/disable, start/stop them, check the journal, check possible dependencies on other services and even edit the services available at will; something that will help …
=> added support to manage the systemd services available on the system (requires systemd-manager installed)

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
When _shellIndicators is empty, there is no forEach member function
and an exception is generated. Using a for loop instead, no exception
is generated when the object is empty.
fixes:
this._shellIndicators.forEach is not a function
Error during on_applet_removed_from_panel() call on applet: systray@cinnamon.org
=> systray-applet: don't crash in on_applet_removed_from_panel

src/st/st-theme.c
Compiler is complaining about shadow variables because the same
variable names are defined in a function and in an if statement in the function
=> st-theme.c: rename confusing variable

files/usr/share/cinnamon/cinnamon-settings/modules/cs_accessibility.py
We want to go back to the theme that was being used before the High Contrast
was enabled. Not reset to the default theme.
Fixes https://github.com/linuxmint/Cinnamon/issues/2533
=> cs_accessibility: Restore previous theme when disabling High Contrast

data/org.cinnamon.gschema.xml.in
Starting systray applet before the menu applet should hopefully be enough to address
https://github.com/linuxmint/Cinnamon/issues/5525
=> Start systray applet first

data/icons/Makefile.am, data/icons/hicolor_actions_scalable_list-edit-symbolic.svg, docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py, js/ui/settings.js
* Allows adding/removing/editing/reordering entries in settings
* Allows a variable number of columns, each with it's own properties and data type
* Currently supports string, integer, float, bool, sound, icon, keybinding, and file variable types (more can be added easily - let me know if you have any ideas or requests)
=> xlet settings: add list widget

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py, js/ui/hotCorner.js
This is a left over legacy from gnome shell and simply doesn't work well the
various panel layouts we allow. It just appears broken/unfinished.
Remove the ability to use them and add a new gsettings key to manage our
settings for them. This should ensure nothing gets broken when Cinnamon is
upgraded.
=> hotcorners: remove the icon option

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py
Allows use of the numpad enter key to execute the command line.
=> cinnamon-looking-glass.py: handle numpad enter in entry

src/st/st-entry.c
was comparing signed and unsigned int before, and generating a compiler warning
=> st-entry: change variable type to avoid compiler warning

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml
On pull request #5891 was added a new option for *entry* and *iconfilechooser* elements called *expand-width*. The reference in the Cinnamon documentation source was added to the wrong element, *filechooser* instead of *iconfilechooser*. This pull request fixes that.
=> [Xlet settings] Fix reference to new option added to wrong element

files/usr/share/cinnamon/applets/user@cinnamon.org/metadata.json, js/ui/modalDialog.js
If `last-edited` exists in metadata, show the timestamp in UTC and don't show `version` of metadata.
If `last-edited` not in metadata, show `version` if exists.
If xlet is a spice, add a "More info" button, which opens the spices website in browser.
[user@cinnamon.org] remove last-edited entry form applets metadata
=>  	[xlets-about-dialog] show timestamp if exists else show version & show "more info" button

files/usr/share/cinnamon/cinnamon-looking-glass/page_inspect.py, js/ui/environment.js, js/ui/lookingGlass.js
This fixes inspection of certain objects whose member's names are not compatible with dot notation such as `Main.AppletManager.appletObj`, and sets null values to "[null]" so they can easily be distinguished from empty objects in the inspector view.
A third fix here makes sure toString() doesn't fail for certain objects when inspecting. I'm not sure about the actual details of this problem, but I could reproduce the issue and I found this fix over in gnome-shell. It's simply adding a try..catch and returning the original toString value for that object if searching for the actor generates an exception.
=> A few looking-glass fixes

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
The values of the spinbuttons for hide and show delay for panels were jumping around for fast clickers.
Fixes #6374
=> Fix panel timeout spinbuttons jumping around

files/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py
Currently the `cinnamon-json-makepot` command, when run with the `--js` argument, it scans only the JavaScript files that are in the root folder of an xlet. In an xlet with "multiversion" enabled, all JavaScript files inside sub-directories will be ignored and the resultant .pot file will be incomplete.
This commit adds the ability to scan all JavaScript files inside an xlet folder by saving a list with all JavaScript files found into a temporary file. Then that file is used to pass the *--files-from* argument to `xgettext`.
- **settings-schema.json** files found inside sub-folders are already *taken care of*. The *problem* is only with JS files inside sub-folders.
- ~~I'm *worried about* the *universality* of the `find` command and the **/tmp** folder. I don't know if that command and …
=> cinnamon-json-makepot: Added support to scan for JS files inside sub-dirs.

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
This PR allows theming of the systray.  Not that theming the systray per se is hugely useful, as it is really the tray icons within the systray that would be more useful to theme [so that, for example, they could be made to behave like applet-box on hover].  However I have bounced off that for now.  The most immediate use is to allow the hard-coded spacing in the systray applet to be moved to CSS, and I think that removing hard-coding from applets is worthwhile.  The important attribute is used so that no changes have to be made to themes other than the default cinnamon theme. I've left systray hover CSS in the Photocopy spices theme for ease of testing - as JosephM commented, highlighting the whole of the systray is a bit of an odd thing to have, but it does at least demonstrate this new …
=> systray: add css class to permit theming

files/usr/bin/cinnamon-subprocess-wrapper, js/ui/cinnamonDBus.js
This ensures that cinnamon-process-wrapper never fails due to an uncaught
exception when launching a process. With this, we can always call back into
cinnamonDbus.js and cleanup the subprocess_wrapper callback. The callback
is only invoked if the command runs successfully and exits with a status
code of 0. NFCI
I made sure that I tested this revision of the code. Sorry about the previous PR.
=> spawn_async: clean up the callbacks after we're done

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
This enables users to chose the default file manager, e.g. in case other applications "steal" it from nemo because of alphabetical order of .desktop files.
Addresses #3695, fixes #5598 indirectly
=> [cinnamon-settings, "Preferred Applications"] Add a chooser for File Manager

js/ui/applet.js, js/ui/appletManager.js, js/ui/modalDialog.js
Currently, the applet name of the **Remove** context menu items of third party applets  aren't translated. This is because the translated string is currently fetched from Cinnamon's domain and not the third party applet's domain. Default Cinnamon applets doesn't have this problem.
This commit uses a mechanism similar to the used by the **SpicesAboutDialog** prototype to try to fetch the correct translated string.
Also, some trailing spaces were removed and some missing semicolons were added.
- I moved the call to **Gettext.bindtextdomain** from the **modalDialog.js** file to the **appletManager.js** file so the applet's domain it's binded (don't know if I express this correctly) before the first call to the **finalizeContextMenu** function. This way, the translated strings are available …
=> Fix for non translated applet names on Remove context menu items.

files/usr/bin/cinnamon-killer-daemon, files/usr/share/applications/cinnamon-killer-daemon.desktop, files/usr/share/cinnamon-session/sessions/cinnamon.session, files/usr/share/cinnamon-session/sessions/cinnamon2d.session, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, js/misc/interfaces.js, js/ui/keybindings.js, js/ui/soundManager.js
- cinnamon-settings-daemon no longer exists as an executable
- dbus names are now unique for each plugin
https://github.com/linuxmint/cinnamon-settings-daemon/pull/162
=> Adapt Cinnamon to multi-process CSD

js/ui/panel.js
This problem was only exposed after I changed the way _updatePanelVisibility was being called in PR #6438. This warning won't occur on master but this is still an issue.
Fixes:
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/panel.js 3150]: assignment to undeclared variable x
=> panel.js: fix missing variable declaration

js/ui/messageTray.js
While we don't allow most notifications to show when running fullscreen
applications, we should allow notifications marked as critical. Since panels
are hidden there is no obvious indicator of things like the fact that your
battery is about to die.
Closes https://github.com/linuxmint/Cinnamon/issues/1646
=> messageTray: Show critical notifications in fullscreen

js/ui/modalDialog.js
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/modalDialog.js 594]: anonymous function does not always return a value
=> modalDialog: avoid a js warning

js/ui/applet.js, js/ui/appletManager.js, js/ui/desklet.js, js/ui/deskletManager.js
This exposes the request for deletion of config files to the xlet that is being removed, in order to enable them to clean up after themselves, e.g. if an xlet uses its own settings. there's no need to do this for plain extensions, because their disable()-function is only called when completely unloading it.
=> [Xlets] Expose config deletion request to xlet

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
These allow us to recolor the applets icon depending on the current state of
the battery. Use a 'warning' style class when the percentage drops below 20 and
an 'error' class when it drops below 5.
=> power-applet: Add support for warning and error style classes

src/st/st-theme.c
avoids compiler warnings
done upstream
=> st-theme: add missing enums and default case

files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
I have upped the image.thumbnail resolution from 96x96 to 255x255. This will save an appropriately .face image for the new larger face thumbnail on the lockscreen for cinnamon-screensaver.
This push resolves bug linuxmint/cinnamon-screensaver#187 and closed duplicate #6173.
=> cs_user.py: Save appropriately sized .face for cinnamon-screensaver

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
This reworks the internals of the panel settings page to simplify the code and fix some buggy behavior with panel highlighting and editing. Instead of a static 2 pages for all panels, it now uses 1 for each panel. In addition, the panel widgets were rewritten as backended subclasses of the standard settings widgets in SettingsWidgets.py in order to make sure they are in line with the other widgets throughout cinnamon-settings.
=> Panel settings rework

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py
Add a flipped argument to the cinnamon settings range widget. Gtk.Scale is a
little limited in what it allows. There is no way built in to map a range from
a big->small value without drawing the fill value in reverse. Add a bit of a
hack to allow working around this limitation.
=> cinnamon-settings: Fix some sliders being drawn backwards

data/theme/cinnamon.css, js/ui/applet.js
Was affecting text-only applets unintentionally.  Use spacing rather than margin to avoid this.  This has the happy side effect of being able to remove some code that is not needed anymore
=> St: support margin: corrections to PR 6271

js/ui/panel.js
This fixes most instances of hidden panel flashing, and also has a minor fix and some cleanups. See commit messages for detailed descriptions. Please test and comment if you find any bugs.
This branch exposes an issue in existing code which is fixed in #6460
Fixed issues that I don't know if are reported:
- Panel shadows show up on adjacent monitors
- Hidden panels flash on any settings or theme change
- Panel sometimes disappears when moving a panel with autohide enabled
- Hidden vertical panels partially show when activating a horizontal panel menu
- Recently added shadow clipping code in _showPanel doesn't handle all shadow types correctly
Existing issues:
- <s>Partial vertical panels don't have a shadow on top or bottom. These should be unclipped when the panel above or below hides. …
=> Panel.js: _moveResizePanel refactor and cleanups

js/ui/layout.js
If we don't do this then hidden panels still affect the input region on
the adjacent monitor but never react to events, so the area becomes an
input "black hole".
This also moves the nested if's conditionals into the parent if. There's no reason to create the rect if we aren't going to use it, especially now that we're doing more calculations in here in some cases.
=> layout.js: don't include clipped off areas in input region

src/st/st-scroll-bar.c
done using g_return_val_if_reached as upstream
=> st-scroll-bar: add default to case statement to avoid compiler warning

src/st/st-scroll-view.c
avoids compiler warnings
missing enums are put in the same places as upstream
no regressions I can see ...
=> st-scroll-view: add missing enums and default case statements

src/st/st-widget.c
also add a cast to similarly avoid compiler warnings
all changes as upstream.
=> st-widget: add missing enums to avoid compiler warnings

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This avoids warning messages as margin:auto is not supported
And it also means third party theme developers will not copy non-functional CSS
The warning messages for the programmatic insertion of margin:auto in the menu applet
were particularly cryptic
I have removed earlier PRs in the same area, on reflection I realised simple removal of the margin:auto statements that triggered warning messages was all that was needed.  I can roll this out into other themes.
=> St: Margin: remove margin:auto from menu applet and default theme

src/st/st-icon.c, src/st/st-label.c, src/st/st-private.c
Adapted from https://github.com/GNOME/gnome-shell/commit/d6fe008b2c334f8f7b48b28b87982c06035243e0
Closes https://github.com/linuxmint/Cinnamon/issues/6360
Closes https://github.com/linuxmint/Cinnamon/issues/6209
=> st: Fix a couple icon/text-shadow bugs

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py
Just a quick hack to fix this issue. Keep track of custom notebook pages
and use existing methods to destroy them on quit. This fixes the window
freezing on quit if you have added any custom file watchers.
=> melange: don't freeze on quit with custom log watchers

js/ui/desklet.js
st_bin_set_child() only takes a single argument. In previous versions of cjs
the extra argument must have just been silently ignored. Now it complains so
quit trying to pass it. Leaving it in the function params just to avoid
breaking anything.
=> desklet.js: Ignore an extra argument to setContent()

js/ui/tooltips.js
Encountered this when calling a PanelItemTooltip instance from a child class in ITM.
```sh
(cinnamon:10020): Cjs-WARNING **: JS ERROR: TypeError: this.mousePosition is undefined
PanelItemTooltip.prototype.show@/usr/share/cinnamon/js/ui/tooltips.js:318
open@/home/jason/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:653
hoverOpen@/home/jason/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:635
_onMenuEnter/<@/home/jason/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:610
setTimeout/<@/home/jason/.local/share/cinnamon/applets/IcingTaskManager@json/__init__.js:12
```
=> js/ui/tooltips.js: Check if this.mousePosition is defined

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
=> workspace-switcher: correct undefined property warning (mozjs38)

js/ui/appletManager.js, js/ui/dnd.js, js/ui/extension.js, js/ui/panel.js
The dnd and panel errors can be reproduced when dragging an applet that also has an undefined error in its code that gets called during dragging. After the change in dnd, the applet's stack trace showed instead.
```
(cinnamon:5100): Cjs-WARNING **: JS ERROR: Error: Expected type enum for Argument 'type' but got type 'undefined'
_Draggable<._updateDragHover@/usr/share/cinnamon/js/ui/dnd.js:412:21
wrapper@resource:///org/cinnamon/cjs/modules/lang.js:178:22
```
```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/appletManager.js 317]: reference to undefined property x._applet
```
```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/panel.js 2206]: reference to undefined property this._dragShowId
```
---
```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/extension.js 382]: …
```
=> Fix undefined errors with mozjs38 in dnd, panel, extension, and appletManager

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
With js38 these throw a warning because add_actor() takes only one argument,
the actor to add to the container add_actor() is called on. I don't believe
these ever had any effect, so I've removed them.
Quiets 5 of these on MPRIS player open with js38:
Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
=> sound-applet: remove extraneous arguments on add_actor calls

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
We are checking if the AppMenuButton is temporary, but the temporary property
is actually stored as 'alert'. This corrects that typo and in addition changes
all existing calls to _addWindow() to include the alert argument for consistency.
This ensures that window.alert is always initialized to either true or false.
fixes js38 warning at line 1233:
reference to undefined property window.temp
=> window-list-applet: fix undefined reference warning

files/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py
With the introduction of list widgets to the xlets settings system (#6303), there is a new *title* key that needs to be extracted to be translated.
This commit adds the ability to the `cinnamon-json-makepot` command to extract from the settings-schema.json file those keys when said command is used to create a .pot file.
=> [cinnamon-json-makepot] Added support to extract "title" and "units" keys on list elements

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py
Lack of parenthesis is preventing xlet-settings from starting.
```sh
Traceback (most recent call last):
File "xlet-settings.py", line 9, in <module>
from JsonSettingsWidgets import *
File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 2, in <module>
from SettingsWidgets import *
File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 15, in <module>
from ChooserButtonWidgets import *
File "/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py", line 167
print message
^
SyntaxError: Missing parentheses in call to 'print'
```
=> ChooserButtonWidgets.py: Fix Python 3 error

files/usr/share/cinnamon/desklets/photoframe@cinnamon.org/desklet.js, files/usr/share/cinnamon/desklets/photoframe@cinnamon.org/settings-schema.json
The xlet settings widget used to choose a folder for the images was changed to
use a URI instead of path. The code in the applet was never updated to reflect
that so choosing a new directory was broken.
Clean up a few of the signal values while as well.
=> photoframe-desklet: Fix a few issues

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Existing behavior for installation progress bar text :
- Before installation : _no changes_ (_empty_ when initialized, stays at `100%` when continued from previous installation instead of reset to _empty_ or to `0%`)
Behavior after this change : 
- Before installation : initializes (or reset) to `0%` along with all other relevant components (`progressbar.set_fraction` and `progresslabel`)
=> Progress bar text initializes and resets

js/ui/panel.js
Checked out on single monitor, and when adding and removing a second monitor
=> panel: avoid cjs giving a warning that dummyPanels[i][j] is undefined

js/ui/deskletManager.js
consistent with appletManager now. Was showing log errors
=> deskletManager: Correct call to file.delete

js/ui/settings.js
(cinnamon:5111): Cjs-WARNING **: JS ERROR: TypeError: oldSettings[key]
is undefined
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:558:17
How to reproduce:
Remove the layout section in an applet's settings-schema.json, reload the applet, add it back, and reload again. Can be seen when upgrading some applets that add a layout section to their schema.
=> ui/settings: Handle undefined old settings values

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
meta_window_minimize() only takes one argument and it is the meta window object
=> window-list applet: fix argument warning

js/ui/main.js
The COMMAND_2 enum member was removed from muffin in 2012.
https://github.com/linuxmint/muffin/commit/0fd28e63a9bf02c68d735756e826db7bba5b7c49#diff-15c3f0c014bba808df3ba2b17c812e9aL191
fixes warning:
main.js 1229: reference to undefined property Meta.KeyBindingAction.COMMAND_2
=> main.js: remove obsolete Meta enum member reference

files/usr/share/cinnamon/applets/slideshow@cinnamon.org/applet.js
Translations are available, but do not show because of the imported gettext lines.
Remove the those lines and the applet shows the right locale
=> slideshow-applet: fix translation

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
If applet is only visible in panel-edit-mode and you move it, it vanishes.
This PR makes sure to always show the applet in panel-edit-mode.
Also show applet icon, when you add this applet with panel-edit-mode enabled.
=> keyboard-applet: applet icon vanishes when moved in edit mode

files/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py
This changes two things.
- It adds a keyword option that can be passed to xgettext. For instance, if you don't assign gettext to an underscore variable ("_"), setting this option with the alternative variable will allow the JS strings to be included.
- The script breaks on my applet's files because of regex found in the Lodash library. This is fixed by changing the language to "JavaScript". If there's side effects of this I'm not aware of, I can make this an option too, but it seems like a safe choice.
=> cinnamon-json-makepot: Add keyword option, change language used by xgettext to JavaScript

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This fixes the cause of multiple menus opening for these two applets, but does not fix the cause of the stuck menu. See #6550
=> Set items unreactive during panel edit mode for window list and panel launchers

files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js
meta_window_unminimize() only takes one argument and it is the meta window object
edited to add:
Cjs-Message: JS WARNING: [/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js 117]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
=> windows-quick-list: fix argument warning

js/ui/cinnamonDBus.js, js/ui/environment.js, js/ui/popupMenu.js
This corrects the following errors.
```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/popupMenu.js 2025]:
reference to undefined property actor._delegate
```
```
(cinnamon:5111): Cjs-WARNING **: JS ERROR: Error: Expected type object
for Argument 'actor' but got type 'undefined'
_patchContainerClass/containerClass.prototype.add@/usr/share/cinnamon/js/ui/environment.js:37:9
```
```
(cinnamon:5111): Cjs-WARNING **: JS ERROR: Exception in method call:
highlightXlet: TypeError: obj is null
CinnamonDBus.prototype.highlightXlet@/usr/share/cinnamon/js/ui/cinnamonDBus.js:310:1
_handleMethodCall@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:261:22
_wrapJSObject/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:331:16
```
I encountered these during development of my own applet, …
=> Correct errors/warnings in popupMenu, environment, and cinnamonDBus

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py, files/usr/share/cinnamon/cinnamon-looking-glass/lookingglass_proxy.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_extensions.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_inspect.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_log.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_memory.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_results.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_windows.py, files/usr/share/cinnamon/cinnamon-looking-glass/pageutils.py
This converts melange from a docked window into a normal toplevel window, fixes broken scrolling on the results page, implements autoscrolling on the log page, and adds a menu to inspect page that allows you to insert the selected property's path into the command line entry.
The last commit is a wide range of cleanups that I wanted to do after working on the code. This can be removed if anyone objects.
=> [3.6] [RFC] Melange normal window, scrolling fixes, and cleanup

js/ui/modalDialog.js
* The version number shows up only, when the timestamp is not shown/does not exist. So move the version number to where the timestamp is, i.e. under the uuid. -> Remove `about-version` style_class.
* Move the icon up and inline with the box that holds the title, uuid and timestamp/version.
* Remove the "Comments" label.
* Add tab before website link like it's done for contributors.
left column is new, and right column is old, i.e. how it looks right now:
=> xlets-about-dialog: improvements for about dialog

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
"panel height/width" needs to be translated differently in some languages (depending on the sentence/context it's used in).
The same strings "height/width" right now are used in two different contexts and therefore makes it impossible to translate it properly, e.g. into Czech.
This PR splits those translatable strings.
Fixes https://github.com/linuxmint/Cinnamon/issues/6615
=> [3.6] panel settings: split height/width translation strings

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
=> cinnamon-settings.py: allow search box placeholder text to be translated

src/cinnamon-slicer.c, src/st/st-bin.c, src/st/st-box-layout.c, src/st/st-icon.c, src/st/st-private.c, src/st/st-private.h, src/st/st-table.c
https://github.com/GNOME/gnome-shell/commit/24ad59ea3728cf55ad127085e486d73345e33a35#diff-578ccc5ce70c4a11d7f30e3f38002f0b
plus a very minor simplification in st-box-layout
=> [3.6] st: Remove _st_allocate_fill

src/st/st-bin.c
https://github.com/GNOME/gnome-shell/commit/7e343f11f28a736d88619b85c9b9c6ea52a7e142#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6] st-bin: Make sure not to allocate hidden children

src/st/st-widget.c
https://github.com/GNOME/gnome-shell/commit/79bfea5970a055a3990f7e52a3669a59594851a1#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6]st-widget: Unset hover when setting track_hover to FALSE

src/st/st-bin.c
https://github.com/GNOME/gnome-shell/commit/50f8ae6fc756d1a0fb33912e6b9d08a8fa71c197#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6] st-bin: Don't allocate a hidden actor

src/st/st-drawing-area.c
https://github.com/GNOME/gnome-shell/commit/587c93eadf01fafc6a6a6cb53aac94d9802de44d#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6] StDrawingArea: fix texture drawing

src/st/st-widget.c
https://github.com/GNOME/gnome-shell/commit/5c0ee02251ebd21f72ee8d32b93d707547a06803#diff-b948bb195b709c61ce7275142a2fbdfd
=> [3.6] st-widget: remove stylable property

js/ui/panel.js
I think we should change the code convention for how we iterate arrays in Javascript to only allow iterating with normal for loops. While ```for ... in``` is easy to type and very much a python way to express iteration, it is the wrong way to iterate arrays in Javascript. 
- Benchmark tests show ```for ... in``` loops to be [demonstrably slower](https://jsperf.com/for-vs-foreach/75) than normal for loops.
- [From MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)
> for...in should not be used to iterate over an Array where the index order is important.
- Blog: [The Problems with for...in and JavaScript Arrays](http://adripofjavascript.com/blog/drips/the-problem-with-for-in-and-javascript-arrays.html)
- [A good Stack Overflow response regarding the …
=> [3.6] ui/panel: Convert for ... in loops iterating arrays to normal for loops, splice arrays instead of using delete operator, remove white space

js/misc/signalManager.js, js/ui/popupMenu.js
This migrates signals and ensures that all signals across popupMenu classes are properly disconnected during their life cycle.
This will probably need more testing, so I'm giving it the WIP flag, but it should be complete. I am avoiding the PopupMenuAbstractItem class as it is interwoven into the indicator support, which I don't fully understand.
=> popupMenu: Migrate signals to SignalManager management, add connect_after method to SignalManager.prototype

src/cinnamon-app.c, src/st/st-adjustment.c, src/st/st-box-layout-child.h, src/st/st-scroll-view.c, src/st/st-widget.c
results are implementation specific and can give odd results if bit operators are used.  
gboolean maps to int, not unsigned, so replace gboolean bit flags with guint.
based on https://github.com/GNOME/gnome-shell/commit/69f17da5ca191c57acb6dfc5bbedc6f14f768e9b#diff-9ad11fdf581414b0f2501e50921d1052
with one additional instance found
=> avoid signed ints for bit flags

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
Status icons were coming up a bit small.
Indicator icons were coming up double size.
The default of 16px indicator icons in non-scaled panels was awfully blurry.
Icon spacing appeared to be scaled up in hidpi for no good reason.
=> systray: Improve icon scaling in hidpi

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/config.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
This makes cinnamon-settings independent from the installation location,
making it easier for developers, because you don't have to install
Cinnamon for testing during development. You can just run it from where
it is.
=> [3.6] Make cinnamon-settings unaware of installation location

js/ui/panel.js
I'm pretty sure this is dead code, I can't see anything missing if I remove it [at the moment there is a problem elsewhere in setClipRegion that is suppressing corners showing,but I tested with a workaround to that].  If anyone knows that it is still needed, please say.  This code is present upstream, but I rather suspect that it is there to do something Gnome-ish that is not needed in Cinnamon - the comment about synchronising a [non-existent in Cinnamon] locate button with the corner seems to imply as much.
=> panel: Remove dead code

utils/cin-debug
The script uses sudo to gain privs to attach the debugger, so we must
run interactively to display the password prompt. It will work in cases
where sudo auth is already cached, but that's probably not likely in
most cases.
=> cin-debug: don't suggest backgrounding

js/ui/panel.js
Fixes on screen keyboard
Cjs-WARNING **: JS ERROR: TypeError: this.panels[i] is undefined
PanelManager.prototype.lowerActorBelowPanels@/usr/share/cinnamon/js/ui/panel.js:432:13
LayoutManager.prototype.showKeyboard@/usr/share/cinnamon/js/ui/layout.js:269:9
Keyboard.prototype.show@/usr/share/cinnamon/js/ui/keyboard.js:470:9
Keyboard.prototype._setupKeyboard@/usr/share/cinnamon/js/ui/keyboard.js:282:13
Keyboard.prototype._settingsChanged@/usr/share/cinnamon/js/ui/keyboard.js:243:13
=> panel.js: don't error on nonexistent panel

files/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js
Cjs-Message: JS WARNING:
[/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js 37]: Too many
arguments to method Gio.File.monitor_directory: expected 2, got 3
Cjs-Message: JS WARNING:
[/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js 80]: Too many
arguments to method Gio.FileEnumerator.next_file: expected 1, got 2
=> trash applet: Fix arguments warnings

src/st/st-entry.c
adapted from https://github.com/GNOME/gnome-shell/commit/387f5143f02f720b4d084aa4fca65e2ff31176b0#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-entry.c: make it recognise ctrl-C, X, V in the same way as ctrl-c,x,v

src/st/st-entry.c
https://github.com/GNOME/gnome-shell/commit/954d262d674f597a35a4b4342a6d4fc41dc8ff43#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-entry.c: Fix spacing on right icon in entry

js/ui/settings.js
With some naive benchmarks, I got following results with my configuration: (average of 20 hot-starts each)
type     | uuid                                |    before |    after |
---------|-------------------------------------|--------|--------|
applet   | `calendar@cinnamon.org`             |   65.8 |   14.8 |
applet   | `menu@cinnamon.org`                 |  328.1 |  254.2 |
applet   | `network@cinnamon.org`              |   67.9 |   48.1 |
applet   | `notifications@cinnamon.org`        |   58.3 |   10.1 |
applet   | `panel-launchers@cinnamon.org`      |  112.3 |   43.6 |
applet   | `recent@cinnamon.org`               |   31.3 |   24.1 |
applet   | `removable-drives@cinnamon.org`     |    9.5 |    7.1 |
applet   | `show-hide-applets@mohammad-sn`     |   55.0 |    9.7 |
applet   | …
=> Performance: Do not write valid settings files again to the disk

js/ui/layout.js, js/ui/panel.js
Wide range of optimizations and documentation fixes for layout.js. See individual commits for more details.
Optimizations that may improve performance:
- from 2 to 1 connections to screen signal windows-restacked
- remove unused var and if conditional from windows-restacked handler
- on screen windows-restacked - from 2 to 1 calls to _queueUpdateRegions if popup window is visible
- on screen monitors-changed - from 2 to 1 calls to hotCornerManager.updatePosition
- on layoutmanager monitors-changed -  from 2 to 1 calls to both _queueUpdateRegions and _updateVisibility
- when popupmenu is visible, one less comparison in Chrome actors loop during _updateRegions
Non-performance optimizations:
- call _queueUpdateRegions directly in _updateVisibility since we call it directly after, avoids an …
=> layout.js optimizations and docs

docs/reference/cinnamon-tutorials/importer.xml, files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js, js/ui/extension.js, js/ui/main.js
This replaces the usage of ```imports.addSubImporter``` with ```imports.searchPath```. In main, both the global and local Cinnamon data directories are added to the search path. This allows us to import those xlet directories directly, e.g. ```imports.applets```. This is then aliased to each xlet's UUID property on the importObject object in extension.js, instead of the old import object the CJS patch provided.
The good part is we can remove this extra functionality from CJS and move a little closer towards upstream GJS. ~~The bad part is, and why this is a work in progress, is it breaks the ```imports.applet``` import object~~. The majority of xlets on Spices import files through appletManager, which should behave like normal.
Edit: I will be updating all Spices that break because of …
=> extension: Use imports.searchPath instead of imports.addSubImporter

js/ui/panel.js, src/st/st-box-layout-child.c, src/st/st-box-layout-child.h, src/st/st-box-layout.c, src/st/st-box-layout.h
Left as 5 commits so the reviewer can see what is going on.  There are four commits in the upstream change https://bugzilla.gnome.org/show_bug.cgi?id=703810.  Note that in the first one align_end was left untouched, essentially a non-functional stub to ensure that code that used it remained functional (to a degree).  align_end was something we introduced in a commit in 2015.  Once the full commits in the upstream change were in place, this made the standard clutter align functions available.  This in turn permitted the workarounds that align_end was there to fix, to be removed, and so align_end could go.
In the round it's a considerable simplification of code.
=> Move to using a clutter layout manager in StBoxLayout

debian/control
As reported by some users and with a fast search in cinnamon-common
files gettext and xdg-utils are required but missed.
=> Added missed gettext and xdg-utils to cinnamon-common deps

js/ui/applet.js, js/ui/appletManager.js, js/ui/panel.js
Previously, Cinnamon would send a message to cinnamon-settings saying there was an error.
With this change, the user is now prompted with the following options:
1. Leave the applet on the panel anyway (some applets are still suitable for vertical panels under certain circumstances - even if they aren't marked as such). In this case an override is added to the applet definition to avoid the user being prompted in the future.
2. Remove the applet.
3. Try to move the applet to a different panel. If a suitable panel cannot be found, the applet is removed instead.
The first commit also rewrites the way applet positions are saved after a dnd operation so as to avoid the override being overwritten by a dnd operation. (note: the override is stored as another entry in the applet definition, and is …
=> Improve the way cinnamon handles applets that are added to an unsupported panel

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
to overlay the vector box. The St.BoxLayout that we use for the
CategoriesApplicationBox no longer supports container-relative
positioning and as a result the vector box was being positioned
at the end of the box.
=> menu-applet: use a generic clutter actor container

js/ui/extension.js
This fixes a crash at Cinnamon startup, if there's an xlet definition for a non-installed xlet uuid.
Trying to load non-installed xlets now silently fails also at startup, not only while Cinnamon is already running.
=> extension.js: Fix startup with non-installed xlet uuid

src/cinnamon-app.c
https://github.com/GNOME/gnome-shell/commit/36c69124f749c48f583e8ff2413d27e10d1229e0
Spotted while browsing gnome commits. The original cause appears pretty obscure.
=> cinnamon-app.c: Don't crash when trying to dispose

files/usr/bin/cinnamon-settings-users
Policy settings about cinnamon-settings-users is already present, use
policykit instead deprecated gksu for cinnamon-settings-users works
correctly and is already used in fedora package.
=> Use pkexec instead deprecated gksu for cinnamon-settings-users

js/ui/extension.js
Corrects the following error when reloading an xlet:
```
(cinnamon:29502): Cjs-WARNING **: JS ERROR: Exception in method call: ReloadExtension: ImportError: No JS module 'hasOwnProperty' found in search path
forgetExtension@/usr/share/cinnamon/js/ui/extension.js:514:1
unloadExtension@/usr/share/cinnamon/js/ui/extension.js:508:9
reloadExtension@/usr/share/cinnamon/js/ui/extension.js:536:9
Melange.prototype.ReloadExtension@/usr/share/cinnamon/js/ui/lookingGlass.js:639:9
_handleMethodCall@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:261:22
_wrapJSObject/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:331:16
```
=> extension.js: Fix ReloadExtension error in forgetExtension

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This toggles the progress pseudo class depending on if the window progress is greater than zero.
=> window list: Prevent the progress indicator from showing when set to 0

js/ui/panel.js
Prevents this error when the panel is removed. I didn't expect the style-changed signal to be emitted on destroy...
(cinnamon:29644): Cjs-WARNING **: JS ERROR: TypeError: this._box.get_parent(...) is null
PanelCorner.prototype._styleChanged@/usr/share/cinnamon/js/ui/panel.js:1469:21
Panel.prototype._destroycorners@/usr/share/cinnamon/js/ui/panel.js:1965:9
Panel.prototype.destroy@/usr/share/cinnamon/js/ui/panel.js:2083:9
PanelManager.prototype._onPanelsEnabledChanged@/usr/share/cinnamon/js/ui/panel.js:802:17
check_key_and_set@/usr/share/cinnamon/js/ui/overrides.js:46:16
overrideGio/Gio.Settings.prototype.set_strv@/usr/share/cinnamon/js/ui/overrides.js:88:71
PanelManager.prototype.removePanel@/usr/share/cinnamon/js/ui/panel.js:464:9 …
=> panel.js: check if the panel corner has a parent

src/st/st-private.c, src/st/st-theme-node-drawing.c
https://github.com/GNOME/gnome-shell/commit/6d22670307928dfdce75a7536598486fa25d51d7#diff-8a01b40c2c1be22ef97916811be0ab65
Stops a potential fault condition causing a crash.
=> Guard against failure of cairo_pattern_get_surface()

js/ui/panel.js
When converting for ... in to normal for loops in panel.js (https://github.com/linuxmint/Cinnamon/commit/718ce025dc360d62c6e510b5b57483553bf80c1c) the array elements needed to be checked for undefined because panels and panelsMeta are being created through direct assignment, and their index is treated as key, which means they can't be converted to just pushing values without breaking panel configurations. This is a simple fix for now, but the panels arrays should be keying by a value that's contained within their actual value, unless they're a normal keyed object, so this is something I might try to dig into more deeply later.
=> panel: Fix not being able to add panels on all sides of the only or last monitor

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
the new progress bar overlay was showing unwanted artefacts as it was using .visible instead of a direct
show or hide of the overlay actor. Simplified the use of the pseudoclass to ensure
it was only set once.  Theme Graphite-Zero can be used for testing if required
the unwanted artefacts are particularly visible in a vertical left panel
=> window-list: correct progress overlay logic

js/ui/appletManager.js, js/ui/dnd.js
Fixes the following errors on GJS 1.49/mozjs52, and regression tested on CJS 3.4.4/mozjs38.
```
(cinnamon:3425): Gjs-WARNING **: JS ERROR: TypeError: applet is undefined
saveAppletsPositions@/usr/share/cinnamon/js/ui/appletManager.js:544:1
PanelZoneDNDHandler.prototype.acceptDrop@/usr/share/cinnamon/js/ui/panel.js:1762:9
_Draggable<._dragActorDropped@/usr/share/cinnamon/js/ui/dnd.js:502:21
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Draggable<._onEvent@/usr/share/cinnamon/js/ui/dnd.js:188:24
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_getEventHandlerActor/<@/usr/share/cinnamon/js/ui/dnd.js:56:46
(cinnamon:3425): Gjs-WARNING **: JS ERROR: TypeError: this._dragActor.get_stage(...) is null
_Draggable<._dragActorDropped@/usr/share/cinnamon/js/ui/dnd.js:471:22 …
```
=> dnd, appletManager: Fix applet DND on mozjs52

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This allows themes a bit more flexibility with theming the new progress
indicator. It also allows our 'important' property to work for themes that don't
yet have specific support.
=> Use a style class name for the new window list progress indicator

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
The title in the list widget, which has been introduced with Cinnamon 3.4, is not translated.
Gotta catch (and translate) 'em all.
=> xlet-settings: translate title in list widget

js/ui/dnd.js
Can't see any regressions. I did see this at one time in the log, but could not reproduce, so it could be coming from somewhere else
(cinnamon:21731): Clutter-CRITICAL **: clutter_layout_manager_allocate: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
=> dnd: avoid use of deprecated reparent

src/st/st-theme-node.c
https://github.com/GNOME/gnome-shell/commit/6fc5b0477ba1c77b6bcdd23e07254fbe97c92b83#diff-b948bb195b709c61ce7275142a2fbdfd
=> theme-node: Fix font family formatting

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
For Cinnamon users with multiple workspaces, this setting option enables the window list to show all regular windows from all workspaces. I got tired of this feature not existing, so here is my attempt.
=> Add Show all workspaces setting to window list

js/ui/indicatorManager.js
Adds support for triggering the SecondaryActivate function on an appindicator by clicking the middle mouse button on the icon. This is the same behaviour as in Unity on Ubuntu, and since middle mouse clicking does nothing in Cinnamon currently I thought it might be nice to have.
More info:
https://bugs.launchpad.net/unity/+bug/812933
https://developer.ubuntu.com/api/devel/ubuntu-13.10/c/AppIndicator3-0.1.html
=> indicatorManager.js: add support for appindicator SecondaryActivate

files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py
Requires linuxmint/cinnamon-settings-daemon#181.
The scrolling work is compatible with either driver. Clickpad support works differently: synaptics does not disable button emulation in any case, at least on the laptop I have at hand.
If you need a reminder why libinput makes sense: see https://fedoraproject.org/wiki/Changes/LibinputForXorg
TL;DR other distros are moving towards it, and it can handle a number of modern input devices better. The synaptics driver was for instance not built for laptops where buttons need to be emulated and its default (and only) way of handling those devices causes issues for some (especially Lenovos).
=> Make touchpad settings compatible with libinput

src/st/st-icon.c
github.com/GNOME/gnome-shell/commit/60e7db71260ed2f8e22760c52bcf6288e1bfe6ba#diff-b948bb195b709c61ce7275142a2fbdfd
and
GNOME/gnome-shell@7f381dd#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-icon: remove unused fields

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, js/ui/appSwitcher/appSwitcher.js
Related to #6922, this commit adds "Show all workspaces" to the alt-tab appSwitcher utility.
=> Add 'show all workspaces' setting to appSwitcher

files/usr/share/cinnamon/applets/show-desktop@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, js/ui/accessibility.js, js/ui/expoThumbnail.js, js/ui/indicatorManager.js, js/ui/panel.js, js/ui/popupMenu.js, js/ui/tooltips.js
This passes null so SignalManager doesn't cache the context, which it uses for binding callbacks. This can be replaced by SignalManager.connect's fourth parameter, bind.
Since the manager is a property of its callee, re-referencing `this` inside each SignalManager instance will create a circular reference, and while they are not inherently bad, it forces the engine to check more objects. Spidermonkey in particular counts circular references as part of an object's reference count, which makes it more likely an object will exist after its needed, and it will continue to consume memory.
=> Performance: Avoid caching `this` context in SignalManager instances

files/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/expo@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/inhibit@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/removable-drives@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/scale@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/separator@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/settings@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/show-desktop@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/slideshow@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/spacer@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/user@cinnamon.org/stylesheet.css, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/xrandr@cinnamon.org/applet.js
Remove unused variables, add missing semicolons, use `[]` notation instead of `new Array()`, etc.
=> Applets: fix linter warnings

js/ui/windowManager.js
Users find the useful and there is no reason to hide it just because effects
are disabled
Fixes https://github.com/linuxmint/Cinnamon/issues/6942
=> window-manager: Show the workspace OSD even when effects are disabled

js/ui/main.js
How to reproduce: run `global.log` on an AppletSettings instance. 
It turns out there are some native objects [CJS can't stringify](https://github.com/linuxmint/cjs/blob/f7638496ea1bec4c6774e6065cb3b2c38b30a7bf/cjs/context.cpp#L138), so a try-catch block is used to short circuit the recursion in this scenario.
=> Main: Work around unserializable object exception from CJS in formatLogArgument, improve indentation and JSON serializable object visibility

src/cinnamon-util.c
https://github.com/GNOME/gnome-shell/commit/447246da741da9126aadb41c98a9179290bbcd86#diff-e13d0669f81906a880112b462a031c53
also fix an instance of deceptive indentation
And then I found some similar leaks ...
=> cinnamon-util: fix GFile leak

src/st/st-texture-cache.c
routine could possibly be removed, I can only see it being used by one third party applet
=> st-texture-cache:  load file simple, avoid leaks

js/ui/popupMenu.js
Placing the pivot point not in the center shifts the arrow a little bit down when rotated and it becomes **vertically off-centered** and **blurry** because it is in a subpixel position.
See the screenshot (view it at 100% zoom):
_Before vs after._
=> Fix blurry and off-centered arrow in popup submenus

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
When uncommenting the try-except block wrapping the _install method, this stack trace was seen when trying to install `multicore-sys-monitor@ccadeptic23` (since patched on the xlet side). 
```sh
Exception in thread Thread-85:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 283, in _process_job
job['result'] = job['func'](job)
File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 577, in _install
if file.split(".")[1] == 'po':
IndexError: list index out of range
```
=> Spices.py: Fix xlets not installing if a file without an extension is in the po directory

files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
Double clicking in an row launches the edit dialog as when clicking the edit button.
=> TreeListWidgets.py: edit elements with double click

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py
When running a new dialog, the following is printed in the terminal : Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
See issue : #6976
=> cinnamon-settings-users.py : Fixing Gtk-Message when running a dialog

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Some items are hidden so we have to skip hidden actors while
accounting for their index.
fixes #6807
=> window-list: account for hidden items during DnD repositioning

src/st/st-texture-cache.c
the code makes the assumption that if no texture is returned then the error is set
this change avoids making this assumption.  Found with scan-build.
=> st-texture-cache: avoid potential null pointer dereference

js/ui/panel.js
occasionally the null applet position was being carried through to the writing of the new applet
causing apparent drop failures, and to the disappearance of the highlighted drop box.  Much visible
weirdness with a very simple solution
=> initialise applet position to avoid drag and drop errors in edit mode

js/ui/popupMenu.js
Leaving sourceArrow undefined shouldn't have an adverse effect on Cinnamon since a check was added for sourceArrow in PopupSubMenu.prototype._init, but silencing the warning for cleaner log files.
=> popupMenu: Prevent warning of this._triangle

src/st/st-theme.c
Changed to how it was before - gives a warning and returns null.  Much friendlier.
=> st-theme.c: st_theme_resolve_url could assert with a theme issue

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Prevent iteration of device.get_icon_name() if it is Null
Fixes: TypeError: argument of type 'NoneType' is not iterable and some sinks not appearing in sound settings.
#7053
=> Fixes crash if device.get_icon_name() is Null

files/usr/share/cinnamon/cinnamon-settings/modules/cs_online_accounts.py
The help dialog of Cinnamon Online Accounts was translated, but it is not used currently.
Tell the gladefile, where to look for translations.
Fixes https://github.com/linuxmint/Cinnamon/issues/7076
=> Online Accounts: Use translations

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
The letter `n` is cut off, if it appears at the end of a description.
Fixes https://github.com/linuxmint/Cinnamon/issues/7096
=> Spices description: Do not cut off the letter `n`

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
If a system xlet is overwritten in `~/.local/share/cinnamon/xlets`, the local xlet is used, but the system metadata info is shown.
Fix to show local metadata, when local xlet is used
=> Xlets: Fix shown info for overwritten xlets.

src/st/st-cogl-wrapper.c, src/st/st-cogl-wrapper.h, src/st/st-icon.c, src/st/st-label.c, src/st/st-private.c, src/st/st-private.h, src/st/st-theme-node-drawing.c
https://github.com/GNOME/gnome-shell/commit/1c1f63a7d7a5f0be5a796679d029a6b0c600b838#diff-578ccc5ce70c4a11d7f30e3f38002f0bR168
also
st: Adapt the mutter implementation for create_texture_material
https://github.com/GNOME/gnome-shell/commit/05f9f991d8d5796b77def6c096a36786b5307351#diff-578ccc5ce70c4a11d7f30e3f38002f0b
This was adapted to make use of the static cogl context in st-cogl-wrapper
No regressions that I can see.
Presumably for Cinnamon 3.8 at this stage in the cycle
=> st-private: Update shadow APIs for Cogl deprecations

docs/reference/cinnamon-tutorials/importer.xml, js/misc/fileUtils.js, js/misc/util.js, js/ui/applet.js, js/ui/appletManager.js, js/ui/cinnamonDBus.js, js/ui/deskletManager.js, js/ui/environment.js, js/ui/extension.js, js/ui/extensionSystem.js, js/ui/lookingGlass.js, js/ui/main.js, js/ui/panel.js, js/ui/searchProviderManager.js, js/ui/settings.js, tests/interactive/urgentwindow.py, tools/check-for-missing.py
Depends on: https://github.com/linuxmint/cjs/pull/54
This cleans up some cyclical references and moves state from nested objects to an array of objects in extension.js. Global properties were made read-only, in the unlikely event they are re-assigned and crash Cinnamon. This also restructures the extension code for asynchronous loading using [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). 
The main advantage of loading extensions asynchronously is non-blocking I/O. Currently, when an extension is loaded, the UI locks up until the extension is finished loading. Worse, this can cause Cinnamon to freeze up entirely if a mistake is made in the xlet's code. It also opens up the possibility of off-loading smaller tasks to dedicated worker …
=> Refactor the extension system and add commonjs compatible module importation

js/misc/config.js.in, js/misc/fileDialog.js, js/misc/fileUtils.js, js/misc/gnomeSession.js, js/ui/dnd.js, js/ui/main.js, js/ui/messageTray.js, js/ui/overrides.js, js/ui/popupMenu.js, js/ui/search.js, js/ui/windowAttentionHandler.js, js/ui/workspacesView.js
Depends on: https://github.com/linuxmint/cjs/pull/61
This fixes some of the mozjs52 related warnings occurring in the logs except for extension related modules, which will be handled in #6878.
This also fixes a few string.replace calls so they only use regex, the old way of only passing strings to `replace` was not on a standards track and will break in JS.
Some unused imports were also cleaned up.
=> Fix issues related to Cinnamon running with cjs/mozjs52

src/st/st-theme-node-transition.c, src/st/st-theme-node-transition.h
https://github.com/GNOME/gnome-shell/commit/2f88a7a1e15032bb91a2a732ee2eaad9e70fe3d2#diff-b948bb195b709c61ce7275142a2fbdfd
=> st: Drop vfuncs from StThemeNodeTransition

src/cinnamon-tray-manager.c
https://github.com/GNOME/gnome-shell/commit/b5d3c4e165a97376907d4bd6f808a82d55c60a85#diff-25d902c24283ab8cfbac54dfa101ad31
=> shell-tray-manager: Disconnect theme_widget signals on finalize

src/cinnamon-embedded-window-private.h, src/cinnamon-embedded-window.c, src/cinnamon-gtk-embed.c
https://github.com/GNOME/gnome-shell/commit/d212d574669ef842cb39a0a0f7a7fa066656528c
see issue #5573
thanks to @lestcape for pointing this out.
Can't see any regressions, but also can't check against the collapsible systray applet that generated the issue, as it has some problems. Hence suggest that this fix can wait for 3.8
=> shell-embedded-window: change realize to map

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_desklets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
This will allow the value of the column to be limited to specified values. If options are supplied, a combo box will be generated rather than the usual widget for that data type.
The settings example applet and the settings reference page were also updated to reflect this additional feature.
Addresses #6970
=> Allow column options in the xlet settings list widget

files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js
Fixes the following warning when animations are enabled:
```sh
(cinnamon:3968): Clutter-WARNING **: clutter-actor.c:10033: Actor 'StIcon' tried to allocate a size of -30.00 x 24.00
```
=> windows-quick-list: Fix icon allocation warnings

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
Change the default behaviour of toggle mute from output only to input and output. Add two new options to toggle mute for output only or input only.
=> sound applet middle click mute refinement

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, js/ui/popupMenu.js
Credits to claudiux and https://github.com/linuxmint/Cinnamon/pull/7187 for the initial design and implementation.
This commit makes it possible to configure the maximum sound volume in the sound settings and modifies
the settings module and sound applet appropriately.
Depends on https://github.com/linuxmint/cinnamon-desktop/commit/d35987157f5d35c3b19db9d5f5adc19633f49589.
CSD change: https://github.com/linuxmint/cinnamon-settings-daemon/pull/215.
=> Sound: Make maximum sound volume configurable

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/ui/main.js
The goal of this PR is to make it faster for Cinnamon to open windows.
Using the following test script:
```
#!/usr/bin/python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject
import time, threading
def print_timing(func):
def wrapper(*arg):
t1 = time.time()
res = func(*arg)
t2 = time.time()
print('%s took %0.3f ms' % (func.__name__, (t2 - t1) * 1000.0))
return res
return wrapper
def async(func):
def wrapper(*args, **kwargs):
thread = threading.Thread(target=func, args=args, kwargs=kwargs)
thread.daemon = True
thread.start()
return thread
return wrapper
def idle(func):
def wrapper(*args):
GObject.idle_add(func, *args)
return wrapper
class MyApp ():
def __init__(self):
self.windows = []
mainwindow = Gtk.Window()
box = Gtk.Box()
button = Gtk.Button() …
```
=> Speed up windows mapping

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
* Setting label text to empty hides it, so that it doesn't take up any space when using paddings, margins or spacings.
* Also removed the fixed margin to separate the label from the icon as themes now have the ability to do that.
A visual example:
> **NOTE**: This only takes place when there are no devices, because when there are the label is set to empty correctly if "nothing" is selected.
=> Power applet: truly hide label when there are no devices

js/ui/dnd.js
Prevents the following warning:
```
(cinnamon:3026): Cjs-WARNING **: Some code accessed the property '_Draggable' on the module 'dnd'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```
=> dnd: Fix scope warning

js/ui/popupMenu.js
and use it when the menu is closing due to a parent open-state-changed
notification during parent animation.
This prevents PopupMenus from changing size/position during the close
tween when they contain open PopupSubMenus.
Before:
After:
=> popupMenu.js: PopupSubMenu: add prototype method closeAfterUnmap

files/usr/share/cinnamon/cinnamon-settings/bin/GSettingsWidgets.py
Before this patch, settings widgets that did set bind_dir=None would not have their sensitivity set to false when the gsettings key is locked.
=> Prevent users from editing locked settings

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
We want this to match the other sliders in the sound settings. The size group
we were passing was forcing the labels to take up to much space.
=> cs-sound: Fix the width of the amplification slider

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
This allows us to use a non-scaled icon in the panel which looks nicer than the
slightly blurred version we get when scaling 20px.
=> panel-launchers: Set the default icon size to 22

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
This makes them easy to copy/paste the information.
Closes: https://github.com/linuxmint/Cinnamon/issues/7174
=> cinnamon-settings-info: Make some labels selectable

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
=> applets/cinnamon-settings: Add some settings used commonly on Red Hat based distributions

files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py, js/ui/messageTray.js
Depends on: https://github.com/linuxmint/cinnamon-desktop/pull/100
Closes #4892
=> Notifications: Add support for a bottom position option

docs/reference/cinnamon-js/Makefile.am, docs/reference/cinnamon-tutorials/Makefile.am
<s>Can't think of a better way to do this. The gen_doc_ran file should probably be cleaned on make clean, but I don't know how to do that. I initially made gen_doc_ran a .PHONY target, but that made it regenerate the docs during make install.</s>
=> Fix cinnamon-js doc build w/ gtk-doc 1.27

src/st/st-private.c
https://github.com/GNOME/gnome-shell/commit/941513b280433c269491572b7b1de2a7c5bab21b#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-private: Fix offscreen leak if cogl_framebuffer_allocate fails

src/st/st-theme-node-drawing.c
https://github.com/GNOME/gnome-shell/commit/8416ba25de3797c1fdfd49b2a598f3e380713129#diff-b948bb195b709c61ce7275142a2fbdfd
=> st: Don't assert when corner texture creation fails

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
For example when there's a dependency in an xlet's settings.
I forgot to mention that it happened only if one clicks on the row instead of the switch.
=> SettingsWidgets: prevent toggling disabled switches

src/st/st-entry.c
https://github.com/GNOME/gnome-shell/commit/4e07d0b0737fd557538c7452d4a00d58e0f626c2#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-entry:don't possibly allocate actors a negative size

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This small change makes the sound applet reuse the same temp file for
downloading cover files. Previously, a new file was created in /tmp/ for every
song, cluttering /tmp/ with cover images.
This should not affect behaviour of the applet in any other way as wget is used to download the covers, so if the file is accidentally removed by the user, it will simply be recreated when new cover is downloaded. showCover is called after the download finishes, so there is no risk of showing the cover for the previous song.
=> Sound: reuse cover temp file

js/ui/appletManager.js, js/ui/panel.js
This wasn't working because when an item from `rawDefinitions` is removed, the array re-indexes and the following cached indexes become incorrect.
=> Fix panel applet clearing

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
This setup no longer even works in gtk3.20+ and is the source of a bunch of
build spam. Just remove it and let themes handle it. Since it already isn't
working it won't make any difference in themes that don't.
=> [gtk3.22] cinnamon-settings: Remove some broken and hardcoded theming

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
We now use the the "window-list-preview" style class for the preview
in order to allow fine grained control instead of sharing the window
switcher's style class.
Adds support for user to disable the preview label and to change the
thumbnail size from 75% to 150% of default.
<s>The thumbnail may have some aspect ratio issues right now, and the default theme may need a few tweaks, but this is the basic idea.</s>
Support will need to be added to all existing themes. Until then the default theme as shown <s>here</s> below will be displayed.
=> window-list: unique style class and new preview options

js/ui/search.js
Optimize RegExpr. Changes:
1) Remove search by regexpr and use `includes` for checking contains sub string. RegExp is redundantly for this case.
2) Removed needless `match`, to aviod `double regexp search`
3) For string `trim` use native method instead of 2 regexprs
=> Optimize RegExprs in ui search

js/ui/appFavorites.js
This PR contains the following changes.
1) Optimize generating favorites map. Use `reduce` for array. Only 1 loop instead of 3 loops.
2) Use native functions like `Object.keys`, `Object.values` instead of `for loop`
=> Optimize appFavorites

data/theme/cinnamon.css
The images are 22x64 not 22x65.
=> Fix blurry switches in the default theme

src/st/st-theme-node-drawing.c, src/st/st-theme-node-private.h, src/st/st-theme-node-transition.c, src/st/st-theme-node.h, src/st/st-widget.c
three linked upstream commits, one requiring some adaptation.  No obvious regressions, no new warning messages.
=> st: remove some cogl deprecations

js/ui/appletManager.js, js/ui/deskletManager.js, js/ui/extension.js, js/ui/extensionSystem.js, js/ui/searchProviderManager.js
1. Removes the promise for `unloadExtension` since nothing asynchronous is happening inside this function. 
2. Fixes applets being moved to new position within a panel location not being recognized as a change.
3. Unsure if this was occurring on master already, but deskletManager's change handler was updated so desklet removing worked correctly without a Cinnamon restart.
=> appletManager, deskletManager: Fix change handlers

files/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
Enable text wrapping for the label widget because one typically wants more than one line in there.
Also added it to the settings example so that new xlet creators know that it exists and how to use it.
=> Improve label settings widget

js/misc/fileUtils.js, js/ui/extension.js, js/ui/extensionSystem.js
- Removes left over code that imported multi-version xlets with the cjs importer
- Re-added `extensionMeta`
- Made the meta object available to the xlet scope with the variable `__meta`
=> Fix multi-version xlets loading twice, address metadata availability

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py
Removes some custom themeing which was used only for custom file watch tabs' close button, as it was broken during the python3 migration. Since it was broken, and it's also obsolete style properties that have no effect in gtk 3.20+ now seemed like a good time to remove it.
Fixes a crash with FileWatcherView when the watched file is updated in quick succession. The crash was 100% reproducible by adding a watcher for `~/.xsession-errors` and restarting cinnamon.
Stack trace:
```
Fatal Python error: Segmentation fault
Thread 0x00007f020f7fe700 (most recent call first):
File "/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 725 in set_text
File "/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py", line 276 in update
File …
```
=> Melange fixes

data/theme/cinnamon.css
Hi,
These selectors appear to have been defunct since [this commit](https://github.com/linuxmint/Cinnamon/commit/7b9ced98a35cd5fb5e4de01d78c51fd8fbb23ec4) in July 2013. I don't think any supported version of Mint is still using a cinnamon release this old and needs a theme with these selectors.
=> Remove deprecated .panel-launcher-add-dialog selectors

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py, js/ui/messageTray.js
This adds a simple close button to all notifications that can be used to dismiss them individually without
activating the associated action.
Additionally, this removes the "fade on mouseover" feature for notifications as it makes closing the notification harder. Currently we disable this feature for notifications that have action buttons. Extending this behavior to all notifications so the close button is easier to use will effectively disable the feature anyway.
=> notifications: close button and no fade on mouseover

js/ui/notificationDaemon.js
Apps like Chromium and Firefox create notifications with a reasonable
expectation that the user should see them before they disappear.  The
old behavior was to clear notifications when the app became focused.
If the user was away when notifications were generated, they would be
stored in the message tray.  If the user then focuses the app, all of the
notifications would disappear (even if the notifications had critical
urgency), never giving the user a chance to see them.
This behavior is not intuitive and can lead to loss of important notifications,
so this CL removes this behavior altogether.  Users can still use the "clear
all notifications" button in the tray.
=> Don't clear notifications when an app becomes focused

js/ui/notificationDaemon.js
processNotification() used to call pushNotification() if the
notification was resident and the app had focus.  This CL changes it
to always call notify() instead.
The only difference is that notify() additionally emits the 'notify'
signal which hooks into _onNotify(), the function that actually puts
the notification into the queue.  Without this, the notification would
never get displayed.
=> Fix resident notifications not displaying

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
This causes a strange two stage display sequence for the user. Precautionary delay for the application to load is already baked in before this.
It's not clear to me why there would be a timing difference between scale mode (which has this extra delay) and having the icon size set by default/theme (no additional delay).  There's already a 1 sec initial delay for most applications which I presume is precautionary to give them time to load, so the current code gives a 1 second delay in most cases before an unscaled icon shows- and then there is a re-scaling of the icon to the expected size half a second later.  That's a bit weird, and gives an unhelpful impression of Cinnamon being slow and laggy.  Unless someone knows of a really good reason why the half second additional delay is in there, …
=> Systray: remove the resize delay in scale mode

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, js/ui/indicatorManager.js
1. Fixes off-center icons by only using the applet-box class on indicator actors if a label is present.
2. `_shellIndicators` in the systray was converted to an array for faster iteration.
3. Fixed reference to the systray applet being added to each indicator object. I searched all of Cinnamon's JS and couldn't find an instance of it being used.
=> indicatorManager, systray applet: Fix off-center icons, keyed object iteration, circular reference

js/ui/appletManager.js, js/ui/deskletManager.js, js/ui/extension.js
- Removes the call to unloadExtension in `onEnabledAppletsChanged`. It was calling a function that can only remove by UUID. In cases where multiple applets of the same UUID are on the panel, and only one instance needs to be removed, this prevents all of them from being removed.
- Re-added addAppletToPanels in `onEnabledAppletsChanged`. `initEnabledApplets` will try to initialize enabled applets, but the `Extension` constructor checks its cache and resolves true if an xlet of the same UUID is already loaded. This is ideal normally because instances are tracked in appletManager, but it skips the actual panel loading event.
- Fixes incorrect invocation of `formatError`, caught by @Odyseus 
- `_onEnabledDeskletsChanged` no longer gets called when desklets are dragged
=> appletManager, deskletManager: Fix incorrect handling of adding/removing multiple xlets of the same UUID

js/ui/appletManager.js
Since we removed the discrete instances object appletObj and merged
instances into the definition object, we now have null instances.
This occurs during startup, for definitions that are on removed panels,
and likely for applets that fail to load.
To return the previous behavior we just need to filter instances that
aren't actually running at the moment, aka null.
=> appletManager.js: fix getRunningInstancesForUuid()

js/ui/panel.js, js/ui/popupMenu.js
Children were allocated at 0 over the top-left borders and paddings, leading to dead zones in the opposite side.
Fixes #6440
Visual explanation:
```css
.panel-bottom {
background: red;
border-top: 8px solid blue;
}
```
**I need to test it in RTL mode**. I did my best but I could not find a way to enable it. If you tell me how to do it I'll check if it works with that (it should).
=> Fix bad allocation of panels with borders

files/usr/share/cinnamon/applets/show-desklets@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/show-desklets@cinnamon.org/metadata.json, files/usr/share/cinnamon/applets/show-desklets@cinnamon.org/settings-schema.json, js/ui/deskletManager.js
- Modified `DeskletContainer` to enable raising its actor above and below the window group, based on code @collinss wrote for the sticky notes applet.
- When clicking outside of a desklet, the desklet container is lowered and input is released.
- Tested all desklets on Spices, and they seem to behave the same when raised and input is grabbed.
- Added a companion stock applet, "Show Desklets" which toggles desklet visibility when clicked.
- Added a context menu shortcut to add desklets
- Added a keybinding shortcut option, which defaults to Super + Tab. I didn't see this conflicting with anything, but could be wrong. If so I can change it.
- Written using ES2015 class syntax. I think it looks cleaner than the constructor style. While there is a specific syntax for [GObject classes in …
=> Add ability to raise desklets above windows

files/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/metadata.json
Use the same icon for the applet, which is used for the application
=> on-screen-keyboard applet: change icon to keyboard

files/usr/share/cinnamon/applets/user@cinnamon.org/applet.js
Upstream fixed 'changed' signal being emitted far too often which broke
initial loading of the user info here and exposed this typo. It would
still load and work as usual after the first legitimate changed signal.
fixes: #7471
=> user-applet: fix loading with newer accountsservice

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
This is changed in gtk3.20+ and we need to fix this so they are themed
correctly
=> keyboard-settings: Fix the use of wide separators

.eslintrc.json
- Excludes more Cinnamon-specific globals like `send_results`.
- [no-unused-vars](https://eslint.org/docs/4.0.0/rules/no-unused-vars) rule now excludes parameters, and a select list of variables that are either exported and eslint is unaware of it, or is often used in array assignment.
- [indent](https://eslint.org/docs/4.0.0/rules/indent) rule now ignores some pythonic ways of aligning properties in objects and elements in arrays, and most instances of switches cases triggering it.
- Disabled [no-use-before-define](https://eslint.org/docs/4.0.0/rules/no-use-before-define) for functions since most of the functions in Cinnamon triggering this are globals.
- Disabled a couple other rules that are more opinionated and harmless such as …
=> Update eslintrc.json for more flexibility

js/ui/settings.js
This fixes the settings so if an xlet sets null as the value of one of its settings, it fails in the xlet instead of in settings.js.
=> ui/settings: Check for null values on this.settingsData

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, js/ui/messageTray.js
The applet keeps track of notifications via `this.notifications`, so we can use that to access the `Notification` instances instead of relying on the actor._delegate reference.
=> Notifications: Remove circular reference on notification actors

files/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-active-symbolic.svg, files/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-symbolic.svg
The ZZ's inside where not paths and they weren't affected by the color property. I converted them to paths.
Screenshot of Mint-X:
=> Inhibit applet icon: fix uncolored parts

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
With simple buttons:
In visual mode:
After this patch:
=> Workspace switcher: fix blurry #panelRight's applets in visual mode

files/usr/bin/cinnamon-json-makepot
* The help option was causing the script to scan the current folder. Passing the -h option now imforms the user that cinnamon-json makepot is deprecated and gives a helpful tip about using cinnamon-xlet-makepot instead and then quits.
* Fixes the -i and -r options which use slightly different syntax.
* Include the command in the args list so the first arg doesn't get dropped.
* Properly append the output path to args rather than concatinating.
=> cinnamon-json-makepot: fix some issues

js/ui/tooltips.js
Hi,
Fixes #7267 & #7266 
Complements #7325
A similar problem to that addressed in #7325 affects tooltip positions in panels with a border.
e.g. 
This commit changes the calculation of the tooltip vertical position to be based on the panel height for horizontal panels, and panel width for vertical panels. A one pixel buffer is added to ensure that there is some separation between a panel with borders and a tooltip with borders.
After - 
Please be gentle if I've done anything really stupid in the JS - it's been a number of years since I've done any JS work and I am an amateur by any definition of the word.
=> tooltips.js - base #PanelTooltip position on panel width / height

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_inspect.py, js/ui/lookingGlass.js
Main window:
- Adds a garbage collect button next to the inspect button. This is
also on the currently disabled memory tab.
- Removes description labels and adds tooltips instead
- Uses nicer keybind display format
Inspect tab:
- Back button is now always enabled. When the inspection stack is
empty then the Results tab is activated.
Results tab:
- Eval result tooltip: sub-millisecond precision for execution time
- Inspection result tooltip: generic tooltip so it's not blank
Screenshots only show some of the changes:
Before:
After:
=> Melange: slight UI rework

js/ui/modalDialog.js
=> Modal dialog: don't stretch icon, align it to the top

src/st/st-scroll-bar.c
Positions must be integers.
**Two visual examples**  _(zoom in without smoothing to see better)_
=> Fix blurry st scrollbars

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py
In python3 the / operator returns floats, to maintain the previous behaviour
we need to use the // operator.
=> Use ints for the menu position

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
- Inside the `Spice_Harvester` class initialization code the `dbus.exceptions.DBusException` exception was used, but the **dbus** module wasn't imported.
- The `disconnect_proxy` method of the `Spice_Harvester` class had what seemed to be a typo (**please, triple check this**).
- The `enable_extension` method of the `Spice_Harvester` class had several lines ending with semicolon.
=> [Spices.py] Added missing import, fixed typo and removed unnecessary semicolons

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Just reorders code so that search providers results are added before selecting first result as selected item.
Fixes #7412 
@NikoKrause - Stark Menu has the same issue and the same fix I think would apply. Cinnamenu doesn't have this issue.
=> menu applet - if no selected item when adding search provider results make first search provider result selected item

data/theme/cinnamon.css
Hi,
`.menu-category-button-button` is unused and may simply be an uncaught typo from many years ago.
`..menu-category-button-selected` is valid and makes sense in this context and as written does distinguish visibly between the selected category and a hovered and selected category. Whether the visual effect is desirable I'll leave for others to decide.
=> Default menu - fix unused selector .menu-category-button-button

js/ui/keyboard.js, js/ui/panel.js
* Add some padding to the OSK so that the top panel doesn't overlap it.
* Also better calculate paddings to avoid a layout overflow.
* Add a missing _else_ in _heightsUsedMonitor_.
=> Fix top panel overlapping the on-screen keyboard

files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py, js/ui/hotCorner.js, js/ui/layout.js
* Avoid systematic console warnings.
* Remove usage of deprecated functions.
* Place corners on the primary monitor when there is a bottom monitor. In general, hot corners aren't placed across monitors.
* Remove duplicated event listeners and buttons remains.
* Fix `shouldToggleOverviewOnClick` not taking effect.
* Update `cs_hotcorner` interface and internals
=> Hot corners cleanup and fixes

js/misc/fileUtils.js
* Fix exported variable/functions regex. It didn't recognize variables with numbers in the name.
* Fix module.exports recognition regex and remove clutter. It only recognized some exported variable names, but not numbers nor objects, and it required a space before and after the assignment token (=).
* Add a new line character after the prepended 'use strict' or otherwise the parser won't recognize exported variables in the first line.
* Use test instead of match because it's faster in this use case. It only checks until the first occurrence and doesn't generate strings like match.
**Just a note.** 
I wasn't sure if the exports regex was supposed to match things like `module.exports = myVariable`, so I opted for keeping the old behavior and allow it (I was not able to make use of it …
=> Fix JS exporter parsing

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
The problem was caused by the ListBox trying to select the ListboxRow that's wrapped around the Textview widget, even though it was set to SelectionType.None. This caused the Textview to lose focus as soon as the mouse button was released, which in turn rendered the Textview almost unusable. This pull request explicitly forbids the ListboxRow from receiving focus, which it shouldn't have anyway, as the Listbox is only there for cosmetic reasons anyway.
=> SettingsWidgets.py: TextView widget - fix focus-stealing bug

data/theme/cinnamon.css
Hi,
The style_class `.menu-background` was fixed in #5948.
I think it should be referenced in the default theme so that new themers are more likely to be aware of the possibility without necessarily trawling through the stock applet code.
=> default theme - add .menu-background{} as placeholder

files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
cinnamon-session also starts the autostart desktop files that are OnlyIn
GNOME, and drops all the ones that are set listed in
org.cinnamon.SessionManager autostart-blacklist gsetting.
=> Sync the logic in cs_startup with cinnamon-session

src/cinnamon-generic-container.c, src/cinnamon-global.c
helps to avoid full stage redraws
see: https://bugzilla.gnome.org/show_bug.cgi?id=694988
=> report paint volumes / don't use stage "paint" signal

src/st/st-theme-node.c
For example when you change the handle position of a switch.
=> Repaint node when background position changes

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
This change introduces the option to make your machine turn off completely when the lid is closed, as well as turning of when the power reaches a critical level.
I always find myself adding these lines manually in all my machines, so I figured I might not be the only one.
=> Added "shutdown immediately" entries for lid close and power critical.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
This no longer works under gtk3.22 so go ahead and just get rid of it. Even
Adwaita now supplies both a full light and dark variant.
=> cs_themes.py: Remove the setting for prefer-dark-themes

js/ui/messageTray.js, js/ui/notificationDaemon.js
- Reverts #7252 and adds a blacklist which includes chrome, chromium, and firefox
- Limits notifications to 10 per source. When a new notification is added and 10 notifications exist, the oldest notification is dismissed.
More details in the first commit.
=> Notification clearing on app focus + blacklist + limit

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
* There was no margin the first time it showed up because the position was set before actually showing the actor.
* Update position when window size changes, notably when bottom-positioned (try this with cinnamon-settings themes, which has a long startup, in a bottom panel).
=> Fix window list previews position

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Because the files are zipped, and then unziped, the execute bit is getting lost when xlets are installed through cinnamon-settings, which in turn causes certain included scripts to not run. This sets the permissions manually on all files to ensure that everything has the necessary permissions.
=> Spices.py: fix file permissions durring install

js/ui/popupMenu.js
**When using margins** on the menu it is shifted a bit and the clip doesn't end just in the panel. This is fixed by taking margins into account for the end/start positions and the clip size.
For some reason, sometimes margins must be subtracted twice. There is no math here, only trial and error. I haven't found a logical behavior, only that actors are automatically shifted when they have margins.
For example:
```js
actor.x = actor.x - actor.margin_left      // Does nothing
actor.x = actor.x - actor.margin_left * 2  // Shifts margin ok
actor.x = actor.x                          // Shifts actor to the right
```
=> popupMenu: fix menu cutoff during open/close animation

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
* Use `with lock` instead of `lock.acquire` to ensure a lock always gets removed.
* When updating the download progress use the total downloads to calculate the fraction only when there is more than one download. This prevents a divide-by-zero under certain circumstances, and gives more meaningfull progress information.
=> Fix some issues with the download refactoring in Spices.py

js/misc/fileUtils.js
This fixes a bug when module.exports is overwritten with a new object, breaking the reference to the exports variable in the xlet scope, resulting in the module returning undefined.
Also re-approaches the fix for variables on the first line in a file being ignored because the solution in #7477 causes the line numbers in stack traces to be offset by 1.
=> fileUtils: Fix module exporter bug, fix line numbers in stack traces being incorrect

js/ui/layout.js, js/ui/main.js
chrome: Improve visibility conditions for panels and other chrome
when windows are fullscreen and popups or menus are activated.
Intended behavior:
Single monitor setups: Panels are hidden only when a given fullscreen
window for a given monitor actually is the toplevel window for that
monitor.  If a popup is activate (like the Cinnamon menu via shortcut,)
the panels will show while that modal is active.  This prevents a
weird disembodied menu popping out of nowhere.  Further, if a non-
fullscreen window is alt-tabbed to, or otherwise made the focus, the
panels will also return until the fullscreen window is re-focused.
Multi-monitor setups: Same as single monitor, except for modal actor
behavior is different - only the panel(s) on the monitor which currently
hosts the last-added/current …
=> chrome: Improve visibility conditions for panels and other chrome w/fullscreen

files/usr/share/cinnamon/cinnamon-settings/cinnamon-online-accounts-info.ui
=> Use default icon names in Online Accounts (GOA)

data/theme/cinnamon.css
use border radius for progress
use border-radius dependent on top/right/left panel for window-list-box
grey progress (instead of red)
=> Cinnamon theme: window-list progress improvements

po/README
Provide a link to Launchpad, since I see potential contributors are often using GitHub as their starting point, and trying to submit translation corrections via GitHub rather than Launchpad.
=> Update po/README: provide a link to Launchpad

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py
This script runs as root and allows to configure e.g. other user's icon
files. These icon files are written to the respective user's $HOME/.face
location. If an unprivileged user prepares a symlink pointing to an
arbitrary location then this location will be overwritten with the icon
content. This vulnerability thus allows to corrupt the system or other
user's files. The content is not attacker controlled, luckily.
This change introduces temporary privilege drops to the target user's
privileges before attempting to write the respective .face files. This
way the kernel can decide if permissions are okay or not.
=> cinnamon-settings-users.py: fix symlink attack vulnerability

js/ui/popupMenu.js
`Cjs-Message: 03:25:55.954: JS WARNING: [/usr/share/cinnamon/js/ui/popupMenu.js 2048]: reference to undefined property "_delegate"`
=> popupMenu: Fix undefined _delegate property warning

.github/ISSUE_TEMPLATE.md
This will help improve our ability to figure out issues we can't readily reproduce. If a user is experiencing a problem and a developer can't reproduce it, seeing debug output is the next best thing.
Not sure what the most distro-agnostic way is to get Cinnamon's stdout without asking everybody to use cinnamon --replace, feedback is welcome.
=> Issue template: Start requesting logs

configure.ac, debian/control, debian/rules, docs/reference/cinnamon/Makefile.am, docs/reference/st/Makefile.am, files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py, js/ui/environment.js, src/Makefile.am, src/cinnamon-global.c, src/main.c, src/st/st-cogl-wrapper.h, src/st/st-polygon.c
Based on:
https://github.com/GNOME/gnome-shell/commit/af28a219be30490c1c50a9ed99c1e22e70a36826
This links the private Muffin versions of Clutter and Cogl into Cinnamon. Depends on https://github.com/linuxmint/muffin/pull/335.
=> Migrate to private Clutter and Cogl libraries

generate_cs_module_desktop_files.py
added traceback import to the top, main reason is py best practise, import on use is nice but if frequent is a  problem.
=> import change

js/misc/signalManager.js, js/ui/environment.js
- Moves duplicate code to _disconnect and _connect.
- Pulls _signalIsConnected and _disconnect out of the class because they
don't need class context, and the functions would be re-created for
every instance otherwise.
- Fully deprecates passing context to the constructor with a warning
since it creates circular references.
- Adds method `GObject.Object.prototype.is_finalized`.
=> signalManager: Migrate to ES2015 class, improve code readability

js/ui/tweener.js
Depends on #7868 
This moves the tween state from a property on the target to a global array of state objects, `tweenStateObjects`, and makes it so we don't have to access an object (usually MetaWindowActor) to get its state.
=> tweener: Fix invalid object access errors

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/systray@cinnamon.org/metadata.json, js/misc/util.js, js/ui/applet.js, js/ui/appletManager.js, js/ui/desklet.js, js/ui/deskletManager.js, js/ui/extension.js, js/ui/extensionSystem.js
Depends on #7868
- Adds an API that lets xlets know when they are being reloaded vs. just seeing that they are being unloaded and loaded. There were workarounds to figure out if the xlet was being reloaded from the xlet, but this is more precise.
- Used this API in the systray applet to move `Main.statusIconDispatcher.redisplay` from `onEnabledAppletsChanged` in appletManager to `on_applet_added_to_panel`. Since 3.8, extensions load asynchronously, but there was a side effect from that change causing the `redisplay` call to occur before the xlet was reloaded.
- Adds a small function to utils, `findIndex`, because it is a little [faster than native findIndex](http://jsben.ch/ABI1C) with Spidermonkey.
- Uses `is_finalized` from #7868 to prevent invalid object access.
- Cleans up various …
=> systray: Fix invalid access errors, implement a reloading API for xlets

js/ui/dnd.js, js/ui/tweener.js
This also corrects the invalid object access fix for tweener, we should be calling `is_finalized` on `state.actor` instead of `target`.
=> DND, tweener: Fix invalid object access errors

js/ui/environment.js, js/ui/expoThumbnail.js, js/ui/messageTray.js, js/ui/tooltips.js
This should prevent us from having to guard `destroy` on every possible code path that redundantly destroys objects, or where objects are destroyed in JS when they have already been destroyed in C code.
=> environment: Override Clutter.Actor.prototype.destroy and add is_finalized check

utils/cinnamon-stap-monitor/cinnamon-stap-monitor.py
% is used to cast objects, %s to string etc. now, if int or float, the corresponding formatting (like %d) should be used instead of converting via str() then passing via  %s (double job as the purpose of formatting is precisely to allow even numbers)
now .format() is supported since py2.7 . it is more flexible and less dense
=> string formatting - line 112

js/ui/applet.js, js/ui/desklet.js, js/ui/popupMenu.js
This updates some of the Cinnamon APIs to the newer class syntax. Since third party xlets have not switched to class syntax yet, there is a tricky part to it, so it looks different than the approach in #7389. 
When updating function constructors in the middle of the prototype chain, we have to account for child classes (xlets) still using function constructors calling `_init` directly. This wasn't a problem for the Cinnamon xlet refactoring because they're at the end of the prototype chain, and don't need to worry about other classes calling their `_init` methods. As a result, `_init` needs to be maintained as the constructor function for all APIs. Only the root class at the beginning of the prototype chain needs to have an actual constructor for initializing the instance.
=> applet, desklet, popupMenu: Migrate to class syntax

files/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js
Replaced old gvfs command by th new gio command on trash applet since the command got removed in gvfs 1.37 and cause an `command not found` after pressing `Empty trash` button of trash applet.
```bash
gvfs-trash --empty
gio trash --empty
```
https://gitlab.gnome.org/GNOME/gvfs/blob/1.38.0/NEWS#L36
https://gitlab.gnome.org/GNOME/gvfs/commit/6d711c07cbd00768c6b2b468f3100f02afc58f6f
=> Applet: Replaced gvfs command by gio on trash applet

js/ui/hotCorner.js
Only block the click after an enter event to avoid launching the action twice if the user both hovered and clicked the corner actor at the same time.
This fixes a bug where you could open (in a broken state) the overview from the workspaces view and viceversa by clicking the corner.
=> Hot corners: don't block a click after another click

js/ui/hotCorner.js
Otherwise some ripples may not show if activated while the old animation is running.
=> Hot corner: remove ripple tween before animating

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This prevents access-after-dispose warnings and possibly segfaults,
though I didn't observe any crashes.
Also includes a few minor cleanups.
=> window-list: don't try to destroy clutter clone multiple times

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
The getter is async but is treated as sync, so players that don't support seeking always showed the control unless they were in the hardcoded array.
For example _Gradio_. It doesn't support seeking but had the seeker.
=> Sound applet: fix seeking not detected for not hardcoded players

js/misc/params.js
If `params` is `null`, than we can to avoid `for loop` and just return `default`. Result is same.
=> Optimize parse params. Return defaults if params not defined

js/ui/runDialog.js
Fix for issue #7461 
Before the user could have the dialog window open and pressing the "Win" key would result in no longer being able to close out the "Alt+F2" dialog window. Added logic that now takes into the account the "Win" key being pressed and closes out the "Alt+F2" dialog window accordingly.
=> Fix 'Win' button issues in 'Alt + F2' dialog

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Full-opacity icons don't match greyed out labels.
=> Menu applet: add support for theming opacity to greyed category icons

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
`_listApplications` was changed to return an array in #7395, but this was only handled in `_doSearch`.
=> menu: Fix application items not rendering

js/ui/panel.js
Hi,
This simple modification delete error messages in .xsession-errors like:
`Cjs-Message: 11:39:25.446: JS WARNING: [/usr/share/cinnamon/js/ui/panel.js 2429]: reference to undefined property "_focusWindow"`
Best regards.
Claudiux
=> js/ui/panel.js - Delete annoying message in .xsession-errors

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
* Exposes a SettingsWidget() in Preferred Applications to control the default calculator application schema defined in commit [5b9ca20](https://github.com/linuxmint/cinnamon-desktop/commit/5b9ca2075dcfa9a23bdc9542cac90e6fc7252086) for [linuxmint/cinnamon-desktop](https://github.com/linuxmint/cinnamon-desktop)
* In order to function properly, this PR is dependent on the merger of commit 5b9ca20 into [linuxmint/cinnamon-desktop:master](https://github.com/linuxmint/cinnamon-desktop/tree/master) to define the schema, as well as the merger of commit [c84fa48](https://github.com/linuxmint/cinnamon-settings-daemon/commit/c84fa482bf392430fba6b89d3efb7f4b19cf1386) into [linuxmint/cinnamon-settings-daemon:master](https://github.com/linuxmint/cinnamon-settings-daemon/tree/master) to honor the schema …
=> cs_default.py: Add a SettingsWidget() for a default calculator application

js/ui/appSwitcher/appSwitcher.js
Use wm's methods to switch workspaces instead of duplicating code.
That caused the "don't cycle through workspaces" setting to be ignored.
Fixes #7955
=> Alt-TAB: Don't bypass workspace switching restrictions

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Let the theme define both horizontal and vertical paddings.
This means more easy theming and less calculations.
Themes don't have to do anything because, although it was ignored, most of them already defined the vertical padding they wanted, Mint-Y being one of the exceptions.
=> Menu applet: don't hardcode favorites button padding

src/st/st-polygon.c, src/st/st-polygon.h
This was caused by an [API update](https://github.com/linuxmint/Cinnamon/commit/f891384cdfd544fe65ea778823ed26cb46f240e4#diff-49572b95ade43576dc999b552d001660R236) when switching to Muffin's own private version of Cogl, and can be seen when moving the cursor over categories in the menu.
This also removes some unused properties of the private struct, and cairo headers.
=> st-polygon: Fix memory leak during picking

js/ui/panel.js
`_onPanelZoneIconSizesChanged` was originally written to only account for the panel-zone-icon-sizes gsetting, so we need to let the function differentiate between them.
=> panel: Preserve logic to only emit icon-size-changed on actual change while exempting symbolic changes

files/usr/share/cinnamon/applets/separator@cinnamon.org/applet.js
Add a vertical style class to the base actor. Also remove some hard coded
things that only exist when the separator is in a vertical panel. Not sure
why this was there.
=> applet-separator: Better support vertical panels

js/ui/cinnamonDBus.js
```
(cinnamon:4616): Cjs-WARNING **: 22:43:21.150: JS ERROR: Exception in method call: updateSetting: TypeError: Main.settingsManager.uuids[uuid][instance_id] is undefined
CinnamonDBus.prototype.updateSetting@/usr/share/cinnamon/js/ui/cinnamonDBus.js:354:9
_handleMethodCall@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:256:22
_wrapJSObject/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:326:16
```
=> cinnamonDBus: Handle stale xlet settings

files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py
so they don't spam the logs every time the program is run.
```
$ cinnamon-looking-glass 
/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py:21: DeprecationWarning: Importing dbus.glib to use the GLib main loop with dbus-python is deprecated.
Instead, use this sequence:
from dbus.mainloop.glib import DBusGMainLoop
DBusGMainLoop(set_as_default=True)
import dbus, dbus.service, dbus.glib
/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py:280: PyGIDeprecationWarning: GObject.SIGNAL_RUN_FIRST is deprecated; use GObject.SignalFlags.RUN_FIRST instead
"close-clicked": (GObject.SIGNAL_RUN_FIRST, GObject.TYPE_NONE, ()),
/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py:345: PyGTKDeprecationWarning: Using positional arguments with the GObject …
```
=> melange: clean up a bunch of deprecation warnings

files/usr/share/cinnamon/cinnamon-looking-glass/page_inspect.py, files/usr/share/cinnamon/cinnamon-looking-glass/page_results.py, files/usr/share/cinnamon/cinnamon-looking-glass/pageutils.py, js/ui/lookingGlass.js
Reworks object parsing code so that we can inspect more types,
present the information more clearly, and prevent misbehavior
with types we shouldn't iterate like importers.
Notable behavior changes:
- Boxed instance proxies such as Clutter.Color, Clutter.Rect, etc
are now inspectable like other objects.
- Inspecting importers no longer loads every file.
- Errors during command eval() are now inspectable.
- Values are currently truncated at 120 characters. When an
inspectable object's toString value is longer you will need
to manually call toString() on it to view the full value.
Strings are viewable in a popup dialog.
- The 'shortValue' key in the Inspect dbus method is no longer
used as it is not available on all of the methods, and so
easier to deal shortening values on the Melange …
=> melange/lookingGlass: better object inspection

data/theme/cinnamon.css
As the thumbnails container is already a menu, themes are already styling it, so no need to duplicate the menu background, which themes have to revert. That is totally unnecessary.
The class can be kept though, in case any theme wants to do anything special.
=> gwl: Remove unnecesary styles that make themes look bad by default

src/st/st-theme-node-drawing.c
The old unpremultiply function was out of range in some cases, like light colors with low opacity, resulting in an overflow and incorrect border colors.
For example:
```
border-color: rgba(250, 250, 250, .1)
background-color: transparent
In unpremultiply:
fr = (r * 255 + 127) / a = 260 > 255
where r = 250 * 0.1 = 25
a = 255 * 0.1 = 25
Result:
rgb = 260 & 255 = 4
border-color: rgba(4, 4, 4, .1)
```
A visible example of what this fixes is the "empty gap" under hovered window list items when using the Mint-Y theme.
Here is a visual comparison of the old function (red) vs the new one (green) with an alpha value of 8. Notice how the old function exceeded the maximum 255 and it wasn't 0 with a component value of 0.
This is the excess of a white color in function of alpha (the resulting color is …
=> st-theme-node: Fix border color blending

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-excellent-secure-symbolic.svg, files/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-good-secure-symbolic.svg, files/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-none-secure-symbolic.svg, files/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-ok-secure-symbolic.svg, files/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-weak-secure-symbolic.svg
The network applet shows a lock icon besides the wireless signal icon.
Use the new network-wireless-signal-secure icon instead.
Also add fallback icons (Adwaita style) for icon themes, which don't have this icons.
Mint-Y already has those new icons.
The fallback icons are used now in Cinnamon 4.0.1, because @mtwebster fixed the fallback icons issue: https://github.com/linuxmint/Cinnamon/commit/ffc4c9565e2dadde507eb89c7d8efb55ef0d139e
=> network-applet: use new network-wireless-signal-secure icons
