files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
I found an issue with places while working on removing the vector box and using only mouse. This just makes the hover and leave event callback code match the other category buttons.
It can be triggered on master by moving the mouse into the categories box and then using up/down keys to move to the places button. Once there, moving the mouse should cause two categories to be selected.
Second commit cleans up some unnecessary Lang.bind()s that I came across in forEach() callbacks and converts all to arrow functions for shorter code.
=> menu applet places hover fixup/forEach cleanup

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
right now the icons look pretty squashed, especially with small icon
sizes
=> systray-applet: more spacing between icons

src/st/st-texture-cache.c
Based on:
https://github.com/gnome/gnome-shell/commit/2c617e5a3a7226201a551c205493ac7d92a98cab
https://github.com/gnome/gnome-shell/commit/1f03599d1cf888f73a33363212b99905064e2c9e
https://gitlab.gnome.org/GNOME/gnome-shell/issues/210
=> st-texture-cache: Don't add NULL textures to cache

js/ui/panel.js
These three menu items were the only ones that triggered a
non-animating close.
=> panel.js: be more consistent about closing menu

js/ui/popupMenu.js
We update the position on allocate() but skip this if we're tweening.
Updating it here ensures it's correct before we start animating,
and setting a fixed size should keep it from automatically resizing.
master:
this branch:
=> PopupMenu: update position and fix size before tweening out

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
in HiDPI.  checked out with Tomboy and Redshift
=> systray: stop indicator icons coming up oversize

data/org.cinnamon.gschema.xml.in, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py, js/ui/panel.js
This is a bit simpler for the user, and we also place the setting for it in panel
settings, since icon sizes are there already.
top is existing new layout, bottom is with this change in effect at default value:
=> panel/theme: Use just a single relative percentage for sizing symbolic icons.

js/ui/popupMenu.js
This was added for menus that use column widths a long time ago, and the only xlet needing this is Cinnamenu, which has no side-effects from the removal.
=> popupMenu: Avoid unnecessary relayouts

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, js/ui/popupMenu.js
This makes it so hovering over an app button doesn't immediately give the opening thumbnail menu exclusive input focus. Until the user decides to interact with the menu, we should assume they are typing in another window.
When a menu is opened via Super + space toggling, it will always grab input.
In addition, other fixes in this PR includes:
- Button labels randomly showing the window title when the app title is set.
- Button labels not always showing the focused window label when the fourth option is set.
- Focus style on app buttons not showing when the applet first loads.
- Incorrect key navigation on vertical thumbnail menus when the panel is oriented horizontally.
=> gwl: Improve thumbnail menu input and button label handling

js/ui/appletManager.js
This is called by applets, from a menu item typically. This makes
sure the menu has enough time to animate properly instead of the
applet being removed while it's still in the menu item handler.
Fixes incorrect menu animation on remove applet from panel since
2cfff16c8c93b7063e21aa40e83ff3b9eaac14de
=> AppletManager: perform _removeAppletFromPanel on idle

js/misc/util.js, tests/unit/url.js
Cherry-picked from https://github.com/gnome/gnome-shell/commit/5cc42b18b0e6ced675af446d0d38fd3a354a25f9
Closes #8078
=> utils: Simplify URL regex to only support one layer of parentheses

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
Tested this with a variety of panel/icon sizes, third party themes, and high DPI - should work consistently.
Before:
After:
=> gwl: Fix icon alignment in left oriented panels

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
This should work without any additional translations because `Remove '%s'` is translated in the panel launchers applet.
C/O @itzexor
=> gwl: Translate preferences context menu item

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
The top level applet actor will grab input on hover, and ungrab if the CTRL modifier isn't held. This way it won't conflict with the intent of #8057.
=> gwl: Open new windows by holding ctrl and left clicking

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json
Un-pinned apps can still be re-arranged, but they need to be explicitly pinned from the context menu for their positions to persist.
Also fixes duplicate thumbnails appearing on init in the vertical menu orientation.
Closes https://github.com/linuxmint/mint-19.1-beta/issues/9
=> gwl: Always persist pinned apps' positioning after drag, fix duplicate thumbnails on init in vertical menu orientation

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Menu is broken, i.e. unfocused `All apps` and unfocused searchbar, when
the option `Open menu on hover` is enabled.
Fixes https://github.com/linuxmint/mint-19.1-beta/issues/15
Fixes https://github.com/linuxmint/Cinnamon/issues/8088
=> menu-applet: fix broken option `Open menu on hover`

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
This will use a timeout using the show apps timeout setting, and will be interrupted if the cursor enters the thumbnail menu.
It also fixes an issue with queued thumbnails not being processed if the thumbnail menu opens from any other method than a mouse event.
Closes https://github.com/linuxmint/mint-19.1-beta/issues/32
=> gwl: Fix the thumbnail menu not closing when using Super + # keys

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Caused by https://github.com/linuxmint/muffin/pull/391 - this is the only xlet using MetaScreen's window-added signal that's affected.
Closes https://github.com/linuxmint/muffin/issues/393
=> window-list: Fix icons not appearing for some apps

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
This can be confusing since the icon may not reflect the currently focused window.
=> gwl: Only use notify::icon signal for un-grouped apps

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
This provides a way to drag files to windows when there are multiple windows in an app group. Clutter does not propagate events when files are dragged, but through polling and stage calls, we can get enough info to figure out which thumbnail actor is hovered over.
Closes https://github.com/linuxmint/mint-19.1-beta/issues/23
=> gwl: Add support for dragging files to windows from the thumbnail menu

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
- Fixes the thumbnail not showing for the first app group instance.
- Fixes multiple buttons of the same pinned app persisting in the panel after their window is closed, when Cinnamon is restarted and multiple windows from the same app are open.
- Fixes incorrect thumbnail menu positioning when windows are added or removed while button labels are enabled.
Closes #8119 
Closes https://github.com/linuxmint/mint-19.1-beta/issues/44
=> gwl: Fix a couple ungrouped mode bugs, fix thumbnail menu positioning on window add/remove

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
- Prevents showing already visible labels, and sets `lastFocused` to `null` in the group's state when the last window from the group is closed.
- `titleDisplay` mode 4 - Ignores skip-taskbar windows when handling the focused window's label, otherwise it will cause the label to be shown just before its hidden, but with no window title because we don't have the skip-taskbar window in the index.
Tested all label options. 
Fixes https://blog.linuxmint.com/?p=3661#comment-146711
=> gwl: Fix incorrect app group button widths on close with labels enabled

data/theme/cinnamon.css
Fixes https://github.com/linuxmint/Cinnamon/issues/8111
Also see https://github.com/linuxmint/mint-themes/pull/175
=> Stock theme - fix expo workspace entry not expanding to fit scaled fonts

js/ui/popupMenu.js
Prevents a segfault occurring in Clutter when pressing left on a sub-menu item.
C/O @Cobinja
=> PopupSubMenu: Set sourceActor active before closing menu

src/st/st-private.c
https://github.com/GNOME/gnome-shell/commit/d1c71fd00d82b517da439a36ce86ca403c645fa2#diff-b948bb195b709c61ce7275142a2fbdfd
This stops an error warning I see frequently
=> st-private: Don't try to create shadow for empty texture

js/ui/indicatorManager.js
- Uses arrays instead of objects for storing collections.
- Uses SignalManager instead of its own signal manager.
- Uses class syntax.
- Uses faster for-loop wrapped array methods from misc/util.
- Cleans up object references when an instance is destroyed.
- Corrects some grammatical errors in comments.
=> IndicatorManager: Clean up

js/perf/core.js
This uses a proxy to intercept and time function invocations within a given object.
Example usage in GWL:
```js
imports.perf.core.benchmarkPrototype(AppGroup, 4);
```
Output:
```
Cjs-Message: 09:28:03.887: JS LOG: [LookingGlass/info] AppGroup.onFocusChange: 6ms (MAX: 26ms AVG: 5.63ms)
Cjs-Message: 09:28:03.887: JS LOG: [LookingGlass/info] AppGroup.onFocusWindowChange: 6ms (MAX: 26ms AVG: 5.63ms)
Cjs-Message: 09:28:03.890: JS LOG: [LookingGlass/info] AppGroup.onFocusChange: 4ms (MAX: 26ms AVG: 5.62ms)
Cjs-Message: 09:28:03.891: JS LOG: [LookingGlass/info] AppGroup.onFocusWindowChange: 4ms (MAX: 26ms AVG: 5.61ms)
Cjs-Message: 09:28:08.119: JS LOG: [LookingGlass/info] AppGroup.windowAdded: 30ms (MAX: 30ms AVG: 5.77ms)
Cjs-Message: 09:28:11.324: JS LOG: [LookingGlass/info] …
```
=> perf: Add a simple benchmark utility for prototype methods

js/misc/util.js, js/ui/main.js, js/ui/modalDialog.js, js/ui/runDialog.js
This replaces `trySpawnCommandLine` in the run dialog with `spawnCommandLineAsync`, and adjusts the code there to work with an asynchronous callback.
This also refactors `spawnCommandLineAsync` so it uses Gio.Subprocess, which allows us to receive stdout and stderr output while remaining asynchronous. The only xlet using spawnCommandLineAsync is multi-core-sys-monitor, and its using it in a compatible way. Not seeing any zombies left over from its usage on this branch.
Ref https://github.com/linuxmint/mint-19.1-beta/issues/52
=> Refactor spawnCommandLineAsync for stdout/stderr output

js/ui/main.js, src/cinnamon-recorder.c, src/cinnamon-recorder.h
Adapted from GNOME/gnome-shell@f5c058a
Closes #8156 
C/O @leigh123linux @brownsr 
This also fixes recording in multi-monitor setups.
=> recorder: Use clutter_stage_capture instead of cogl's read_pixels 

src/st/st-icon.c
https://github.com/GNOME/gnome-shell/commit/2ba26407f18e2520a87bbae58b29cf72fe9c6a26#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-icon: remove unused size values

src/st/st-texture-cache.c
https://github.com/GNOME/gnome-shell/commit/ca3f4cfb41851fec84a68fc334bef2e3e9a552bc#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-texture-cache: Use right event to detect file changes

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
Sets correct search column for interactive search.
Closes https://github.com/linuxmint/Cinnamon/issues/8152
=> cs_keyboard.py: Fix category search in layout tab

js/ui/cinnamonMountOperation.js
I refactored it to avoid unshift for array for performance reason.
=> [js] Use push instead of unshift for array

data/theme/cinnamon.css
Shows the different CSS used by full colour or symbolic icons, a non-obvious split that needs inspection of the code to find out otherwise.
=> Default theme: document css used by symbolic icons

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
- Fixes windows not being removed from all workspaces when "Show windows from all workspaces" is enabled.
- Fixes the 'insensitive' workspace option in the context menu not being based on the workspace the last focused window is actually on.
- Removes property assignment on the MetaWindow object - state props should stay localized to the applet.
- Fixes windows being removed from the active workspace when a window's
"Visible on all workspaces" option is toggled while "Show windows from all workspaces" is enabled.
- Fixes null MetaWindowActor TypeError in `AppMenuButtonRightClickMenu.prototype.populateMenu`.
Closes #8190 
Closes #8252
=> gwl: Fix incorrect window accounting in multi-workspace cases

files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
This pull request moves the setting "Minimum height of the favorites section (px)" so that it's now below the setting "Show favorites and session buttons". It also makes the favbox height setting dependent on the show favs setting since the former only makes sense when the latter is enabled.
=> Menu applet settings: move the favbox height setting

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py
```
Traceback (most recent call last):
File '/usr/share/cinnamon/cinnamon-settings/xlet-settings.py', line 500, in <module>
window = MainWindow(xlet_type, *sys.argv[2:])
File '/usr/share/cinnamon/cinnamon-settings/xlet-settings.py', line 96, in __init__
self.load_instances()
File '/usr/share/cinnamon/cinnamon-settings/xlet-settings.py', line 280, in load_instances
self.build_from_order(settings_map, info, instance_box, first_key)
File '/usr/share/cinnamon/cinnamon-settings/xlet-settings.py', line 378, in build_from_order
widget = globals()[XLET_SETTINGS_WIDGETS[settings_type]](key, info['settings'], item)
File '/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py', line 310, in __init__
self.attach()
File '/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py', line …
```
=> JsonSettingsWidgets: Fix TypeError

js/ui/runDialog.js
Fixes an issue with #8130. This was only closing the run dialog while an async process was still ongoing, but this would only be the case when using `pkexec`.
=> runDialog: Always close on loss of key focus

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
This moves the initial window load handling for pinned apps from `windowAdded` to `loadFavorites`, which allows removing some of the redundant logic. A side effect of this is the window icon will always load instead of the app icon, so that was changed in `setIcon` to only use the window icon for ungrouped apps.
=> gwl: Simplify AppList.prototype.windowAdded

src/st/st-theme-node.c
https://github.com/GNOME/gnome-shell/commit/2e1e00c3de747b9208fcd8fd6a1b713d99adc932#diff-b948bb195b709c61ce7275142a2fbdfd
=> st-theme-node: fix text shadow 'none' to correctly draw no shadow

src/st/st-drawing-area.c
Pipeline copy rather than new is preferred.  No measurable difference to performance unfortunately.
=> st-drawing-area: use pipeline_copy

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/recent@cinnamon.org/applet.js, js/misc/docInfo.js, js/ui/main.js, src/cinnamon-doc-system.c, src/cinnamon-doc-system.h
This PR simplifies DocSystem/DocInfo (which role is to handle the list of recent documents in Cinnamon), to optimize performance, memory usage and prevent memory leaks (by removing complicated code).
It:
- Removes a lot of unused code.
- Simplifies the listing of recent docs in the menu@cinnamon.org and recent@cinnamon.org applets.
- Makes everybody use the same unique instance of DocInfo.
- Frees recent objects which aren't used.
- Moves the limit of 20 recent items from JS to C (Gtk.RecentManager can't sort or clamp result, this is done in C in DocSystem.. it used to be sorted in C but clamped in JS before this PR).
- Remove the number of objects in memory (for instance recent applet no longer keeps a handle on recent objects, only their URI)
=> Simplify DocSystem/DocInfo

src/st/st-cogl-wrapper.c, src/st/st-theme-node-drawing.c, src/st/st-theme-node-transition.c, src/st/st-theme-node.c
I found a performance gain in Muffin in not fetching the CoglContext from Clutter except to get the initial pointer, and so it makes sense to also do it here. Clutter has to fetch its context in get_default_backend(), which causes it to place a lock on Clutter's context. Its an intricate dance when we just need something that's already available.
=> st-cogl-wrapper: Get context from Clutter once

src/st/st-drawing-area.c
Even though `drawing_pipeline_template` is static and the `G_UNLIKELY` macro is supposed to "hint" to the compiler that it shouldn't occur often, its still an extra check that can be avoided.
=> st-drawing-area: Call cogl_pipeline_new when needed

js/ui/main.js, js/ui/windowAttentionHandler.js, src/cinnamon-app.c, src/cinnamon-window-tracker.c
- Use meta_window_is_interesting
The main benefit to this is it can be slightly more efficient when using pointers in muffin, and easier access on the prototype in JS.
- app: Close all closable windows from quit() 
> There's no relation between a window being hidden from overview/taskbars
and a window not being closable - currently we effectively disable the
fallback quit action for any application with open transients, which
simply doesn't make sense.
> Instead, only exclude windows for which the close action has been
explicitly disabled.
Requires https://github.com/linuxmint/muffin/pull/418
=> appsys: a couple changes for more optimal muffin usage

src/cinnamon-app.c
In https://github.com/linuxmint/muffin/pull/399 icons are no longer created for every window because Cinnamon does this most of the time. For window backed apps however, Cinnamon needs to fallback to Muffin's icon. Instead of creating a Muffin icon for every window, this will create them as needed, or in this case, when we have a non-Xapp window-backed app.
=> cinnamon-app: Get a fallback icon from Muffin for some window-backed apps

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This changes the `notify::icon` signals to `icon-changed`, which depends on https://github.com/linuxmint/muffin/pull/399. This was merged into this PR to avoid a conflict.
=> gwl: Use icon-changed signal for Muffin #399

src/cinnamon-app.c, src/st/st-texture-cache.c, src/st/st-texture-cache.h
Since the pixmap is cached in muffin, and icon-changed receivers destroy their icons on emission, there's no need for a complex caching solution dedicated to window-backed app icons.
Requires https://github.com/linuxmint/muffin/pull/422
=> cinnamon-app: Simplify icon retrieval for window-backed apps

files/usr/share/cinnamon/cinnamon-settings/modules/cs_effects.py, js/ui/main.js, js/ui/overview.js, js/ui/windowEffects.js, js/ui/windowManager.js, js/ui/workspace.js
- Caches settings so we are not invoking Gio.Settings calls on every window action.
- Removes assignment of window_type via a signal.
- Reduces function invocation.
- Switches WindowManager and the effects classes to ES2015 class syntax.
- Removes circular references to WindowManager on the effects instances.
- Uses object destructuring assignment for imports so we are not accessing properties on large objects as much.
- Makes OSD elements not animate when animations are disabled. This could be turned into its own effects option if needed, though not sure it's necessary.
- Moves the main desktop effects setting to Muffin, so we can disable some unnecessary code paths from Muffin when effects are disabled.
Depends on https://github.com/linuxmint/muffin/pull/428
This area of Cinnamon …
=> windowManager: Cache settings, various clean up

debian/control, files/usr/bin/cinnamon-file-dialog, files/usr/bin/cinnamon-killer-daemon, files/usr/bin/cinnamon-launcher, files/usr/bin/cinnamon-menu-editor, files/usr/bin/cinnamon-preview-gtk-theme, files/usr/bin/cinnamon-subprocess-wrapper, files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py, files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py, files/usr/share/cinnamon/cinnamon-screensaver-lock-dialog/cinnamon-screensaver-lock-dialog.py, files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py, files/usr/share/cinnamon/cinnamon-slideshow/cinnamon-slideshow.py
This makes all of our standard python programs set an easier to
identify name in the process list. Build/translation utils were
not included.
=> all/python: use setproctitle

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
The style class was not being set, leading to the need for a subsequent workaround.  This change uses the function in the popup menu code designed to set a specific style class on a popup menu, and so means the intended dedicated CSS is now applied.
=> gwl: apply style class to the thumbnail menu

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Fixes:
```
(cinnamon:1011): Cjs-WARNING **: 20:59:35.685: JS ERROR: TypeError: metaWindow.get_compositor_private(...) is null
_onWindowMonitorChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1099:14
```
=> window-list: Fix MetaWindowActor TypeError

files/usr/share/cinnamon/applets/slideshow@cinnamon.org/applet.js
I've added an item in the popup menu to show the current file name.
This is quite useful when you have a big set of wallpaper, and you want to know which one is displayed.
It's updated when menu opens, so it stays up to date when:
- users change the wallpaper by hitting "Next"
- wallpaper is changed automatically
I don't know yet how to provide the translation for `Current background:`, advises are welcome!
=> Slideshow applet: Show current file name in popupmenu

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/misc/windowUtils.js, js/ui/appSwitcher/appSwitcher3D.js
This adds compatibility for [this commit](https://github.com/linuxmint/muffin/pull/410/commits/5d3361b45a35583af6e0f50722d6aa48de8b2991) in https://github.com/linuxmint/muffin/pull/410.
The muffin patch works by skipping rendering of unminimized windows the user cannot see, so system resources are spent on the windows being interacted with. One part of this is making sure this doesn't break live thumbnail previews, which this PR addresses.
=> Add compatibility for the obscured window optimization in Muffin

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
This fixes a bug in which disabling an applet with a uuid that is a sub-string of another uuid will cause both to be disabled. For example, disabling window-list@cinnamon.org will incorrectly cause any instances of grouped-window-list@cinnamon.org to also be removed.
Fixes #8282
=> Spices.py: fix a bug causing gwl to be removed when wl is disabled

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This seems to work great on my end, but it may break stuff so it needs testing.
- buttons significantly faster by not using PopupBaseMenuItem
- buttons all have a 'name' and 'description' property to simplify enter/leave events
- removed some classes that just added an icon or label
- combined all enter/leave events to a single handler to consolidate all the code into one location and reduce the amount of duplicated code
- the applications box now uses only one context menu item. this is how recent buttons already worked, but there was 1 menu per application button and on my system it was about 110 menu item actors
- scrollToButton() now resets vscroll adjustment to 0 when no button is passed. avoids passing first item and having it calculate when we just want to scroll to the top.
- a …
=> Menu applet: Various improvements

js/ui/deskletManager.js, js/ui/layout.js, js/ui/magnifier.js, js/ui/main.js, js/ui/notificationDaemon.js
Simple profiling with the GJS/CJS profiler revealed:
1. paths being called relatively frequently when the features they support weren't enabled:
-magnifier cursor update
-desklet mouse tracker
2. window restack connections are always a top consumer on general non-cinnamon-ui usage
3. <s>uiGroup is always allocating, and the allocate does nothing beyond default</s>
4. notification daemon is always checking the WindowTracker to clear notifications, even when there are none
=> General optimizations

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json, files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
This improves how data is displayed in the tree of an xlet settings list widget in several ways:
1.) Boolean values are now displayed as a checkbox rather than the values TRUE and FALSE.
2.) Icon type values are now displayed as an icon rather than text.
3.) Columns with a key-value options list now display the key rather than the value. In most cases this makes more sense and it brings it more in line with the combo box widget which is used in the add/edit dialog.
4.) A new property 'align' was added to allow the alignment of the content to be controlled. The settings example applet and the docs were updated to reflect this change.
Fixes #8009
=> xlet settings list widget: some fixes and improvements to the tree

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
This adds an option to the sound chooser widget to use any sound file type - not just ogg/oga and wav (which are the ones supported by the cinnamon sound system). The settings reference tutorial is also updated to reflect the new option.
The default path for the file chooser dialog in this widget was also set to /usr/share/sounds for cases where the file is not set or doesn't exist as this is a much better default than ~/.
Fixes #8267
=> sound chooser widget: add all mimetypes option and improve default

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
According to #6265, adds a tooltip explaining the three window focus modes.
_I'm absolutely new to contributing to Cinnamon, but I hope this helped._
=> Add tooltip to window focus behaviour

src/st/st-icon.c, src/st/st-label.c
The allocation will only ever change inside the allocation vfunc. Caching some of this can avoid some unnecessary computations and redraws.
=> st: Move allocation calls out of paint vfuncs

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
This was broken by #8309 which fixed an issue with applets but the fix didn't consider that desklets and extensions use a slightly different format for the gsettings key. This pr adds handling for all extension types.
=> Spices.py: fix disabling of desklets and extensions

js/ui/layout.js
This is only needed if either #8465 or #8467 don't get merged. I just want to make sure the typo is fixed. If either is merged then this can be closed.
This should've been changed to `Window` from `Menu`. Thanks to @jaszhix for noticing.
=> layout.js: fix typo

src/cinnamon-doc-system.c, src/cinnamon-doc-system.h
slists and glists were mixed up, there was a compile warning with the macro,
and I took the opportunity to put in the normal prepend/reverse trick
=> cinnamon-doc-system: tidyup of recents

src/st/st-texture-cache.c
difficult to test not knowing how many sliced images are flying around.  A batch of menu load tests came up around 20ms faster afterwards on average, though with high variability in the test results both before and after so I might be kidding myself.  No regressions in evidence, not that I would expect that as this is a well tried approach.  https://developer.gnome.org/glib/stable/glib-Doubly-Linked-Lists.html#g-list-append
=> st-texture-cache: use a slightly more efficient linked list method

files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py
The Image.VERSION variable was deprecated some time ago and is now gone entirely. But its only use was to determine whether we were using at least the latest version of PIL, or any version of its fork, Pillow. And PIL was last developed in 2009 and does not support python3 at all, so we are guaranteed to be using Pillow.
Moreover, the check does not really matter, as Pillow is guaranteed to load any image it opens, without the user doing so manually.
Fixes #8495
=> PIL: remove unnnecessary version check and code fork

src/cinnamon-doc-system.c, src/cinnamon-doc-system.h
GSList usage seems to perform better in CinnamonDocSystem. This switches back to it while preserving the warning reductions with appropriate casting, and the prepend + reverse trick. Not seeing any GCC warnings from cinnamon-doc-system.c.
Measurements:
https://openbenchmarking.org/result/1904086-SP-APRIL848805&obr_sor=y
=> cinnamon-doc-system: Switch back to GSList

js/misc/util.js, js/ui/overrides.js
This is an optimization intended for V8, but it [also works on Spidermonkey](http://jsben.ch/1DVog). It modifies the properties of GObject instances so the engine uses its optimized path for property access. [More info](https://stackoverflow.com/questions/24987896/how-does-bluebirds-util-tofastproperties-function-make-an-objects-properties).
I got the idea to use this when I was trying to optimize #8068 and to address a performance regression with [CJS built with mozjs60](https://github.com/linuxmint/cjs/pull/70). In any case, it has a noticeable performance improvement for me, most notably with the responsiveness of electron apps like VSCode.
=> Improve property access performance

src/cinnamon-app.c, src/cinnamon-global-private.h, src/cinnamon-global.c, src/cinnamon-window-tracker.c
This moves the CinnamonGlobal struct to its private header file so its properties can be directly accessed within C code. Public functions are for bindings and consumer contexts, so let's trust GCC a little less and make sure these non-static functions are not incurring a performance penalty.
=> Reduce public function invocation in C code for simple getters with no logic

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, js/misc/util.js, js/ui/windowEffects.js, js/ui/windowManager.js
96f62eb54e99f87d5bf970677178b897f5f4e425
This solves some rendering issues with effects after the last few rounds of muffin changes. By separating effects from MetaWindowActor, we can call expensive custom Clutter vfuncs less, and have more compositional control over the end result without worrying about breaking the compositor.
Ref #8454 
**Depends on** https://github.com/linuxmint/muffin/pull/464
=>  wm: Apply window effects to clones

js/ui/layout.js, js/ui/panel.js, js/ui/popupMenu.js, src/cinnamon-global-private.h, src/cinnamon-global.c
- A couple fixes for #8351
- Lower priority of `global.sync_pointer`
- Fix usage of undefined property `this._isPopupMenuVisible`, which caused `wantsInputRegion` to always be true.
- Removes all usage of Lang.bind with [arrow functions used instead](https://jsperf.com/bind-vs-arrow-function).
- `global.sync_pointer`: This is an old workaround needed so Clutter emits enter/leave events when a window grabs the pointer without our knowledge, but it calls heavy GDK methods that cause round trips. Even worse, the restacked signal is emitted a few times per second on my machine. That is a muffin bug, but until it's fixed we can't afford the latency incurred from pointer syncing (or at least I can't).
- Moves popup window visibility logic to muffin, which will be more efficient because it is …
=> layout: Misc. clean up

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.ui
When the back button is hidden the hack we used to center the stack switcher
stops it from being centered. Nowadays we have gtk_box_set_center_widget().
Use that instead so the stack switcher is always centered correctly.
=> cinnamon-settings-ui: Remove the hack to center the stack switcher

js/ui/layout.js
This fixes a regression of https://github.com/linuxmint/cinnamon/pull/8465/commits/654c7049d3efa8086e64e29d1eecc9e236a6db95 where input regions where not updated anymore when a window goes fullscreen.
=> Fix: update the input regions when going fullscreen

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
This converts everything except the desktop settings to the new style used
in python-xapps. The desktop settings have to be adjusted in Nemo. A few
changes in spacing were made to make this work better in cinnamon settings.
=> SettingsWidgets: Convert to use the new style used in xapps

js/ui/windowEffects.js, js/ui/windowManager.js
It appears MetaWindowActor is being disposed during the effect because once switched over to applying the effect directly, we need a finalized check in `Effect.prototype._end`. This is breaking Clutter's ability to opacify the clone for some reason. We can apply the effect directly as a fix since there weren't any issues observed with the close effect in particular.
Depends on https://github.com/linuxmint/muffin/pull/508
=> windowEffects: Fix opacity during the close effect, stacking during the minimize effect

js/ui/workspace.js
This is happening because windows are not always eligible to paint a texture after they're initialized. They are lazy loaded, and this does not impact normal window operation. When the obscured optimization in Muffin is disabled via `meta_window_actor_set_obscured`, a redraw is already being queued. The thumbnail clones work without issue everywhere else, so I'm suspecting  it has something to do with this abstracted `WindowClone` class that is preventing MetaWindowActor redraws.
Ref https://github.com/linuxmint/cinnamon/issues/8454#issuecomment-496640069
=> overview: Fix some thumbnails not appearing

src/st/st-label.c, src/st/st-private.h, src/st/st-widget.c
This is basically a redo of 37d75d48e4f0214e498dd559ee257946ad3fed6f, which didn't work because the size didn't propagate until the next redraw.
Ref https://github.com/linuxmint/cinnamon/issues/8454#issuecomment-493608833
=> st-label: Move St-specific shadow processing out of the paint vfunc

js/ui/layout.js
This fixes an input region issue when some desklets are lowered below the window group.
=> layoutManager: Always update regions when untracking an actor

.gitignore
This also ignores the .vscode directory, which stores some binaries needed for intellisense to work in C files. Otherwise autotools deletes them and header includes will be reset.
=> git ignore auto-generated files

.github/ISSUE_TEMPLATE.md
There are a lot of issues indicating Cinnamon 4.0 usage, but it's not clear if this is the maintenance release or master via the PPA.
=> Issue template: Request info about daily builds PPA usage

js/ui/main.js
This replace the default workspace name with one that isn't ALL CAPS. Nowhere else in the DE interface really uses all caps and its less pleasing to the eye
=> Remove All Caps from default workspace naming

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py
A security hole was fixed in #7683, where a user's .face file being
modified with root privileges allowed a symlink attack to overwrite
root-owned data.
Unfortunately, this fix is incomplete - simply dropping privileges
means that users who previously had an older .face file would be
unable to overwrite it. The old code left .face owned by root.
This fix first removes the old .face file as root, then drops
privileges and writes the new .face file.
This bug is explained further in #8298
=> cinnamon-settings-users.py: update symlink vulnerability fix

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
The problem was revealed in the issue https://github.com/linuxmint/cinnamon-spices-applets/issues/2216.
The metadata.json file of some xlets installed for a long time contains a "last-edited" field enclosed in quotation marks. So, it's considered a string and not an integer.
The comparison of dates can not be done and the available update is not available for download by Cinnamon Settings [Applets|Desklets|Extensions].
This simple modification solves the problem.
=> Consider the "last-edited" field as integer even when enclosed in quotation marks.

js/ui/layout.js, js/ui/messageTray.js, js/ui/panel.js, js/ui/popupMenu.js, src/cinnamon-global-private.h, src/cinnamon-global.c
https://github.com/linuxmint/cinnamon/commit/74d14ea9cbb01849d46cda8673d668a6861e29b4 introduced regressions in tooltips and input regions.
- https://github.com/linuxmint/cinnamon/commit/bd6c1929e6985cea8158dabe7de1ccb4776f5ffc, https://github.com/linuxmint/cinnamon/commit/21ae0cde0b9dc908be2f0df94051150909f7210b and https://github.com/linuxmint/cinnamon/commit/08fa99ea5a8236fcf1879e1c95861ea4599abed4 fixed input regions regressions. It's likely they're all fixed now, but we can't be certain. 
- https://github.com/linuxmint/alpha-testing/issues/15 could be fixed by reverting just a portion of https://github.com/linuxmint/cinnamon/commit/74d14ea9cbb01849d46cda8673d668a6861e29b4 (the one which deals with mouse cursor queries) but this close to release it's probably better to pass on …
=> Revert layout.js optimizations

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
Since this has been implemented in cinnamon-settings-daemon, it should be enabled here too.
=> Use ConsoleKit instead of old upower for suspend/hibernate (cs_power.py)

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/settings-schema.json
The visual representation of the workspace switcher currently doesn't work well with a really small panel, so we've been suppressing it in that case. This simply adds a tooltip that explains this to the user so that they don't get confused or think there's a bug.
=> Workspace switcher applet settings: add tooltip with informative note

js/ui/applet.js, js/ui/desklet.js
This PR adds confirmation dialogs when trying to remove applets/desklets from their *Remove* context menu items. If the <kbd>Control</kbd> key is pressed when trying to remove an xlet, the xlet will be removed without confirmation.
- I added the confirmation dialog to the desklets and not just to the applets to keep the behaivor of both types of xlets somewhat homogeneous.
- I added the <kbd>Control</kbd> key behavior just to avoid a possible annoyance. If one wants to remove several xlets, one can simply press the <kbd>Control</kbd> key to remove the rest of the xlets and avoid the confirmation dialog.
=> Xlets removal confirmation dialogs

files/usr/share/cinnamon/cinnamon-dbus-command, js/ui/cinnamonDBus.js
```
mtwebster:~/bin/cinnamon/files/usr/share/cinnamon[cin-dbus-script]> ./cinnamon-dbus-command 
Provide a method name and any parameters.  Available commands are:
Eval --- script ('s') 
ScreenshotArea --- include_cursor ('b') --- x ('i') --- y ('i') --- width ('i') --- height ('i') --- flash ('b') --- filename ('s') 
ScreenshotWindow --- include_frame ('b') --- include_cursor ('b') --- flash ('b') --- filename ('s') 
Screenshot --- include_frame ('b') --- flash ('b') --- filename ('s') 
ShowOSD --- params ('a{sv}') 
FlashArea --- x ('i') --- y ('i') --- width ('i') --- height ('i') 
highlightXlet --- arg_0 ('s') --- arg_1 ('s') --- arg_2 ('b') 
highlightPanel --- arg_0 ('i') --- arg_1 ('b') 
addPanelQuery 
destroyDummyPanels 
activateCallback --- arg_0 ('s') --- arg_1 ('s') --- arg_2 …
```
=> Add a utility script for accessing cinnamon's dbus methods from a terminal

js/ui/hotCorner.js
Avoid executing unnecessary layout code.
=> Ripples: use St.Widget instead of St.BoxLayout

js/misc/windowUtils.js
This fixes #8304
The actual texture position was way down because of the minimizing animation,
but the input rect reports the correct position of the window.
=> Fix misplaced windows in overview

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, src/cinnamon-app-private.h, src/cinnamon-app-system.c, src/cinnamon-app.c, src/cinnamon-app.h
need to:
- ~~prettify exec or flatpak names (capitalize, strip paths)~~
- ~~handle OnlyShowIn/NotShowIn cases with identical executables (i.e. nautilus has two - one for gnome/unity, another for *not* gnome/unity.  Cinnamon-menus accepts both as valid for a cinnamon session.~~
- ~~implement a hardcoded list if necessary for corner cases~~
- optimize
=> Create unique names for desktop apps with duplicate display names.

js/misc/modemManager.js
Please test before merge if this goes into 4.2.  Seems fine to me, but I don't want to risk any connection issue creeping in just before a new Cinnamon version goes out.
=> modemManager: fix cjs warning

js/ui/panel.js
This makes the highlighted panel show for 1.5 seconds if it is autohidden when selected by panel or applet settings.
Also: Oops, accidentally hit enter and opened this as just `"` with no other info initially.
edit: the rework commit looks like more changes than it is in the unified diff. It just moves the panel edit mode or peeking check to the top, and skips calculating autohide (especially the intelligent mode) when either are true.
Fixes: https://github.com/linuxmint/cinnamon/issues/8616
=> "Peek" panel for 1.5 seconds when highlighted

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
This PR is related to this issue: https://github.com/linuxmint/Cinnamon/issues/7945
Currently, cinnamon-settings (applets,desklets,etc) is ignoring system-wide proxy settings.
This fix uses proxy settings (when available) to connect to spices hosts.
=> fix to use proxy settings when available on cinnamon-settings

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
- Darkens labels of empty workspaces in "simple buttons" mode. Workspaces with only minimized windows are considered "not empty"
This PR includes a workspace-button pseudoclass in cinnamon.css to define the darkened label. I'm not sure if this is acceptable for compatibility reasons, but I'm not sure of another way to accomplish this
=> Workspace switcher: shade labels of empty workspaces in simple button mode

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/power@cinnamon.org/settings-schema.json
This is my attempt at a fix for issue #4979 .
It also adds one new configuration setting for this applet, "Always show all batteries", as in some cases with multiple batteries one battery will report as primary regardless of intended use; this setting forces multiple battery behavior in that case.
=> power@cinnamon.org: improved support for multiple batteries

files/usr/bin/cinnamon-settings, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py, man/cinnamon-settings.1
Usage:
`/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py applets 1 2`
opens the Applets window of Cinnamon Settings directly on Download tab (tab 1) with list of applets sorted by date (sort type 2).
The _applets_ word can be replaced by _desklets_, _extensions_ or _themes_.
The first number corresponds to the tab to open (tab 0 by default); the second number corresponds to the type of sorting:
- 0: sorting by name;
- 1: sorting by popularity;
- 2: sorting by date;
- 3: installed first.
This PR was requested by @jaszhix in https://github.com/linuxmint/cinnamon-spices-applets/pull/2235#issuecomment-456601075.
These changes do not affect all other settings.
Best regards.
Claudiux
=> Cinnamon Settings: Adding capability to open specific tab and choose sort type

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
This is an alternative solution to https://github.com/linuxmint/cinnamon/pull/8668 for fixing https://github.com/linuxmint/cinnamon/issues/8662. It should work on all locales but I'm no localization expert. Please test.
> Currently all characters in a search string which can not be represented in the
> ASCII character set filtered from the search string. This happens to work for
> Latin based locales because the strings first get normalized to NFD, which
> represents e.g. 'é' as the base character 'e' followed by the combining
> character '´'. Only the combining characters get filtered and the base
> characters remain.
> 
> However, in locales, which do not use the Latin character set, the base
> characters get filtered as well and the search string ends up being empty.
> 
> Fix this by …
=> Cinnamon Settings: Fix search for locales with a non-Latin character set

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
fixes #8687 
The first commit is the fix, the second two strip out progressively more code that is not required with setStyleOptions gone.
=> grouped-window-list: setStyleOptions still getting called if labels on

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Audacious returns an invalid value for `MediaPlayer2.Player.Rate`, which should be set to the current playback speed rate or 1 if not supported.
This partially fixes the issue #8690.
=> sound applet: show seekbar for Audacious

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Should fix #8189.
The problem here is that there's a mix up between the device and device id objects. `newDevice` is actually the device id and `id` is actually the device but it's treated as the id. When comparing `id != getattr(self, type+"Id")` the comparison is of the device to an integer. This is always true, so the next statements are always executed, regardless of whether the device has changed. This causes the infinite recursion in the issue.
=> Sound settings: Fix setActiveDevice

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This doesn't actually work as is because it's just partially
recreating the menu, and leaves it in a broken state. As far
as I can tell we don't need to rebuild anything with it being
the same layout in every orientation.
This also removes the 'orientation' property because it already
exists on the prototype as '_orientation'. If we aren't modifying
it I don't see a reason to store it twice...
fixes: https://github.com/linuxmint/mint19.2-beta/issues/52
=> menu applet: only update label on orientation change

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
So we don't show the clear recents button with an empty list.
=> menu applet: if all recents are hidden act like there are none

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
A long-overdue follow-up to #3071. I consistently hit a problem where I have Python code running in a terminal in the background that pops up windows and steals focus. For a minimal example, I run this:
```
$ python -c "import time; time.sleep(1.); from matplotlib import pyplot as plt; plt.figure(); time.sleep(1.)"
```
then click away to some other program (vscode, a different terminal) and start typing.
So this PR:
1. Exposes the `org.cinnamon.desktop.wm.preferences:focus-new-windows` setting, which prevents this behavior when set to `strict`
2. Clarifies the wording of the old `"Prevent focus stealing"` to make it clear that it only deals with windows that request attention (not new windows)
New option in use:
cc @crobarcro this might help with #8059, might not. If it does not, I …
=> Update cs_windows.py: Add setting for new window focus

src/cinnamon-global.c
This partially reverts commit d592d54819c257fc77268f4c972bd9f738c53a96.
These functions had the correct return type before, only the param-
eter type was incorrect. Third time's a charm... Hopefully?
fixes: d592d54819c257fc77268f4c972bd9f738c53a96
=> Partially revert "cinnamon-global.c: fix repaint function signatures"

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_display.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py
Doing this so we can move the display related settings from General->Display
Just import the C module for now and put the new settings on their own
page
=> Add a display settings python module

utils/cin-debug-run
Remove space from single digit time; distinguish between 4 in the morning and 4 in the afternoon.
=> cin-debug: Fix time code

js/ui/messageTray.js, js/ui/notificationDaemon.js
The 'suppress-sound' parameter is defined in the freedesktop notifcation specification.
This is useful for informative notifications with less importance, like for example when a new song starts in a music player.
=> Notifications: add support for silent notifications

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Exetensions under `/usr/share/cinnamon/extensions/` didn't appear in the list of installed extensions. There was no way of loading, unloading or configuring them through the settings interface.
=> Enable management of system-wide extensions through the spices settings UI

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Reduce by half the number of "`there was a problem trying to read metadata.json`" warnings. Speed up loading.
=> Spices.py: don't try to load themes twice

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
=> cs_default.py: fix missing declaration causing crash when desc not found

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js, js/ui/statusIconDispatcher.js, src/cinnamon-tray-manager.c, src/cinnamon-tray-manager.h, src/main.c
(see xapp pr for details))
issues with this applet:
- currently doesn't drop its dbus name when removed from the panel (which interferes with XAppStatusIcons deciding on whether or not to use a GtkStatusIcon.
=> xapp-status applet: Update to utilize XAppStatusIconMonitor.

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
At the moment when the panel is shrunk down, this applet switches the graph view to buttons, at an arbitrary point, and the reason given in the code comment is that the graph view loses usefulness at a small size.  However the graph is actually visible and usable to some degree right down to the smallest panel size that can be set in panels of either orientation so there is no real reason to switch over to buttons. In some themes and panel orientations the buttons are less usable at a small panel size than the graph view, so this can actually cause a usability regression.  This has confused at least one user, who has raised an issue.  Removing the tests simplifies the code as well, so the sensible thing imo is to simply remove the switch to buttons at a small panel size.
fixes #8755
=> Workspace switcher : remove arbitrary cutover to buttons

js/ui/main.js
The dynamicWorkspaces functionality seems to have been disabled
since merge. Removes Lang import, and cleans up spacing warnings.
=> main.js: remove dead code and style cleanup

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
Hi,
Output strings for some hardware can be quite lengthy. For some screen resolution / font-size combinations this can result in a System Info window that exceeds the width of the screen - e.g. for this user with Font sizes set to 13 on a 1280 x 1024 screen - https://forums.linuxmint.com/viewtopic.php?p=1686784#p1686784
Allowing these labels to wrap should avoid this issue.
=> Allow line wrapping in System Info labels

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
I propose to add a sort by available update, for the Spices.
=> ExtensionCore.py: Add a sort by available update

files/usr/bin/cinnamon-launcher, js/ui/extension.js
A user might have installed broken extensions/applets/etc that make cinnamon fail to start. At the moment the `cinnamon-launcher` falls back to starting a fallback panel, but the registered three fallback panels might not be installed, which would leave the user with an empty desktop without any feedback.
In case starting cinnamon fails, a dialog is shown that allows to restart cinnamon. A checkbutton is added that allows disabling applets/extensions etc from user's home directory. If the checkbutton is checked, the env var CINNAMON_TROUBLESHOOT=1 is set.
When searching for extension's directory, only search user directories if this variable is not set.
=> option to restart without user extensions

files/usr/bin/cinnamon-settings, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, man/cinnamon-settings.1
Hi @clefebvre,
This PR is related to #8902. 
It allows users to use commands such as `cinnamon-settings applets -t download -s update` to open the Download tab with applets sorted by available update.
It also updates man page.
Best regards.
Claudiux
=> cinnamon-settings: add 'update' to --sort option available values

js/ui/dnd.js
Makes it easier to track when an animation is complete. Used in yet-to-be submitted changes to help reduce the jankiness of DND drag operations.
v2 of #8831 that ensures the callback is always called. Since I want to use it to reset the animating state, it must always be called.
=> dnd.js: add animation done callback support to placeholder

js/ui/extension.js
The declarations were moved inside a conditional so the other uses were undeclared.
Cjs-Message: 15:53:47.091: JS WARNING: [/usr/share/cinnamon/js/ui/extension.js 585]: assignment to undeclared variable dirPath
Cjs-Message: 15:53:47.091: JS WARNING: [/usr/share/cinnamon/js/ui/extension.js 586]: assignment to undeclared variable dir
fixes: 3bb0e598219131b760b6b1ed2a5d9cfab40034fa
=> extension.js: fix variable scope regression

files/usr/share/cinnamon/applets/menu@cinnamon.org/appUtils.js
I inadvertently removed this feature in the refactoring. User-
hidden directories are marked nodisplay and so that needs to be
checked on the gmenu object either at load or display. This commit
does it at load, so consequently any unhidden category will show
all unique apps as newly installed/highlighted upon unhiding after
starting the session or applet with it hidden.
Thanks goes to @collinss for finding both the bug and the fix.
fixes: 0ed2544d7398d033a9
=> menu-applet: don't show user-hidden categories

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
For whatever reason these are getting the flash alert incorrectly. I
don't see how it could be related to my recent rework of flashButton()
but I also don't know what else could have caused this. Either way,
it's incorrect to flash a window that's already focused so avoid it.
=> window-list: don't flash focused windows

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/misc/util.js
This prevents js errors when you type reserved characters like \ or [ and such into the search box.
**Behavior change:**
Besides avoiding js errors when an incomplete regex is typed by the user, this effectively disables regex searching via the menu search box. On master, the menu search is basically a regex-enabled search field where the query is prefixed with the regex `\b` word boundary metacharacter. A user typing in
`(applet|panel)` would have a perfectly valid regex search that matches both "applet" and "panel", but not mid-word. Many JS errors will be printed while typing that, but after `)` the search will work fine.
**Options:**
1. If we actually want a regex-enabled search then the error spamming can be avoided, but there needs to be a feedback mechanism in the UI itself to …
=> Add RegExp escape utility function and use it in the menu

src/st/st-icon.c, src/st/st-texture-cache.c
This monitors file changes for GFileIcon and updates the StIcon accordingly
=> Fix: Handle GFileIcon file changes

files/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js
I'm sorry if something isn't understood, my english isn't very good.
I recently installed some themes for WM on Mint Cinnamon 19.2 (https://github.com/smurphos/Window_Borders_Mint_19), one of them is "HighContrast" theme. When the theme is applied globally from "Accessibility" (in Cinnamon Settings), the WM decoration changes to "HighContrast". This doesn't happen if you do the same from the accessibility applet.
=> a11y applet: apply HighContrast theme in WM

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, js/ui/dnd.js
I'm not sure if the hit testing will be accurate or not in hidpi since I am using direct actor size values and not transformed size. I am unsure which is the correct method to use since we get pre-transformed mouse coordinates from the DND code. It is easy to fix if it's incorrect now, but if it works the extra transformation overhead is best avoided.
I completely removed behavior that caused multiple full reloads. A comment said it was overkill but easier to get the scaled size correct that way. I haven't noticed any icon scaling issues, and have no idea what case this code was designed for(maybe hidpi?). It's extremely inefficient and also can cause extra visual disruptions. If we don't need this, it is also best left out.
This reworks:
- Applets sync state when changed from cinnamon …
=> Panel launchers rework

src/Makefile.am
Nothing in libcinnamon uses libnm, and the typelib does not need to either. In fact, the only part of cinnamon that uses libnm is the applet network@cinnamon.org and that directly imports.gi.NM, so it doesn't need to get it via exposure through the GObject bindings for cinnamon itself.
Removing references to NM from the Cinnamon typelib and rebuilding cinnamon results in a fully working Cinnamon desktop and a fully working network applet, so there is no downside to just dropping it.
Motivated by #8617 except I want to get it right -- there is no reason this cannot be a fully generic solution. We don't need a configure switch for a purely simple case of overlinking.
=> Cinnamon-0.1.typelib: do not link to libnm typelib

files/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js
On "Accessibility" settings, if gnome-orca isn't installed the switch "Screen reader" disappears (the legend "install gnome-orca" is displayed), but on the accessibility applet it's still visible.
I don't know if this is the best way to verify that gnome-orca is installed, but it works.
=> a11y applet: don't show "Screen reader" switch when gnome-orca isn't installed

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
Other actions instead of pressing the OK button should be considered as cancellation
Closes #4310
=> Dialog: Treat Escape key as Gtk.Response.NO

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
I hate when I mess it up twice in a row :[ Third time's a charm...........?
The original implementation checked needsAttention every timeout
interval and this caught the case where a window demands attention
event is triggered by an activate event on an existing window. An
example of this could be a non-focused browser window being focused
as a user clicks a link in another application. In this case, with
the original implementation, the window starts flashing and stops
before the style even changes. It also handles the case where a
user clicks the window during the flash cycle.
This commit restores that behavior.
fixes/reverts: ec9b3fb1c1c03eaf27b893e0f2ffc29166b646c1
=> window-list: proper fix for incorrect flashing

src/Makefile.am
This was explicitly removed in commit 237fa0090516e60d03aaea313c5671e6a78f8e3f but then re-added in commit e289a971610b4530622e4b35fea5af6958f5356b
Fixes regression in #8617
=> Revert the incorrect and problematic addition of overlinking in Cinnamon-0.1.gir

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Needs testing.
- Fixes js error when muting with default settings and no input.
- Fixes chromium mpris js error. we were unpacking a return value while error was set.
- Fixes removing player instances when cinnamon started with a player already open (typically only in crash or cinnamon --restart case)
- Defaults Next/Previous options to disabled for error/no dbus property case.
- Consume button press event when we act on it, instead of chaining up and possibly handling it twice and/or propagating it
- Converts all callbacks to arrow functions and removes Lang import
- Trivial spacing fixes
=> Sound applet enhancements

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
In commit 6ac295a62556f22b755b17dee29d17d6721fa361, Settings>Applets>Download gained the ability to display the number of available updates, using an ngettext-translated message. However, it has never worked since ngettext was never imported in the file in question, so it simply raised a traceback.
In the same commit, `gettext.install()` was taught to declare `names="ngettext"`, but as per the python documentation, the `names=` argument requires a sequence (of one or more aliases to declare in the global namespace), not a string. So it tried to check if it could install the gettext functions: `{'x', 't', 'e', 'g'}`, which was wrong.
The fix is to either import `ngettext` directly, so it can be used as-is, or globally install `ngettext` by passing it as a one-item list to the …
=> fix regression in ExtensionCore not working when updates are available

files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
It we were already using the version that exists in python-xapp so it's dead code now
=> SettingsWidgets.py: remove duplicate IconChooser widget

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
MetaWorkspace:window-added is sent very early in the construction of a new
window - before the compositor even knows about it, which ends up with cinnamon
frequently adding a window with no actor yet (to clone for thumbnails).
The display signal is sent at the very end of meta_window_new_with_attrs() so
should be more reliable to provide a fully developed window.
If a window is created using the ctr-click method on the app's panel item,
the framing around the new thumb is corrupted at first, if animation is enabled.
Removing the hide/show when adding a new window in this manner avoids this issue,
and has the added benefit of the entire thumbnail group re-centering itself with
its panel item automatically.
=> grouped-window-list@cinnamon.org: Listen to MetaDisplay's window-created signal for adding new windows.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
The python script `cs_backgrounds.py` was failing because an array was
not checked to be empty before being indexed.
Fixes #5586
=> cinnamon-settings: Fix missing backgrounds issue

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py
So far this only affects the settings-example applet, but it will cause breakages if someone tries to use this in another applet.
=> Settings: add missing widget import

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
It should be possible to try the sounds out without having to enable them to
see if you actually want to use them.
Closes https://github.com/linuxmint/cinnamon/issues/8187
=> cs_sound.py: Allow previewing the sound even when disabled

files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py, files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py, files/usr/share/cinnamon/cinnamon-slideshow/cinnamon-slideshow.py
In https://bugs.python.org/issue34850 using `is` with a literal became a SyntaxWarning at runtime. It was always wrong, and abused implementation details of CPython, but now it also tells ordinary users about it.
Loudly.
=> python 3.8: fix all flake8 F632 errors

js/ui/popupMenu.js
The current animation works well but is a bit on the "dramatic" side. It also
doesn't render smoothly on some of my test hardware. Using a simpler animation
also seems to feel a bit faster.
=> popupMenu.js: Use a simpler animation for open and close

js/ui/extension.js
This applet doesn't use old `import.gi.NMClient` since Cinnamon 4.0, so it should be removed from the knownCinnamon4Conflicts list.
=> extension.js: Remove multicore-sys-monitor@ccadeptic23 from knownCinnamon4Conflicts list

files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py
The pull request to add an input for the delay before locking (#7577) was not merged, so here's something else.
At the moment you can choose no lock delay or, at the minimum, a 15-second lock delay. The only situation I use the delayed locking feature for is when I notice immediately that the screensaver has kicked in and don't want it to go to the lock screen. In that situation, 15 seconds is far too long and 0 seconds is obviously too short, so there should be an option between them. This pull request adds a 2-second option.
What do you think?
=> Add 2-second screensaver lock delay option

data/theme/cinnamon.css, src/Makefile-st.am, src/st/st-settings.c, src/st/st-settings.h, src/st/st-theme-context.c
This will allow cinnamon themed elements to use the default font set in the
settings. It can still be overridden in the themes css.
* Add a st-settings object to track the font changes
* Use the interface settings instead of a default font in the theme context
* Stop setting a font-family in the default theme
Based on work in gnome shell by Florian Mullner and Carlos Garnacho
=> St: Make the theme follow the default font

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
Rename the existing options and a new Gnome and Classic Mac style.
Closes https://github.com/linuxmint/cinnamon/issues/9039
=> cs_windows: Add a couple more button layout options

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
It causes it to be the first item listed in the cinnamon menu when you open
and search for screenshot and it's hardly ever going to be what you actually
want.
=> cs_backgrounds.py: Remove "screenshot" from the keywords

files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js, src/st/st-texture-cache.c, src/st/st-texture-cache.h
For instance, with indicator-multiload:
Fixes #4035
=> xapp status applet: Support irregularly-shaped images.

js/ui/modalDialog.js
We now access OPEN_AND_CLOSE_TIME outside of modalDialog.js so we need to
declare this with var instead of const
=> modalDialog: Quiet an ES6 warning

js/ui/main.js
This is just to allow themes a bit more flexibility in sizing the text
=> restart-osd: Add an additional style class

data/org.cinnamon.gschema.xml.in, data/theme/cinnamon.css, files/usr/share/cinnamon/cinnamon-settings/modules/cs_workspaces.py, js/ui/windowManager.js
Remove all the custom placement settings and reuse the existing InfoOSD
dialog. Using the dialog with the background makes it much easier to read
against the open window backgrounds.
=> workspace-osd: Simplify and reuse the InfoOSD

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This fixes a regression in 93e85cd055bd6f7bddbb734255774e73e6167121. The intention presumably was to avoid emitting a signal unnecessarily, but the 'activate' signal is used by the menu structure to know when to close the menu, so we really do need to use it.
=> Sound applet: close the menu when a player is launched

files/usr/share/cinnamon/applets/removable-drives@cinnamon.org/applet.js
Until now, any action closed the menu of this applet, except the "unmount" action.
This PR is made so that the menu of this applet does not remain open after the user has clicked on the unmount button.
=> [removable-drives@cinnamon] Close the menu when the eject button is activated

src/Makefile.am
All of libmuffin-* will be detected and substituted into CINNAMON_LIBS
during configure stage by PKG_CHECK_MODULES(CINNAMON).
List them again is redundant, and we will run into trouble on cross
compiling.
Simplify the Makefile.am by removing it.
This will also fix the broken cross build.
See: https://github.com/void-linux/void-packages/pull/18826
=> Makefile.am: simplify libcinnamon's dependendies

files/usr/share/cinnamon/cinnamon-settings/modules/cs_display.py
They are built into the C widget instead so it all fits a bit nicer.
=> cs_display: Remove the margins from the settings widget

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json
Add configuration option for disabling `<Super> + number` hotkeys. Useful in cases when super+number is used for switching workspaces.
=> grouped-window-list@cinnamon.org: Support disabling super+number

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
the old implementation returned a wrong total disks size when a partition is mounted multiple times (e.g. for timeshift btrfs snapshots)
now using lsblk with json output, available since utils-linux 2.27 which is available even in Ubuntu 16.04
=> cs_info: fix disk size calculation

src/cinnamon-util.c
This fixes 2 things:
- Trailing slashes never got deleted
- the variable path could be NULL, in which case the rest would be superfluous
=> cinnamon-util.c: Fix icon fetching for known folders

cinnamon.pot, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
Fix some "shutdown" uses from incorrect noun form "shutdown" to correct verb form "shut down".
=> Fix "shutdown" typos

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
Hi, I feel that the `cycle` option in the `grouped window list` applet should activate the application (if it doesn't have focus) on first click, then cycle the windows on subsequent clicks. However, since some people may depend on the current workflow, I've added it as an option: `Activate, then cycle`.
My rationale for this mode is as follows.  The current `switch windows` works like this:
* Say I've got two Firefox windows, 1 and 2, and a Terminal window. 
* I'm working in Firefox window __1__, then I need to do something in terminal, so I click its icon.
* Terminal activates, all is well. I need to go back to firefox, so I click its icon.
* Firefox __2__ comes to the front, and I'm confused, why am I seeing a different window suddenly?
For this reason I feel that the first click …
=> Add `Activate, then cycle` to grouped window list

files/usr/bin/xlet-about-dialog, makepot
this fixes a regression of the about dialog of non-builtin applets not being translated
=> xlet-about-dialog: fix spices translations

js/ui/hotCorner.js
This makes the hot corners manager create actors only for corners enabled by the user. Previously, we would have 16 actors loaded into the main uiGroup actor hidden or with 0 opacity when all corners were disabled. Also includes a modernization commit since I'm here and the file's relatively simple.
This probably won't really have much effect, but could reduce memory usage and possibly a few cycles here and there.
=> Hotcorner lazy init

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/calendar@cinnamon.org/settings-schema.json
Add end user configurable keybinding Super+C to show the calendar menu.
=> calendar@cinnamon.org - add keybinding to show calendar

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/settings-schema.json
This has come up a few times on the Mint forums as a suggestion / feature request.
PR adds end-user configurable Super+N as a keybinding to show the notification applet menu along with Shift+Super+C as a keybinding to clear all notifications without having to access the applet.
=> notifications@cinnamon.org - add keybindings to open menu and clear notifications

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Some players (notably chromium based browsers) can block the sound applet as in a  stopped state they cannot be closed from the applet and prevent the launch player dialog from showing allowing users to launch alternative players. Also in general it's useful functionality to be able to launch additional players from the applet even when a player is already active.
Works around / fixes #9022 & #8917
=> sound@cinnamon.org - don't hide launchplayer item when another player is active

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
Adds end user configurable Super+S keybinding to display the sound applet menu.
=> sound@cinnamon.org - add keybinding to show applet menu

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
Hi,
This removes the hardcoded icon sizes in-menu and allows the end user to configure in-menu icon sizes.
The 'magic' formula to resize favourites box icons was effectively obsoleted in any case when the option was added to control the minimum height of the favourites box and it was made scrollable several releases ago.
Application context menu icon sizes remain hardcoded - leave it like that?
I also had to hard code the Recents clear-items button icon-size as for reasons I couldn't work out the applet object wasn't recognised in the `refreshPlaces()` function where that button is added.
=> menu@cinnamon.org - allow end-user control of favorite, category and application icon sizes

docs/reference/cinnamon-js/gen_doc.py, docs/search-providers-examples/trackerprovider@cinnamon.org/search_provider.py, files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py, files/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py, files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/bin/eyedropper.py, files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_accessibility.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_desktop.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_screensaver.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py, generate_additional_files.py, utils/cinnamon-stap-monitor/cinnamon-stap-monitor.py
In one case, gi.require_version is supposed to be run before importing the namespace itself, so keep the second set of imports.
Clean up lots of other imports that aren't actually used.
=> flake8: remove useless double or unneeded imports

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
This third-party module isn't always used, as it's special-cased on some distros. By only importing it if it is actually used, we can reduce the likelihood of things going wrong, such as failure to have it installed.
#9171 added a new dependency without me noticing. But I can't help notice that my distro (and Mint itself) is one case where this codepath is never touched anyway, so the dependency is useless. I could of course add it, and for the current release will do so, but this commit would make overlooking a dependency, potentially less issueful, so why not?
=> cs_info: delay import of 'distro' module until it is used

js/ui/windowManager.js
the osd does not get destroyed and lingers after switching workspaces, when window effects is disabled.
Regression caused by 041ac072e77431cbe5ea1fb23611d8c4f6fde08c
=> Fix workspace OSD

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py
Deprecated since version 3.1, will be removed in version 3.9: encoding keyword argument.
https://docs.python.org/3.8/library/json.html#json.loads
=> Remove encoding=None

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
The current fix ([here](https://github.com/linuxmint/cinnamon/commit/08742aa68838f95c1de419c146f096d4c1a387d3)) to prevent "jumpiness" [#3144](https://github.com/linuxmint/cinnamon/issues/3144) when different scripts are used works by always setting the selectedAppBox height to 30px as get_theme_node().get_length('height') always returns 0 and get_theme_node().get_height() returns -1 (due to the style not yet having been initialised) meaning that selectedAppBox height is always set to 30px regardless of any height set in the .css file. 
This fix sets the height to an appropriate height if no height value exists in the .css file. If a height is set in the .css, get_preferred_height() returns this value.
~~Ideally~~, this fix would be used whenever the style-changed signal is received in …
=> menu@cinnamon.org: a fix for jumpiness bug

data/theme/cinnamon.css
The .menu-selected-app-box style should use em's instead of px's to take account of changes to text scaling factor or default font size. This solves the problem of the description disappearing off the bottom of the menu when a larger font or font scaling is used. The value used is 2.2em so that the menu appears the same as it would if no changes to font size are made from the fresh install default (ubuntu regular, 10 and text scaling: 1.0)
=> cinnamon theme: use em's instead of px's

files/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js
Hi,
Unlike days in the calendar, weekday labels in the header have no style classes to differentiate decoration of work days and non-work days. The PR adds style classes to weekday labels in the header so that to enable individual styles for work days and non-work days.
Cheers.
=> calendar@cinnamon.org: Add (non)work-day style classes to the header

configure.ac, debian/control, src/main.c
It's not actually used, but it pulls in a dependency on dbus itself, and the dbus-glib header is used to grab some constants from a dbus provided header. There's no reason to proxy this through dbus-glib.
Also clean up some PKG_CHECK_MODULES I noticed at the same time.
@Fantu relevant to your discussion about using it in cinnamon-settings-daemon, it needs to be cleaned up in a few other places before cinnamon-settings-daemon dropping it will mean much. Also https://github.com/linuxmint/cinnamon-control-center/pull/235
=> Remove build dependency on dbus-glib

files/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js, js/ui/systray.js
This specifically fixes an issue where the sound applet registers `rhythmbox` but the xapp status applet gets `Rhythmbox`, but it could also serve to prevent other such issues in the future.
=> systray manager: make all role comparisons lower case

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
When the Control Players setting is off, the Launch player menu item disappears, as it should. The problem is that the Launch player menu item will reappear after cinnamon is reloaded, either manually or from a restart/at next boot. This fixes it so that the Launch player menu item correctly stays hidden.
=> [sound@cinnamon.org] Update applet.js - Further fixes #6243

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
This PR updates `applet.js` to displays the volume level on the `sound@cinnamon.org` applet while scrolling with the mouse wheel.
=> [sound@cinnamon.org] Display volume tooltip while scrolling with the mouse wheel (applet.js)

js/misc/util.js
This fixes a typo that leads the latinise-function to changing 'F' to 'L'
=> js/misc/utils.js Fix latinise()

docs/reference/cinnamon-tutorials/xlet-settings-ref.xml, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
Add a new option to TreeListWidgets: `show-buttons`, a boolean to choose whether show the action buttons below the list.
The default value of `show-buttons` is `true`.
Example of use:
In settings-schema.json:
```
"temp_sensors": {
"type": "list",
"columns": [
{
"id": "sensor",
"title": "Sensor",
"type": "string"
},
{
"id": "show_in_panel",
"title": "Show in panel",
"align": 0.5,
"type": "boolean"
},
{
"id": "show_in_tooltip",
"title": "Show in tooltip",
"align": 0.5,
"type": "boolean"
}
],
"default": [],
"show-buttons": false
},
```
Result:
Without this option, or if this option is set to `true`, the action buttons are shown below the list:
=> TreeListWidgets: 'show-buttons' new option

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
The search function does a search only at the beginning of a word.
E.g. search for "Manager" does find "Update Manager", but searching for
"date" does not find "Update Manager" or a better example, searching for
"office" does not find "LibreOffice".
This commit (magic trick from mtwebster) removes the restriction to the beginning of a word.
=> menu applet: search for words inbetween

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
If "Show recent documents" is activated, but there are no recent
documents, the search doesn't work at all.
=> menu applet: fix broken search, if no recent documents

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
This PR fixes issue #9546
The problem was that the `_initial_cat_selection` function can be executed after a category is selected due to being called asynchronously, and there was no check if it _is_ running after a category has been selected.
=> fix issue #9546

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, js/misc/gridNavigator.js, js/misc/history.js, js/ui/appSwitcher/appSwitcher.js, js/ui/dnd.js, js/ui/expo.js, js/ui/expoThumbnail.js, js/ui/lookingGlass.js, js/ui/main.js, js/ui/modalDialog.js, js/ui/popupMenu.js, js/ui/runDialog.js, js/ui/slider.js, js/ui/workspace.js, js/ui/workspacesView.js
```c
/*
* Compatibility version of clutter-keysyms.h.
*
* Since Clutter 1.4, the key symbol defines have been changed to have
* a KEY_ prefix. This is a compatibility header that is included when
* deprecated symbols are enabled. Consider porting to the new names
* instead.
*/
```
**Source:** [deprecated/clutter-keysyms.h (muffin)](https://github.com/linuxmint/muffin/blob/9cbb7ea75d3855ee11a71c11e75000edc7c1ede7/clutter/clutter/deprecated/clutter-keysyms.h#L20-L27)
:fast_forward: This PR does this throughout the content of the Cinnamon repository, in an automated manner. :thumbsup:
```c
#define CLUTTER_VoidSymbol 0xffffff CLUTTER_DEPRECATED_MACRO_FOR("Deprecated key symbol. Use CLUTTER_KEY_VoidSymbol instead.")
```
:arrow_right_hook: Above, an excerpt from [this long …
=> Deprecated Clutter keysyms migration

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/settings-schema.json
- adds a new option called **Reverse scrolling direction** in the "workspace-switcher" applet _(option is off by default)_.
<details>
<summary>View me ...</summary>
&nbsp;
</details>
<details>
<summary>Read me ...</summary>
&nbsp;
On my mouse (a Logitech M705 as above), I hold the side button visible on the right side of this image and scroll down to go to the left workspace and up to go to the right workspace _(using a customized version of [this script](https://www.linuxquestions.org/questions/linux-desktop-74/%5Bxbindkeys%5D-advanced-mouse-binds-4175428297/#post4786821))_.
The goal, achieved with this PR, is to have the same behavior when I scroll on the "workspace-switcher" applet (without holding the additional button there).
</details>
<details>
<summary>Read me ...</summary>
&nbsp; …
=> workspace-switcher applet: New option: "Reverse scrolling direction"

debian/control, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/ui/messageTray.js, js/ui/search.js
Maximiliano Curia patch from debian packages, used from cinnamon 4.0 packages.
As reported by Simon McVittie in
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877738, in the next debian
version the deprecated gvfs-bin will be removed.
This patch remove also gvfs-bin from deps, libglib2.0-bin is already present and
used.
=> Replace deprecated gvfs-bin calls with gio-tool

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, js/ui/appSwitcher/appSwitcher.js, js/ui/expoThumbnail.js, js/ui/popupMenu.js, js/ui/workspace.js, src/st/st-button.c
- adds "KEY_KP_Enter" _(numpad Enter key)_ as an alternative to "KEY_Return" _(Enter key)_ everywhere.
- In Alt+Tab;
- In the context menu of the Cinnamon panel;
- etc.
&nbsp;
___
=> "KEY_KP_Enter" as an alternative to "KEY_Return" everywhere

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
Until now, when viewing an applet's settings, the `icon.png` icon was displayed in the panel, which could contrast with the applet icon itself and confuse the user.
From now on, if an `icon.svg` icon exists then this one is displayed first.
=> xlet-settings.py: Take into account icon.svg prior to icon.png

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
This patch was created by marga@debian.org for debian packages.
I think can be good add a blueman icon in cinnamon settings (that appaire if is
installed), is useful for users or distros that have only blueman instead
blueberry (or also it and prefer it).
=> Add Blueman to the possible icon in cinnamon settings

debian/rules
Actually lmde4 build fails, workaround it disabling dh_dwz, was added by default
in compat 12. Probably the issue is an unexpected case in dh_strip with old
manual debug packages used by cinnamon (instead
https://wiki.debian.org/AutomaticDebugPackages)
=> fix lmde4 build

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
This PR addresses #8779. 
This PR will need tested since the logic that was keeping the icons around is closely related to logic that is used when moving windows around from one workspace to another. I did some testing and things looked to still be working correctly. I'll remove the commented code once further testing has been established.
=> Removed logic that was keeping icons around after window closed

docs/reference/meson.build
This makes building the reference documentation optional to prevent root ownership in the build folder when building and installing without package management.
The meson option is already available but unused. The corresponding debian rule is also already present.
=> Make building the reference documentation optional

js/ui/panel.js
See #9597.
Currently the icon zone size settings are removed every time a panel is destroyed, which causes them to be reset to default every time a monitor is disconnected from the system.
This adds an optional parameter to the destroy function to allow removing icon size settings to skipped if required, such as when a panel is destroyed due to a monitor being removed.
=> Fix #9597 - monitor disconnect resetting icon sizes

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/constants.js
This way the amount of flashes is not hardcoded in the UI code anymore.
If this were to be merged, should I do the same for the `window-list` applet?
=> grouped-window-list: Add FLASH_MAX_COUNT constant

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, js/ui/xdndHandler.js
* fix juddering when dragging items and improved animation (resolves #8639).
Personally I would recommend to change the animation to be like in `panel-launchers@cinnamon.org` (make selected item move _during_ dragging instead of making another empty space where you want to place it), but that's just taste.
* prevent pinned and unpinned items from getting mixed after dragging.
This seemed to me as the best option for the current state of GWL of usually causing ui issues when pinned and unpinned items are mixed, I am open to critisicm of this.
Edit: turned this into a Draft PR as I'm currently waiting for feedback and the code isn't perfect yet.
=> Improve dragging of items in GWL

src/cinnamon-generic-container.c
Build thinks it should be lowercase.
It also complains about pre-processor symbols which I'll look into-I think it's tab formatting.
=> Solve a deprecation warning in an if statement

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
This allows a keyboard shortcut to be configured for "Mic mute". Adding this and configuring a key already seems to make toggle muting the default input/mic to work for me.
Partly fixes https://github.com/linuxmint/cinnamon/issues/9310
=> Add mic mute keyboard shortcut option

files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js
Fixed the applet's apps being reactive when loaded in panel-edit-mode (ex. after moving the applet while editing panel)
=> XApp status applet: Fix apps being reactive after loading in panel-edit-mode

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
This mostly fixes #9067 .
It does not fix the last HoverMenu staying on (is it considered a bug or a feature?).
=> GWL: Fix tooltip lables stuck on after menu cycle

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/desklets/launcher@cinnamon.org/desklet.js, src/cinnamon-app-system.c, src/cinnamon-app-system.h, src/cinnamon-app.c, src/cinnamon-app.h, src/cinnamon-window-tracker.c
Some flatpak apps don't care about making sure that side-by-side installation to versions from distribution repositories can be done cleanly.
This improves the way flatpak apps are integrated into Cinnamon by adding the suffix ":flatpak" to their
dekstop file id and to their StartupWMClass. This allows us to integrate them side-by-side with their distribution counterparts,
mainly for the menu, but also for pinning them in Grouped Window List and adding them to the panel-launchers applet.
This replaces https://github.com/linuxmint/cinnamon/pull/8701
This depends on https://github.com/linuxmint/cinnamon-menus/pull/39
=> Improve integration of flatpak apps for side-by-side installations

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js
Fixed the notifications icon getting hidden when toggling the show-empty-tray setting, despite being in panel-edit-mode.
=> Notification applet: fix icon incorrectly getting hidden in panel-edit-mode

src/meson.build, src/st/meson.build
https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers
=> meson: fix order-only dependency on generated headers

src/meson.build
It's optional but we need to account for that in the libcinnamon dependencies
as well.
Fixes: https://github.com/linuxmint/cinnamon/issues/9727
=> meson: Fix build when network manager is disabled

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
Continuation of #9710 , Fixes #9067
=> GWL: Fix last hovermenu stuck on after menu cycle

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
With old code, a stream name (in slider tooltip) containing 17, 18, 19 or 20 characters was replaced by a string containing 20 characters, losing useful info.
For example, the string `ALSA plug-in [mocp]` (19 chars) was replaced with `ALSA plug-in [mo... ` (20 chars).
This commit fixes that.
=> [sound@cinnamon.org] Slider tooltip: Display entire stream name when its length <= 20 characters

files/usr/share/cinnamon/cinnamon-settings/modules/cs_accessibility.py
This pull request adds the Shift key as an option for mouse wheel magnification hotkeys to cinnamon-settings. In the current situation, this works a lot better than the other options because blink/chromium-based UIs (including cinnamon itself) would react to scrolling even though a hotkey was pressed and the magnifier was active. This is not the case with the Shift key.
Shift is the hotkey for horizontal mouse wheel scrolling, though, so it will interfere with that. But seeing that horizontal scrolling is less common in UIs, it is a suitable workaround for most users and applications. In cinnamon UIs, zooming while holding shift is not possible - it will just scroll vertically. From a usability perspective, this is more likely to be understood.
This issue was first described in #8549 and …
=> Include shift key as magnifier shortcut

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
It will try to detect CPU model and leave it being "Unknown" if all attempts failed.
Also see #9754.
=> cs_info: fix crash caused by missing key under getProcInfo

meson.build, src/meson.build
We've never linked to libnm, merely checked if it existed. During the meson port, this somehow found its way into being over-linked into cinnamon itself, resulting in #9727, which was improperly fixed in #9729 by only performing the over-linking if networkmanager is enabled.
Nevertheless, it remains overlinking. Remove it entirely, and comment the dependency() call to document why we're looking for it but not trying to link it to anything.
=> Proper fix for builds with networkmanager disabled.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
https://github.com/linuxmint/cinnamon/commit/91302ec086ee2061e57dd972baaa43eb0926b150 changed the display of certain power devices. Part of this was
adding a small icon. This icon turns out not to add much information wise and
doesn't turn out to look so good. Remove the icon but leave the other changes
intact.
=> cs_power.py: Remove a status icon

src/cinnamon-app.c
Some applets (menu, gwl and panel-launchers) want to use this id
for lookups at a later time. In the case of desktop files inside of
subfolders, cinnamon-menus prepends the parent path to the desktop
filename, and this is used as a key in CinnamonAppSys. This won't
match the id returned by g_app_info_get_id() causing app-sys lookups
to fail later on.
=> Fix for desktop files in subfolders: use the desktop id generated in cinnamon-menus

files/usr/share/cinnamon/applets/removable-drives@cinnamon.org/applet.js
Before:
After (together with https://github.com/linuxmint/mint-y-icons/pull/279):
=> removable-drives applet: use drive-removable-media icon

files/usr/bin/cinnamon-file-dialog
(and specify a version properly).
Was monkeying around and I found:
```
/usr/bin/cinnamon-file-dialog:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gtk
```
I did figure out why it really did fail (because I didn't specify a number) but this should've been imported anyways.
=> cinnamon-file-dialog: Import GTK properly

files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
These were limited to 40 characters in length which wasn't really needed. The
new size group is used to keep the labels truncated to the same length even
if the row doesn't show a delay value.
Fixes: https://github.com/linuxmint/cinnamon/issues/9862
=> cs_startup: Improve ellipsizing of description labels

meson.build
As best as I can tell, gstreamer is only used by the recorder tool. Now that it has a build option, also make gstreamer optional.
=> Make gstreamer dependencies optional

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
It's important to be able to uniquely identify the spice.
We also want to give a notion to the user that these are somewhat 3rd party
and not core.
=> Spices: Show UUID in management/download tabs

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
This makes it so that xlet authors don't need to include the icon in their multiversion subfolders so that we can reduce the download size.
=> cinnamon-settings xlets: ignore multiversion when looking for an icon

files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js
Height of the the windows-quick-list applet popup is hardcoded to 400px, this forces ScrollView to show the scroll bar too early. After removing the hardcoded option, the popup will be dynamically resized to show all the opened windows until it will reach screen height, only then scroll bar will be shown.
=> windows-quick-list applet: avoid fixed popup size

files/usr/share/cinnamon/applets/favorites@cinnamon.org/applet.js
Same change as recent to windows-quick-list applet: the widget uses scroll view, so
it can grow to fill all available space by vertical direction, and then a scroll bar is shown.
Extra padding between elements was removed to keep the list more clean, it uses the 
same padding as menu applet now.
=> favorites applet: remove extra padding and avoid setting constant height

files/usr/bin/cinnamon-xlet-makepot
The issue exists because [os.walk's list elements are in arbitrary order](https://stackoverflow.com/a/18282401). Because of that the resulting .pot file will be in different order on different systems, making reviewing PRs for them unnecessarily hard (and the script's output should be reproducible for it's own merit too).
Sorting os.walk's output in every place in the script fixes this issue.
Relevant issue: https://github.com/linuxmint/cinnamon-spices-applets/issues/3645
=> Fix cinnamon-xlet-makepot so it always gives the same output on every system

files/usr/bin/cinnamon-xlet-makepot
This prevents the script from failing if one of our translated keywords in settings-schema.json is used as the key name for a settings definition. It works by skipping the check for keywords on the root node (1st run of the function extract_settings_strings()). Also display a warning and return if we attempt to save a value that is not a string so that the user of the script knows there's something wrong with the input file.
=> cinnamon-xlet-makepot: ignore keywords if they're used as settings keys 

data/org.cinnamon.gschema.xml, files/usr/bin/cinnamon-launcher, files/usr/share/cinnamon/cinnamon-settings/modules/cs_general.py, js/ui/cinnamonDBus.js, src/cinnamon-global.c, src/cinnamon-global.h
Check the memory used by Cinnamon at regular intervals. Restart Cinnamon when the memory reaches an unacceptable limit.
Rationale: Some memory leaks are hard to detect or identify (whether that's because they only happen on certain hardware or in certain niche use cases or whether that's because they're very small and have an imperceptible effect when monitored during a short period of time). Sometimes we don't even know if issues reporting leaks we can't reproduce are still relevant. Yet people still sometimes do report abnormal RAM usage, particularly as the result of using 3rd party spices or after leaving the computer idle for a long period of time. This PR provides a workaround by monitoring the RAM usage and restarting Cinnamon if it reaches a certain threshold.
Using the General …
=> Add a memory limit mechanism to Cinnamon

files/usr/bin/cinnamon-xlet-makepot
If we only have `.js` files with translations, xgettext is never
triggered and we end up with a .pot file without a header and without
metadata.
Also if xgettext is not triggered, the old .pot file is never deleted
and old unused strings are never deleted. Translators have to translate
strings for nothing.
Therefore we need to delete existing .pot files at the very beginning.
Fixes https://github.com/linuxmint/cinnamon/issues/9961
=> cinnamon-xlet-makepot: Add header and metadata to .pot file

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py
This catches the AccountsService error for USER_EXISTS. Everything has 
to be moved to try/except because without it, it can lead to some 
unstability.
Fixes #9494
Extra Notes: For some reason using in or == doesn't work but __eq__ does. Making a new dialog can cause some unstability, and the *whole* try/except has to be moved because we don't want an undefined reference with the new_user variable. Believe me I got frustrated trying this.
I know this isn't the *best* but it's something for systems that want to make a Stable Release Update for this fix. Let me know if you want me to change anything
=> cinnamon-settings-users: Don't hold when user creates an existant user.

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js, js/misc/util.js
Perform a periodic connectivity check to indicate
on the panel when there is no internet (global) access.
Due to a bug in libnm, this uses a dbus to communicate directly
with org.freedesktop.NetworkManager for libnm versions before
1.28.0. For newer versions, the NM.Client api is used.
Since the check can take some time - potentially more than the
periodic update interval, we don't start a new check before
receiving a reply from the previous one.
fixes #9927
=> network applet: Indicate on the panel icon when there is no internet access

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Some players return an empty `as` artist array, which results in `_artist` being empty.
=> sound applet: fix empty artist

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
These should mirror the layout of having them on the left
Fixes: https://github.com/linuxmint/cinnamon/issues/9522
=> cs_windows: Fix the button layout when placing icons on the right

js/ui/appSwitcher/appSwitcher.js
Fixes #9787
Closing windows like that (especially with the Q key, which is dangerously close to the Tab key that the user often intends to press) is a destructive and not undoable action, which makes for a bad user experience when it happens. As per https://github.com/linuxmint/cinnamon/pull/10029#issuecomment-813109829 it seems like the feature might have low enough usage that removing it is better than maintaining it and having a separate configuration option.
=> Remove window-close action on Alt-Tab Q shortcut

src/st/meson.build
Uncovered while building with samurai [0] but can probably also
happen with ninja eventually.
In file included from ../src/main.c:25:
In file included from ../src/cinnamon-global-private.h:28:
In file included from src/st/st.h:7:
../src/st/st-box-layout-child.h:24:10: fatal error: 'st-enum-types.h' file not found
#include "st-enum-types.h"
^~~~~~~~~~~~~~~~~
[0] https://github.com/michaelforney/samurai
=> Attempt to fix parallel build

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
Currently the tooltip of the sound@cinnamon.org applet only shows the sound volume. Often I just want to check quickly, which track is playing. At the moment I have to click onto the icon to reveal this information. I don't want to have this information shown permanently in the panel, because it takes a lot of space.
This adds the following additional information to the tooltip:
The player and its state.
The artist.
The title.
It is possible to configure what is actually added.
@mtwebster
=> Add additional information to the sound@cinnamon.org applet tooltip

src/hotplug-sniffer/hotplug-sniffer.c
(https://github.com/GNOME/gnome-shell/commit/4dfc53cade812e3b63205620fa13e31955e72763)
=> hotplug-sniffer: drop volatile

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
This PR implements an optional "switch categories by clicking" option for the default menu applet in Cinnamon.
The option is now available as a toggle in the applet's settings, which have been rejigged a little bit to make the most important options more prominent.
This PR also adds an icon for the "all applications" category.
=> Implement optional "switch categories by clicking" option in menu applet 

files/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js
Previously, the tooltip wasn't updated until the next time it was shown, meaning that if the value changed while the tooltip was already visible, it would continue to display the outdated text until the mouse was moved away and then back again. This could be a problem in situations where the user scrolls on the icon to change a value (eg. volume) which is displayed in the tooltip.
=> xapp status applet: update the tooltip text immediately

js/ui/lookingGlass.js
For some reason, the `ClutterActor` vertex functions[1] now throw an error[2] on any access of the property. Previously, I'm guessing before the most recent CJS rebase, the functions would only throw an error when trying to use them, but now it's any time they are even touched. I don't know why this is, but I've just blacklisted those functions from being described via melange's object inspector.
This also fixes a long standing issue with the Window List inside Melange where windows will not properly be removed from the list after they are closed. For some reason the `MetaWindowActor` is still listed by `global.get_window_actors()` immediately after the `MetaWindow` emits `MetaWindow::unmanaged`. To work around this, I've made all calls to update the window list instead queue an update …
=> looking glass ClutterActor inspection and WindowList fix + cleanups

files/usr/bin/cinnamon-killer-daemon, files/usr/bin/cinnamon-launcher
This fixes a regression with the fallback code in `cinnamon-launcher` where after conversion to an idle function, the `confirm_restart` function no longer returned a boolean value, and so the code always functioned as if the user had clicked no. (`None` was the actual return value) To work around this, the conditional code was moved directly into `confirm_restart` so we don't have to worry about passing the value around at all.
It also changes cinnamon-killer-daemon to make sure it uses `cinnamon-launcher` instead of `cinnamon --replace` directly, so that the fallback and memory limiting behavior are preserved across restarts via the shortcut.
Finally, and least important, the usage of GObject.idle_add is converted to GLib.idle_add to avoid a deprecation warning.
=> Fallback regression fix and launcher preservation thru keybind restart

files/usr/share/cinnamon/cinnamon-settings/bin/util.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
=> cinnamon-settings: Remove ~/.local and /usr/local from python's module search paths.

src/meson.build, src/st/meson.build
Fixes an issue with the package tag in the gir not being generated.
See https://github.com/linuxmint/xapp/commit/e40a44c
=> meson girs: Export gir names as a package

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
..in menu applet to avoid label sometimes being ellipsized.
Ellipsizing goes away after changing text size but comes back after restarting cinnamon. This seems to fix it.
Changes:
to:
=> Change method of making "Clear list" label bold..

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json
Do this by removing the option from the GWL settings. This is forcing that
menu item to show even for applications that only support launching a
single instance like Bulky. The menu entry will still show for applications
that properly support this action in their desktop file.
=> GWL: Don't force the "New Window" option to show

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
This is my solution to issue #10293.  By checking the position of the panel (left or right) versus checking the width and height of the panel, I found more reliable checking.  Additionally, a variable is defined (depending on vertical or horizontal applet) to fix the position at which the window will be inserted while dragging.
=> Fix window ordering with vertical panels

js/ui/panel.js
fixes #10337
Although a panel can be recovered, this is not straightforward for a novice especially if it's your last remaining panel and it's easy to accidentally click on the wrong menu item and instantly delete your panel, I've done it myself. If you google "accidentally deleted cinnamon panel" you'll find lots of posts where people are asking how to recover their panel so this seems to be a not uncommon problem. I think just a confirmation dialog is the way to go.
=> Add confirmation dialog when removing a panel

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Fixing by removing it, the only time it was ever visible was when the bug occurred anyways.
Fixes #4494, alongside any duplicate tickets here and in linuxmint/cinnamon-menus.
=> Fix type to search boilerplate text not being automatically cleared

src/cinnamon-perf-log.c, src/cinnamon-recorder.c, src/hotplug-sniffer/hotplug-sniffer.c, src/st/croco/cr-parser.c, src/st/croco/cr-statement.c, src/st/croco/cr-term.c
This patch fixes a number of memory leaks found by static analysis. In a
couple places the free'ing was at the wrong scope and didn't free in the
error path.
=> Fix memory leaks on error paths

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Spotify now fixed the album art issue. I commented out the artUrl.replace() line and album art now shows in the sound applet.
Here's proof that it works now:
=> Spotify fixed the album art issue

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
Currently, window labels are completely disabled for vertical panels with the window list applet. I've added a toggle to the preferences menu to "Show window labels next to icons," and this is enabled by default. For vertical panels, this allows users to show the window labels (same as the default behavior for a horizontal panel). Users can still disable this setting if they prefer the cleaner look of only icons/no labels for both horizontal or vertical panels.
(2nd PR since I messed up the first one)
=> Window list: Add toggle for window labels on/off

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
In this PR I propose a new feature of sound applet for processing base64 data, that can arrived through d-bus in [artUrl](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#mpris:arturl) property.  The KDE already has the feature like this.
<details><summary><b>Screenshot</b>:</summary>
</details>
=> sound applet: added processing base64 code for art url data

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/settings-schema.json
RFC to add a setting that always hides notification count (useful when panel is vertical).
Needs translations for string "Don't show notification count in tray".
=> notifications applet: Add new setting "Don't show notification count in tray"

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Fix navigation left/right by switching handling between left and right keys
Ex: Left arrow press -> Handle as right arrow press in code -> Move "right", actually move left in an RTL layout
=> Menu applet: Improve keyboard navigation with RTL layout

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
GWL: Update AppGroup icon every time a new window is added to it, to account for cases when the first window of an app doesn't have an icon.
e.g: VirtualBox VM
=> GWL: Fix issue 10401; Update AppGroup icon every time a new window is added

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
`const` is a constraint that will not let a programmer to try to change its value when there is no need for it. It's a good practice in JS now (and even in C as well as in other languages where it's available). Moreover, JS JIT possibly can make better native code with `const` variable because he know that its type will never change.
Keyboard applet is a good point to start using it because the code is small enough =)
=> keyboard applet: Change 'let' to 'const' where possible

files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py
Relpace `right` and `left` lables when on an rtl layout.
I would like some feedback as to whether using a label multiple times can affect translation handling (e.g. create two entries to translate).
=> Window button layout setting: improve rtl handling

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
In order to have fade-out animations, multiple preview overlays are needed at the same time.
The existing code did not handle this, instead not creating a new overlay and not showing a window preview if an existing overlay was fading out.
I did not find any existing issues that were reported about this.
I also did some related code cleanup.
=> GWL: Fix thumbnail preview issue when window fade-out setting is non-zero

files/usr/share/cinnamon/cinnamon-settings/bin/capi.py
Add the library path with the system's arch specific triplet
(e.g. 'x86_64-linux-gnu' or 'arm-linux-gnueabihf') to the search path
for C settings modules. This way it is possible to use the affected settings
modules on ARM based platforms like the Raspberry Pi and most other platforms.
=> capi.py: support non-i386/x86_64 architectures

js/ui/messageTray.js, js/ui/notificationDaemon.js
This removes a bunch of code related to the notification source's former usage as an actual actor on the panel in the old message tray implementation. We only use the icon generation and source tracking features of this prototype these days, so we don't need any of this wasted CPU time making a new actor for the summary label and such.
Works for me on the notification sources I know of, but could probably use some additional testing before merge just in case. This code was all in play before, just not used...so there is still possibility for breakage if I missed any vestiges.
=> Notification Source simplification

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
This is a small change that will allow to fix a bug with wrong layout icon width when the panel is vertical.
Creating a separate PR for it to isolate this change for easing to pick out possible regressions.
=> keyboard applet: Remove unneccesary 'if' in offsets calculation

files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py
Fix #10432 by removing `encoding` argument when calling `json.loads` (`encoding` doesn't exist anymore in python 3.9)
=> JsonSettingsWidgets.py: remove keyword argument `encoding`

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
Keyboard applet has a bug: if the panel is vertical, the flag icon has the width of panel (minus some padding) regardless of the panel icon size setting.
The PR fixes this behaviour.
=> keyboard applet: Respect "icon-size" when panel is vertical

src/meson.build, src/st/meson.build
Regressed by [meson@5cc166a66](https://github.com/mesonbuild/meson/commit/5cc166a667ff). Similar to https://github.com/linuxmint/cjs/pull/98. From [error log](http://www.ipv6proxy.net/go.php?u=http://package22.nyi.freebsd.org/data/130amd64-default-foo/2021-11-28_09h10m20s/logs/cinnamon-4.8.6_1.log):
```python
$ meson setup _build
[...]
src/st/meson.build:204:0: ERROR: "install_dir" must be specified when installing a target
```
**EDIT**: `lmde4` bustage on CircleCI looks unrelated:
```
The following packages have unmet dependencies:
cinnamon : Depends: gir1.2-ecal-2.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
[...]
dpkg: dependency problems prevent configuration of cinnamon-common:
cinnamon-common depends on gir1.2-timezonemap-1.0; however: …
```
=> build: unbreak with meson >= 0.60.2

calendar-server/meson.build, calendar-server/org.cinnamon.CalendarServer.service.in
Hi, the D-Bus service file for cinnamon-calendar-server doesn't currently respect any install prefix other than `/`. While any prefix *is* respected when installing the corresponding binaries (with them ending up in the correct locations), the service file does not reflect this at all and thus potentially points to an invalid location. In such cases, opening the calendar applet only results in the following D-Bus error:
```
Activated service 'org.cinnamon.CalendarServer' failed: Failed to execute program org.cinnamon.CalendarServer: No such file or directory
```
This patch prepends the used prefix to the `BINDIR` variable that is used for replacement in the service file.
=> calendar: Fix missing prefix in bindir path for D-Bus service

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/calendar@cinnamon.org/eventView.js
This makes the new date format strings translatable, so that they can be picked up when makepot is run again.
=> [calendar applet] make new date strings translatable

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
=> Prevent panel settings menu from crashing when opening it

js/ui/screenshot.js
Fix the following warning:
> (cinnamon:2349): Cjs-WARNING **: 23:44:58.421: Some code accessed the property 'ScreenshotService' on the module 'screenshot'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
=> Fix warning about using var for module exports in screenshot.js

files/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js, files/usr/share/cinnamon/applets/calendar@cinnamon.org/eventView.js, js/misc/interfaces.js
None of the e-d-s libraries actually depend on evolution-data-server
(which is what provides the backend to these libraries). Also, not
everyone may want this sort of thing in the first place.
So, check if the e-d-s service we require is active before trying
to enable event support.
ref: #10597, #10567
=> calendar events: Check if evolution-data-server is running before enabling events.

docs/reference/cinnamon-js/meson.build
Sadly, the `dependencies` kwarg does not actually do what it seems to be trying to be used for, here. It is for listing dependency or library objects whose compiler flags should be added to gtkdoc-scangobj.
It will not actually add ninja target dependencies. The similar kwarg in other meson functions (e.g. genmarshal and compile_schemas) that *do* allow adding target dependencies, is `depend_files`.
Older versions of meson simply did nothing in an if/elif/elif block where these custom_targets never matched anything, and were thus silently ignored.
Meson 0.61 type-validates the arguments and rejects CustomTarget as invalid:
```
docs/reference/cinnamon-js/meson.build:11:6: ERROR: gnome.gtkdoc keyword argument 'dependencies' was of type array[CustomTarget] but should have been …
```
=> gtkdoc: remove dependencies on custom target files

src/meson.build, src/st/meson.build
This reverts commit 8fc2df08b40aa3e1958ed2fde853c50676d8cf48.
This commit was wrong, because it tried to work around a bug in a single version of meson by using something that isn't, wasn't, and won't be a valid value.
The fixed version of meson 0.60.x has been out for a while now, which once again accepts `false`, and 0.61.0 also accepts `false` but was known at the time of this workaround to not work in meson-git master (now meson 0.61.0).
Using `false` is acceptable and the failure to accept it has been qualified as a meson regression. Using `[false]` is just... trying to fuzz meson with random objects until you get something that slips its way through the argument checker and produces desired effects on the python implementation level.
=> Revert "build: disable gir install via list to pacify meson >= 0.60.2 (#10489)"

js/ui/deskletManager.js
Before:
```
Cjs-Message: 04:16:09.536: JS LOG: Cinnamon started at Tue Feb 15 2022 04:16:09 GMT+0200 (EET)
Cjs-Message: 04:16:09.566: JS LOG: [LookingGlass/info] ExtensionSystem started in 2 ms
Cjs-Message: 04:16:09.567: JS LOG: [LookingGlass/info] NaNms
Cjs-Message: 04:16:09.567: JS LOG: [LookingGlass/info] SearchProviderManager started in 2 ms
```
After:
```
Cjs-Message: 04:36:55.117: JS LOG: Cinnamon started at Tue Feb 15 2022 04:36:55 GMT+0200 (EET)
Cjs-Message: 04:36:55.148: JS LOG: [LookingGlass/info] ExtensionSystem started in 3 ms
Cjs-Message: 04:36:55.149: JS LOG: [LookingGlass/info] DeskletManager started in 2 ms
Cjs-Message: 04:36:55.149: JS LOG: [LookingGlass/info] SearchProviderManager started in 3 ms
```
=> deskletManager.js: correct logging of startup time

files/usr/share/cinnamon/applets/calendar@cinnamon.org/eventView.js
In the current version of the Calendar Applet, in the Events view, the end times or end days is only shown for events that last more than one day. This small PR changes so that the end time is shown for events that are only one day. I personally find this feature to be useful for time management.
To the maintainers, I have some questions. Was it intentional to NOT show the end times for single day events? If so, should I add a toggle in the settings so that users can switch it on or off?
=> Calendar Applet: single day event now shows end time

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
A little more solid code, things like https://github.com/linuxmint/cinnamon/issues/9806, https://github.com/linuxmint/cinnamon/issues/8257 and https://github.com/linuxmint/cinnamon/issues/7792 should now never happen.
Also, the second commit adds a code that saves maximum width and height of applet (see https://github.com/linuxmint/cinnamon/issues/9505)
=> keyboard applet refactoring

js/ui/applet.js
this param isn't used anywhere since 9 years: https://github.com/linuxmint/cinnamon/commit/1c0c12014b54af946f987b158d2858d62817dabb#diff-689b36b65982d3aa71863ab8941da57b10a5a6bfb2e68d004673f820102f2514L101
=> remove _hook from applet.js

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py, js/ui/accessibility.js, src/st/croco/cr-utils.c
In accessibility.js, there is a missing break in the switch statement.
In cr-utils.c, out_index + 4 is used twice, the second should have been
out_index + 5.
=> Fix a couple typos in latest code

data/theme/cinnamon.css, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
Adding ability to adjust a spacing between app groups via theme CSS. This is done as in window list applet but using following classes:
```
/* ===================================================================
* Grouped window list (grouped-window-list@cinnamon.org)
* ===================================================================*/
.grouped-window-list-box {
spacing: 2px;
}
.grouped-window-list-box.vertical {
spacing: 3px;
}
```
If there is no spacing defined in CSS, the old value of 6px is used.
Related to https://github.com/linuxmint/cinnamon/issues/10407
=> Grouped window list: Spacing is defined by CSS

js/ui/tooltips.js
This fixes a bug in which the text sometimes becomes off-center from the rest of the tooltip.
=> tooltip.js: trigger a relayout after triggering a reallocation

files/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py
On a fresh / YOCTO build raspi image with
* tzdata 2022a
* systemd 250.4
* a 'print(timezone)' added at line 260
the following log is created:
| using systemd backend
| Universal
| Traceback (most recent call last):
|  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 149, in _on_proxy_ready
|    self.proxy_ready_callback()
|  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 77, in _on_proxy_ready
|    self.tz_selector.set_timezone(self.zone)
|  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 263, in set_timezone
|    region, city = timezone.split('/', maxsplit=1)
|ValueError: not enough values to unpack (expected 2, got 1)
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
=> Do not crash on systemd/tzdata reporting Univeral timezone

files/usr/share/cinnamon/desklets/photoframe@cinnamon.org/desklet.js
This is the follow up to a previous pull request [10488](https://github.com/linuxmint/cinnamon/pull/10488)
The hidden files and files under hidden directories are skipped now.
=> photoframe: Avoid showing hidden files or files under hidden directories

files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
Fixes #10778 
The main fix is in the first commit: https://github.com/linuxmint/cinnamon/commit/1fb49a95d8391a5a2a2746aabaaed45ff2febfe5. If the desktop theme doesn't have the `audio-card` icon, an exception is raised and the device would not get added to the list. I didn't know what to use instead (does IconTheme have an appropriate icon we could use that's guaranteed to exist??), so I left it empty. This will result in text only with no icon.
I also noticed that this file had some style issues too, so I also refactored the file to:
- Use `is None` instead of `== None`
- Renamed local variables which were masking the built-in functions `type` and `id`
=> Fix: Missing icon causes output sound device to not show in list

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
There is no microphone icon at all when no mic is present and it gets stuck after connecting and disconnecting a microphone.
Note: This _isn't_ optimal since there could be a situtation when a program tries recording but no actual mic is present, but I Saw it is already being done with the mic sensitivity slider and so used that existing logic.
=> Sound applet: Hide microphone mute toggle if mic is not being used

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
This PR displays the current brightness value on the power applet while the user is dragging the brightness slider.
Relevant issue: https://github.com/linuxmint/cinnamon/issues/10622
=> [power] Show brightness text and value when dragging slider on power applet

js/ui/windowManager.js
After a completed or canceled workspace switch, the position of windows in the origin workspace were reset, but the positions of the windows in the destination workspace weren't. This is fine when the tween is allowed to complete because the window ends up right where it's supposed to be, but if the tween is canceled mid-animation (ie. due to another workspace switch), then the coordinates for those windows for the next animation are where ever the window happened to be when the previous tween was canceled, which in turn means that it ends up in the wrong spot. Resetting the position for the destination workspace windows fixes this issue.
=> windowManager.js: fix window placement after workspace switch animation

js/ui/popupMenu.js
Removing it caused a regression in the sound applet where the mpris player content wasn't properly destroyed when a player disconnected from dbus.
ref: e1bc6c6ea4523778b2fbc8ce15523a221b151a9b
=> popupMenu.js: bring back the call to actor.destroy()

debian/control, debian/rules, docs/reference/cinnamon/meson.build, src/st/meson.build
We may or may not want `st-background-effect.h` and/or `cinnamon-recorder.h` to be included in the docs in the future, but for now, docs without them is still better than no docs at all.
=> Fix docs and re-enable

js/ui/appSwitcher/classicSwitcher.js
This fixes a warning that two signal ids don't exist when trying to disconnect them
=> Don't disconnect signal ids that aren't connected

js/ui/popupMenu.js
This changes when the style class name is assigned for popup menus. Now it is done when the value actually changes instead of every allocation cycle.
=> Change style class name creation in popup menus

js/ui/runDialog.js
This breaks when you change to a larger font size since the dialog can't
resize to adapt to it's content.
Fixes: https://github.com/linuxmint/cinnamon/issues/10829
=> runDialog.js: Don't hardcode the size of the dialog content

files/usr/share/cinnamon/applets/menu@cinnamon.org/appUtils.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Remove calls to decomp_string() when sorting as both case and diacritics are ignored when using option sensitivity: "base" in localeCompare(). Diacritics in other scripts, diacritics from unicode block: Combining Diacritical Marks Extended and ligatures are also sorted correctly according to current locale.
Use .normalize('NFKD') in decomp_string() instead of .normalize('NFD') so that ligatures like 'ﬄ' are decomposed.
Use /\p{Grapheme_Extend}/gu instead of /[\u0300-\u036f]/g to remove diacritics in other scripts and unicode blocks.
=> Menu applet: Some slight improvements to app sorting and searching

js/ui/environment.js, js/ui/tweener.js, src/st/st-settings.c, src/st/st-theme-node.c, src/st/st-widget.c, src/st/st-widget.h
We ended up with part of this when porting to the new muffin. Finish the
implementation to fix a couple issues.
Fixes: https://github.com/linuxmint/cinnamon/issues/10895
=> st: Move slow-down-factor into settings

data/theme/cinnamon.css
Not exactly sure what happened to these but this gets the styling back in place.
=> theme: Restore the styling of gwl window thumbnails

js/ui/windowManager.js
This cleans up a bunch of log spam when restarting cinnamon.
See: https://github.com/GNOME/gnome-shell/commit/e8ab3bf53d1b7224c749ae8187fd64c21671cc59
=> windowManager: Check whether metaWindow is NULL after destroy animation

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
The overlayPreview actor was changed from a Clutter.Content to a
Clutter.Actor. That seems to require that we set the actual size of the actor
to the size of it's contents or we end up with a 0,0 size actor.
=> gwl: Restore the hover peek functionality

files/usr/share/cinnamon/cinnamon-settings/bin/util.py
This fixes the sound volume for channel tests and system sound previews. Before, it used the defined system sound volume which resulted in no output when system sounds are muted.
This restores the way this worked in Cinnamon 5.2
=> Fix testsound volume

js/ui/overview.js
Hiding it also hides our background actor. During animation the temporary
background we create to show in the overview fades out leaving us with only
the black stage visible. This leads to the appearance of flickering.
=> overview.js: Don't hide the global.window_group while animating

files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
When running the Account Details app directly ($ cinnamon-settings user), user is unable to change their user picture using the "Browse for more pictures..." option. This is because the Image submodule is not automatically imported with PIL (https://stackoverflow.com/questions/11911480/python-pil-has-no-attribute-image), and produces an " AttributeError: module 'PIL' has no attribute 'Image' " on line 204. This change is already present in cinnamon-settings/modules/cs_backgrounds.py
=> Imported submodule explicitly from PIL to fix bug

js/ui/popupMenu.js
Remove rtl workaround for the triangle arrow direction, It is no longer necessary.
Seems the direction is now inverted by default, so this workaround actually inverted it a second time to an incorrect orientation.
=> PopupMenu.js rtl arrow fix

data/theme/cinnamon.css, js/ui/locatePointer.js, js/ui/main.js, js/ui/ripples.js
We lost this in the rebase due to changes in how they are handled.
Reimplement them the new way and also allow them to be themed by the
Cinnamon theme. Also adding a new ripples.js that we can reuse for the
hot corners since this same functionality is now being used in more than
one place.
=> Reimplement the locate pointer functionality

js/ui/expoThumbnail.js
Fixes #10612.
The bug was caused by the function responsible for adding spaces between the thumbnails of a given row ignoring the fact the last row could have less thumbnails and, therefore, need less spacing, causing it to be off place.
=> Fix layout bug in expo view

man/cinnamon-session-cinnamon.1, man/cinnamon-session-cinnamon2d.1, man/gnome-session-cinnamon.1, man/gnome-session-cinnamon2d.1
Was spotted by lintian
This commit fix renaming gnome-session-* to cinnamon-session-* and
pointing
to cinnamon-session instead gnome-session
=> Fix 2 man pages

python3/cinnamon/harvester.py
The variable 'name' (yet undeclared) was being used instead of the one which was intended to be used, the variable 'author'
=> fix: wrong (undeclared) variable being used

js/ui/main.js
Function crashes because `Meta.Display.get_tab_list` do not require `Screen` as parameter anymore. [Link to docs](https://gjs-docs.gnome.org/meta7~7_api/meta.display#method-get_tab_list)
=> Fix getTabList in js.main

js/misc/gridNavigator.js
Fixes #11070.
The function responsible for managing the keyboard navigation in the expo or scale view, when pressing up or down, assumed the columns in the last row started at the same position as the other rows, even when it had less columns than the other rows, when in reality the last row is always visually centered.
The edge case of having less than 4 workspaces / windows was also modified because it cycled through cells in the opposite direction as when there are 4 or more workspaces, before and after the changes.
=> Fix inconsistent keyboard navigation in the Scale View and in the Expo View.

python3/cinnamon/harvester.py
The typo causes, that `old_version` might not be initialized in case of an `KeyError`.
In that case `activity_logger.log("%s %s %s %s %s %s" % (log_timestamp, self.spice_type, action, uuid, old_version, new_version))` would fail with an `NameError`
=> fix: variable name causing potential NameError

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
When "Group windows by application" setting is disabled:
- Could not drag and order pinned apps, it always caused the taskbar to refresh and other weird behavior. 
- New windows of an already pinned app would still show the "Pin to Panel" option.
Fixed that?
New windows of same app  open next to each other
Only refreshes (and lose all positions changes the user did) if pin/unpin and not on every drag&drop
The pinned apps get saved by the order the first instance occurs
=> gwl: fix reload dragging pinned apps when group windows setting is disabled

files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py
`GObject.SIGNAL_RUN_FIRST` is now deprecated and should be replaced by` GObject.SignalFlags.RUN_FIRST`
=> deprecated use of GObject.SIGNAL_RUN_FIRST

data/org.cinnamon.gschema.xml, files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
A vendor can disable this. It simply adds a Gtk Image under
the system info data which can be configured
by a gschema.
---
examples:
(Of course, the dimensions would have to be adjusted correctly by the vendor. I just downloaded these online, so like the LM logo would need configuring)
=> cs-info: Add system icon

files/usr/bin/xlet-about-dialog, files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, python3/cinnamon/harvester.py
The reason is to move stuff out of the `.cinnamon` directory for stuff to be eventually in XDG cache, data, state and config directories instead of just dumping them into the user's home directory.  
Users will need to redownload the cache, there are no other side effects.
=> Move spices download cache to `XDG_CACHE_HOME` directory

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
In NixOS, the module does not open with the default `system-icon-path` value:
```
Using pam module (python3-pampy)
Loading Info module
Traceback (most recent call last):
File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
self.side_view_nav(widget, None, category)
File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
self.go_to_sidepage(sidePage, user_action=True)
File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
sidePage.build()
File …
```
=> cs-info: Don't freeze with the default system-icon-path value

calendar-server/cinnamon-calendar-server.py, docs/search-providers-examples/trackerprovider@cinnamon.org/search_provider.py, files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py, files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py, files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py, files/usr/share/cinnamon/cinnamon-settings/bin/util.py, files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py, python3/cinnamon/harvester.py, utils/cinnamon-stap-monitor/cinnamon-stap-monitor.py
In python an identity (`is`) check should be used to check for `None`, instead of an equality check (`==`).
=> replace equality None check with identity None check

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
Mainly to not clutter up the user home folder when downloading themes, it was always creating `~/.themes`. `~/.icons` was created when a theme had extra icons.
Changes:
* Change themes install dir to `XDG_DATA_HOME/themes`
* when we initialize the `Spice_Harvester` we only ensure (create) the `install_folder` not the other directories
* Make sure the default icons dir is in `XDG_DATA_HOME`
Checked that themes still load from old location.
=> fix: Actually use `XDG_DATA_HOME` to download themes and icons instead of home

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
Changes in background settings:
* If `user-folders.lst` is at the new place it will use that, else it will use the one in the old location.
* When changed it will save into the new location, effectively orphaning the old one.
=> Use `XDG_CONFIG_HOME` to store background config files instead of .cinnamon

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py, js/ui/appletManager.js, js/ui/deskletManager.js, js/ui/settings.js, python3/cinnamon/harvester.py
Use `$XDG_CONFIG_HOME/cinnamon/spices` path to store configs instead of dumping them into `~/.cinnamon`. Code prioritizes the new path but it will still fall back to old path if config file only exists there.
I'm not removing/moving config files because that would cause more problems than be useful.
=> Use `XDG_CONFIG_HOME` to store spices configs instead of `~/.cinnamon`

files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js, files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py, files/usr/share/cinnamon/desklets/launcher@cinnamon.org/desklet.js, files/usr/share/cinnamon/desklets/launcher@cinnamon.org/editorDialog.py
So the custom .desktop files does not end up in `~/.cinnamon` but in the correct XDG folder. backwards compatible. Also fixed some bugs in the launcher desklet. 
Changes:
* use `XDG_DATA_HOME/cinnamon/panel-launchers` folder to save launcher configs, with a fallback when getting the config to the old path in .cinnamon
* Remove launcher desklet's right click->Add new launcher because it is very broken (desklet is added but it's never visually on the desktop so it cannot be interacted with) and new instances can be added from the desklets settings anyway.
* Make sure associated custom launchers are removed when a launcher desklet is removed
* When adding a custom launcher for the desklet name is not needed (it's greyed out) but without it it cannot be added. Fixed.
=> fix: use `XDG_DATA_HOME` to store custom launchers, also fix launcher desklet

files/usr/bin/cinnamon-launcher, files/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py, python3/cinnamon/logger.py
Although I've not seen any of these logfiles on my system.
glass.log entry was removed because it doesn't exists anymore.
=> Use `XDG_STATE_HOME` for logfiles instead of `~/.cinnamon`

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
I added `@staticmethod` to the methods `_is_bad_image` and `_sanitize_thumb`. These methods are static and there is no need for a `self` argument. 
I also added an missing comma in the documentation.
=> use @staticmethod in Spices.py

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Proposed solution for issue 11255
=> The middle click toggles the sound and places the microphone in the same state.

python3/cinnamon/harvester.py
This was forgotten in PR #11176 and results in many useless requests where thumbnails are redownloaded because they can't be found in the new location but are saved to the old one.
Can be easily tested with `DEBUG=1 cinnamon-spice-updater --list-simple applet`:
Without this PR `Downloading thumbnail for ...` is always shown, even if the images got downloaded seconds ago
This reduces server load by a lot and should be picked up before stable release of Linux Mint 21.1
=> LM 21.1: Fix old thumbnail cache folder

js/ui/appSwitcher/appSwitcher.js
Ignore smooth scrolling when using the mouse wheel to scroll between apps to prevent skipping windows.
Fixes #11396
=> appSwitcher: ignore smooth scrolling

python3/cinnamon/harvester.py
Instead of checking if `os.getenv("DEBUG") is not None` and then setting `DEBUG` to `True`, the result of `os.getenv("DEBUG") is not None` can directly be assigned to `DEBUG`.
=> simplify DEBUG detection harvester.py

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
On NixOS themes are installed in `/run/current-system/sw/share/{icons,themes}`
This makes theme thumbnail missing on NixOS because we don't search those paths. Let's follow https://freedesktop.org/wiki/DesktopThemeSpec/ and look for cursor themes and GTK themes in `XDG_DATA_DIRS`.
Screenshot on NixOS (cs_themes module - before changing any of the settings):
| Before | After |
|----|---|
| ![](https://user-images.githubusercontent.com/20080233/217859942-5b7b36c0-937d-470f-9f5c-d3834ba283f9.png) | ![](https://user-images.githubusercontent.com/20080233/217860243-6c130723-6329-44f0-a0ec-fb5a72bb7476.png) |
=> cs_themes: load theme thumbnail from XDG_DATA_DIRS

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
The applications section in the sound applet shows a generic icon for Firefox. This PR adds a special case for Firefox, so that the correct icon is shown.
Before:
After:
=> Sound applet: added special case for Firefox icon.

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js, files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js, js/misc/signalManager.js, js/ui/appSwitcher/appSwitcher.js, js/ui/appSwitcher/appSwitcher3D.js, js/ui/appSwitcher/classicSwitcher.js, js/ui/deskletManager.js, js/ui/expoThumbnail.js, js/ui/hotCorner.js, js/ui/layout.js, js/ui/main.js, js/ui/osdWindow.js, js/ui/overview.js, js/ui/virtualKeyboard.js, js/ui/windowManager.js, js/ui/wmGtkDialogs.js, js/ui/workspace.js, src/cinnamon-global.c
CinnamonScreen exists only for compatibility, as MetaScreen went away in 5.4.
Quite a bit had already been ported, but this gets rid of the remaining users.
CinnamonScreen itself still remains for xlets (though they should consider doing this eventually as well).
=> Stop using CinnamonScreen everywhere.

files/usr/share/cinnamon/cinnamon-settings/appearance-dark.svg, files/usr/share/cinnamon/cinnamon-settings/appearance-light.svg, files/usr/share/cinnamon/cinnamon-settings/appearance-mixed.svg, files/usr/share/cinnamon/cinnamon-settings/color_dot.svg, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py, files/usr/share/cinnamon/cinnamon-settings/themes.ui, files/usr/share/cinnamon/styles.d/00_cinnamon.styles
=> cs_themes: Add a simplified UI

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
- Setting the value of the applet settings parameter 'super-num-hotkeys' to false should now avoid registering the super+shift+number app launcher keybinds whereas it previously it only avoided registering super+number keybinds
- These changes should fix the unexpected behavior reported in #11393.
- You can read a further explanation of the issue below originally from my comment on the original issue.
> I erroneously reported this same error in the cinnamon applets repository a short while ago ([cinnamon-spices-applets#4634](https://github.com/linuxmint/cinnamon-spices-applets/issues/4634)). This also seems related to #10811 #9560. 
> 
> In my case, while it does seem to disable the `Super+<num>` keybinds when the settings value `super-num-hotkeys` is set to false it does not also disable …
=> Fix super+shift+number not disabling in grouped-window-list applet

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
When connecting a new monitor to the computer, the layout of the workspace-switcher applet would keep the same, now it will update whenever new monitors are added or removed.
=> workspace switcher applet: relayout when a new monitor is added or removed

data/org.cinnamon.gschema.xml, files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
The undefined `systemIconPath` variable generated an uncaught `NameError`. This prevented the Info window entirely from loading.
Should this also be appended to the 5.6-maintenance branch as a bugfix as well?
=> cs_info.py and org.cinnamon.gschema.xml: Fix undefined var and cleanup dconf strings

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
It seems that qt5 apps still rely on the directory **~/.icons** to display the icon theme for each user.
Fixes #11341, and fixes #11533
=> fix: cursor not changing for qt5 apps on settings

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Currently, `window-list` applet uses a hardcoded minimum window button width when "use the entrie space available" setting is checked.
This fix makes it use the "Window button width" setting as the minimum instead.
I personally set width to zero, to make the buttons only as wide as their text. Leaving it at the default 150 results in keeping the current behavior.
=> window-list: make UseEntrieSpace honor buttonWidth

files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py
ref:
linuxmint/cinnamon-desktop@a573e21850723edbe5ab149ef2c1265d16f0bf02 linuxmint/cinnamon-settings-daemon@66a86cfabd33b6bc0006f5a88f8b6e1618f5cc82
Fixes #11358
=> [5.8] Expose middle-click paste setting.

files/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/calendar@cinnamon.org/settings-schema.json
Currently only the main date format is configurable if the custom format is activated. This PR makes the date that is shown in the tooltip configurable too.
=> Calendar Applet: Custom Tooltip Date Format

js/ui/popupMenu.js
PopupMenu Content should be using the full size of the popup menu even after content has been resized.
See picture:
The horizontal lines are simple separators added to the PopupMenu. They should be spanning full width, but they don't.
Steps to reproduce:
* Cinnamon 5.4+
* Weather Applet, than right click-> Refresh. Open the applet before the refresh finished.
Explanation:
The menu must be open for this to happen. The menu starts out with data already filled in. In the weather applet in full refresh, the menu content gets rebuilt and starts out with the same layout, but without data. Because of that, the total size will be smaller. When the elements get filled up with actual data, the size remains the same even if it should expand.
Notes: 
* Maybe there is a problem on how I construct the …
=> fix: Popup menu content not stretching to its full size on rerender

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
Fixes https://github.com/linuxmint/cinnamon/pull/11175#issuecomment-1457237711
=> Revert to `~/.themes` and `~/.icons` directory as default instead of XDG equivalents because GTK2 apps couldn't use them

js/ui/layout.js
This prevents errors when no display is found (e.g. turned off monitor) during login after screensaver
**Steps to reproduce the exception**
- Lock the screen
- Turn off your display
- Enter some text/password
- Turn on your display
- `.xsession_errors` shows the following exception without this PR
```
(cinnamon:2273): Gjs-WARNING **: 18:46:27.661: JS ERROR: Exception in callback for signal: monitors-changed: TypeError: this.findMonitorForActor(...) is undefined
_updateVisibility@/usr/share/cinnamon/js/ui/layout.js:652:27
_relayout@/usr/share/cinnamon/js/ui/layout.js:675:14
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_monitorsChanged@/usr/share/cinnamon/js/ui/layout.js:216:14
```
=> layout.js: Check existence of monitor before usage

.github/workflows/build.yml
This depends on xapp being built against a bookworm base so that 2.5.0 can be built successfully first.
=> build.yml: Add xdg-desktop-portal-xapp dependency

js/ui/notificationDaemon.js
If no icon is defined, use a symbolic icons.
If an icon name is defined, try to load its symbolic alternative first, then fallback to fullcolor.
Themes might want to use colors in notifications, symbolic icons work on any colors, fullcolor ones do not.
=> notifications: Prefer symbolic icons

js/ui/main.js
I was evaluating `Main.gpu_offload_supported` in Melange and found it undefined. Probably this is removed in 00b0a65b by accident.
I have `JS LOG: [LookingGlass/info] GPU offload supported: true` in my journal and with this change I can see the "Run with dedicated GPU" item in menu.
---
Screenshot of the menu, journal, melange, etc (**after** this change):
<details>
</details>
---
I am aware 5.8.0 is not tagged but I am playing this myself (on NixOS) :-) If "Run with dedicated GPU" is expected to present without this change, here are some info of my setup.
- I am on 93135ed3741cab016b75a91a03c1fc9b48ec70b4.
- `switcheroo-control.service` is running
- ```
$ xapp-gpu-offload -l
1 default DRI_PRIME=pci-0000_00_02_0  [Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]]
0 …
```
=> main.js: re-declare Main.gpu_offload_supported

src/main.c
Without this, values set by the user will be ignored.
Fixes #11673
=> Save/restore NO_GAIL and NO_AT_BRIDGE environment variables (#11673)

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json, js/ui/applet.js, js/ui/dnd.js
This is a follow up to PR #11665 that just merges the commits.
=> Add PopupResizeHandler class and make menu applet resizable.

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, js/misc/util.js
Applet panel text (song information) is truncated by js string length resulting in multiple codepoint characters, e.g. emoji, being shown incorrectly. Count string length and truncate string by unicode grapheme cluster (glyph) instead.
fixes #11691
=> Sound applet: Truncate applet panel text by glyph

data/theme/cinnamon.css
=> Cinnamon theme: allow different text sizes in menu applet search box

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
Fix menu changing size after reopening by using main_container to size the menu rather than menu.actor
fixes: #11712
fixes: https://github.com/linuxmint/mint21.2-beta/issues/6
I've also adjusted the default sizes so that the menu is about the same size in Mint-Y theme as it was before this change.
=> menu applet: fix menu changing size

files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
Don't change category button style on button leave event when search is active and "change categories on hover" option is off.
=> menu applet: fix category button styling bug

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
Fixes spaces in repo-URLs
Steps to reproduce: `cinnamon-settings info` -> "Copy to clipboard" -> Paste it somewhere
Before:
```
Repos:
[...]
Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
1: deb http: //packages.linuxmint.com/linuxmint/packages victoria main upstream import backport
2: deb http: //packages.linuxmint.com/ubuntu jammy main restricted universe multiverse
3: deb http: //packages.linuxmint.com/ubuntu jammy-updates main restricted universe multiverse
4: deb http: //packages.linuxmint.com/ubuntu jammy-backports main restricted universe multiverse
5: deb http: //packages.linuxmint.com/ubuntu jammy-security main restricted universe multiverse
```
With this PR:
```
Repos:
[...]
Active apt repos in: …
```
=> cs_info: Fix space in URLs

files/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
fixes https://github.com/linuxmint/mint21.2-beta/issues/26
I think when I chose the default size I was using a larger font size and had more category buttons, but with default theme/fonts, it does seem a bit big. Maybe these sizes are more reasonable?
Note that these numbers are smaller than they would have been before #11720 because they no longer take into account menu border/padding etc.
=> Menu applet: Reduce default menu size

files/usr/share/cinnamon/cinnamon-settings/modules/cs_gestures.py
* Remove unnecessary semicolons
* Clean up whitespace
* Use f-strings for string interpolation
* Use `enumerate` to generate a counter for an iterable
* Clean up conditional block to use map and return structure for improved readability
* Remove unused exception variable
* Clean up comparison to `None`
* Remove unnecessary `.keys()` call
=> cs_gestures.py: Cleaning up Python

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py
I added a condition in set_button_label because if we set has_button_label to False and then use set_button_label, we will encounter an exception.
> kacper@kacper-VirtualBox:~$ cinnamon-settings themes
> /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
>   self.window.set_wmclass(wm_class, wm_class)
> Loading Themes module
> /home/kacper/.local/share/themes does not exist! Skipping
> Mint-Y-Sand
> dupa
> Traceback (most recent call last):
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 793, in <module>
>     window = MainWindow()
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 314, in __init__
>     if self.load_sidepage_as_standalone():
>   File …
=> To fix the error of referencing a non-existent variable.

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
1. Go to any workspace but the first one
2. Reload the grouped-window-list applet
3. Go to another workspace
4. Try to move the pinned apps in the grouped window list applet (It will probably not work)
5. Try to drag any app from the menu and drop in the grouped window list (It will also not work, probably)
---
I've also fixed https://github.com/linuxmint/cinnamon/issues/8534
=> grouped window list: fix drag and move app icon on the app list

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
In the "preferred applications" labels are aligned to up (START), i changed it to CENTER now.
Before
After
=> Align labels in rows in the preferred applications to center

js/ui/overview.js, js/ui/workspace.js
The hidden windows were being shown before the end of the overview animation. Now the window will return to its original place before the real hidden window is shown in place.
May fix https://github.com/linuxmint/cinnamon/issues/11373
=> cinnamon ui: improve overview animation

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
added a settings update for x.apps.portal.color-scheme that follows the theme mode from the new (from 5.8) simplified themes view
=> color-scheme follow simplified themes

data/theme/cinnamon.css
This is similar to existing Mint-X and Mint-Y themes in mint-themes and center aligns the time value in the Calendar applet.
Similar to linuxmint/mint-themes#452
=> cinnamon.css: Center text in .applet-box

js/ui/lightbox.js
Fixes: #11753
Before:
After:
before, close up & increased contrast
after, close up & increased contrast
=> lightbox: Reduce color banding by adding random noise (dithering)

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
With this change, I don't have #11106 happen anymore.
For me, the bug happened whenever a window is created while the hover menu is open.
Thumbnails objects were being created and added to the list of thumbnails in the `AppThumbnailHoverMenu`. However, then `refreshThumbnail` is called, which calls `getThumbnail`. In `getThumbnail`, `metaWindowActor` is still null and `metaWindow.get_compositor_private` returned null, causing it to remove the thumbnail again before it was ever visible.
With the `setTimeout(..., 0)`, `getThumbnail` is called on the next event loop turn, so that the actor will be returned by `get_compositor_private`.
If the menu isn't open when the window is created, then the window is added to the `queuedWindows` array and added later on when the actor is available.
I …
=> Fix thumbnails not appearing for windows created while menu is open

js/ui/applet.js
The formatting was all wrong in cinnamon-doc.
=> applet.js: Improve code comments.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
Now in the system information the os name is taken from os-release, which is more correct and universal
=> Updated cs_info module

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
Telegram desktop audio player send negative seek value after 35:55.  In melange log i see value like this -2147308296. After that player skips to the begin. To solve that problem I added Telegram desktop in list of players without seek support. https://github.com/telegramdesktop/tdesktop/issues/23892
=> Add Telegram desktop to list of players without seek support.

js/misc/fileDialog.js
Minor optimization. There is on need regexp for single char.
=> js: Use string instead of regexp

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
All modules, when called as standalone (via menu), were too small (in height). I added the missing variables and called the calculus function in this case.
Before:
After:
=> Fixed calculate a sidePage height when it comes as standalone

files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py
Fix bug where toolbar disappears if the window is too narrow.
As the settings window Toolbar only contains one ToolItem, this ToolItem can disappear if the window is too narrow and Toolbar:show-arrow property is set to true. Set Toolbar:show-arrow to false to ensure that the window will expand to accommodate the full width of the Toolbar.
ref. https://github.com/linuxmint/cinnamon-spices-applets/issues/5065
=> xlet-settings.py: Ensure settings window expands to fit toolbar

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
The PR https://github.com/linuxmint/cinnamon/pull/10620/ hides the input switch, if no recording device is open. But let's say you want to mute your microphone before starting a video session, you need that input switch _before_ you start the conference software!
This adds a switch to the configuration screen to always enable the input switch. The default is the old behaviour: Only show it, when a recording device is open. (But you may want to change that.)
This is based on the commit
https://github.com/linuxmint/cinnamon-spices-applets/commit/670c97dc987c42b8c13da9d8cb034bd0f080577a for the sound150@claudiux spice. Thanks @claudiux!
=> Adds option to always show the input switch in the sound applet. (Closes #11232)

files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py
g_settings_bind: property 'reveal-child' on class 'xapp+SettingsWidgets+SettingsRevealer' has type 'gboolean' which is not compatible with type 'i' of key 'notification-fixed-screen' on schema 'org.cinnamon.desktop.notifications'
=> Fix GLib exception:

files/usr/share/cinnamon/cinnamon-settings/modules/cs_gestures.py, js/ui/gestures/ToucheggTypes.js, js/ui/gestures/actions.js, js/ui/gestures/gesturesManager.js, js/ui/magnifier.js
ref: https://github.com/orgs/linuxmint/discussions/102
=> gestures: Allow the user to specify which phase of a gesture should trigger its action.

data/wayland_sessions/cinnamon-wayland.desktop.in
This renames the wayland session to "Cinnamon on Wayland (Experimental)" to make it clear that this is not production-ready yet.
=> Rename Wayland session

files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
When there exists a "list" with a column containing an options set and the column is not the last column defined, the content for that column in the list will be displayed incorrectly. The content displayed will always be based on the last column content rather than the content matching the column index.
Since the map function will only be executed after the 'for' loop has finished, the index in the enclosing scope will always be the index of the last column rather than the index of the expected column. Therefore using the enclosing scope index will cause the map function to use incorrect model data when setting the list column content, unless the column happens to be the last column in the list.
This fix will pass the index variable into the map function as part of the func_data …
=> Fix xlet-settings TreeListWidget's handling of columns with option lists

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
This patch changes the window list applet config to use a menu to choose the behaviour when hovering over a window:
The existing behaviours (window title or window thumbnail) are offered, as well as a new "nothing" option which disables any kind of tooltip.
My personal motivation for this is that when I am switching to a terminal window, it's natural for me to leave the mouse cursor on the terminal window's icon in the window list, but that means the tooltip obscures the bottom part of the terminal window I'm typing into. This is similar to the concerns raised in https://github.com/linuxmint/Cinnamon/issues/4549. I hope you'll agree that this patch doesn't make the user experience worse for those who like the tooltips while allowing an unobtrusive way to disable them.
There has been …
=> Allow "no tooltips" on the window list as well as the existing "title" or "thumbnail" options

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
In the edgecase of the charge/discharge seconds var being the magic number 3600, the power applet will erroneously report `0 minutes remaining` as the conditional statement will not take exactly 1 hour into account, with the time var equaling 60.
This PR fixes issue #11930
This is my first time committing to the Cinnamon repo, so any pointers are highly appreciated!
=> Fix the power applet battery status when the seconds var is 3600

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/sound@cinnamon.org/settings-schema.json
When discussing the MuteToggler@jebeaudet.com spice in https://github.com/linuxmint/cinnamon-spices-applets/pull/5090, we noticed that most of its functionality is already there. I noticed that it might be a good idea to be able to start/stop the player but also mute/unmute the microphone directly with the mouse without diving into the right-click menu. So I added a option for shift-middle-click very similar to the middle-click option.
=> Adds a shift-middle click action to the sound applet.

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
I'd like to suggest to improve the Applet, Desklet and Extension download icon. Since Mint 21, it does not look like a download button anymore (more like a dropdown menu) which is confusing for new users.
Furthermore, the execute button in the autostart settings looks more like "edit" or "settings" instead of an "execute now". That's why I suggest to display a play button instead.
=> Improve settings icons

js/ui/main.js
If a window has a transient child of type Meta.WindowType.NORMAL the behaviour of Main.activateWindow() will be to bring the transient window into focus rather then the window that was requested (i.e. the window of the 'window' parameter).
The change that introduced this behaviour (#1266) was intended to ensure that when the "Open file" dialog for gedit was already open and the user switched back to the gedit window, the transient "Open file" dialog should come to the foreground and have focus. In most cases this is the best action to take since the transient window does not have an entry of its own in the window list (i.e. Alt-TAB) and therefore can't be activated by the user any other way, and in most cases it's exactly what the user wanted anyhow.
But in cases where there is a "normal" …
=> Fix Main.activateWindow() for windows with normal transient children

files/usr/bin/xlet-about-dialog, files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py, files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Manually installed Actions outside of the Spices structure will be displayed with a lock icon and have the About and Uninstall buttons disabled but have support for enabling/disabling from within the module.
=> Update Actions module to show non-Spice Actions

files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
Add a third 'x' option to the inxi command so it will also provide the partitioning scheme for drives. It is useful for people helping with installation or boot issues to know upfront whether GPT or MBR is used.
Also adds the 'J' option to make inxi provide information about USB devices, to put it on par with the information mintreport provides.
=> Update cs_info.py - increase inxi verbosity

js/ui/tooltips.js
*(I'm not hyper-familiar with the logic of cinnamon, and I've not used javascript much for anything before...* ***But!*** *Unless I've missed something important, this fixes the problem.)*
**Before:**
**After:**
( fixes #11978 )
=> Fixes panel tooltips clipping outside the screen when the applet is close to the bottom.

js/ui/tooltips.js
**Hi!**
This is somewhat of an addition to my previous commit. ( #11980 )
The same issue of tooltips clipping outside the screen when the applets were very close to the bottom, was also occuring when the tooltips were close to the top of the screen as well.
Unlike the previous one, this doesn't happen with the default panel layout.
Yet, it's still a possible scenario, (if you edit the panel, and put a cornerbar at the top, for example), so now it's fixed too.
**Before:**
**After:**
=> Fixing tooltip clipping for applets close to the top of the screen as well.

files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js, files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Clearing the attention flash on an already focused window was unintuitive, since it would require the user unfocusing the window and focusing it again.  Since the user is already focused on the window, we don't need to flash for its attention in the first place.
=> window lists: don't attention flash focused window

files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py
**Description:** 
This is a simple proposal for a UI/UX inconvenience I personally came across when using the _Startup Applications_ app. I've tested it and this addition fixes this problem. This change should be easy to test as it is just one added line, after which the Startup Applications app can be opened again to see the change.
**Background:**
I've often wanted to add an application to the Startup Applications. Unfortunately, there was no indication that I could search the list. The current behavior is that the search bar will only appear once you type in a character. I did not know that a search bar existed in this window until I've looked at the source code (this should say a lot :sweat_smile:).
This is not a great UI/UX behavior in my opinion, as many search implementations …
=> Show search bar by default when choosing an application in Startup Applications

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
When the laptop battery is neither being charged nor discharged (eg: when a battery conservation mode is enabled, the AC adapter is plugged in, and the battery reached its intended charge level) the power applet incorrectly reports "Using battery power" when the laptop is actually running on AC power. It can also incorrectly report this when the battery state is actually unknown. This PR fixes that.
-----
Incidentally, i think the status "Using battery power" is incorrect and should just be "Charging". This line is the status of a particular battery (of which there could be many) and not the status of the PC. For all other status values the subject of the status phrase is the battery, but for this one the subject seems to be (incorrectly) the whole PC.
A status line could be added above …
=> power applet: Fix reported battery status

files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js
1. display the whole Timestamp-String including the Date, as the pure Time of Day is useless when looking at a Notification from several Days ago
2. use the User's Locale instead of a Flag "use_24h", moreover as this Flag is not Part of the App's Configuration-Settings
=> Improve Timestamp for Notifications

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
When hiding the stack switcher we need to set both the opacity and sensitivity. Otherwise the buttons can still be clicked even when they are hidden.
Fixes: https://github.com/linuxmint/cinnamon/issues/12115
=> cs_themes: Fix the stack switcher sensitivity

files/usr/share/cinnamon/applets/inhibit@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-active-notifications-disabled-symbolic.svg, files/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-notifications-disabled-symbolic.svg
Closes #11228 
@BrunoNZ This completes the functionality originally proposed in #11228. I hope you're okay with the finished product.
=> inhibit@cinnamon.org: Add unique applet icons for notification toggles

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
* Removing trailing whitespace as well
=> cinnamon-settings.py: Additional modules when Mint modules are absent

files/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
Fixes #11313. When the applet was used in a vertical panel it would appear blank at first, until the mouse cursor was hovered over it.
Calling _syncGroup directly from _syncConfig, instead of using idle_add fixes the problem.
Doing so should not cause any problems though. Both _syncGroup and _syncConfig are signal handlers. So there should not be any threading issues necessitating the use of idle_add.
=> Fix #11313

files/usr/share/cinnamon/cinnamon-settings/bin/KeybindingWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
This implements an additional option that enables searching by a specific keyboard binding. The user input is a single binding sequence and the search recursively finds existing matching entries and displays results similar to the search by shortcut name, including markup.
=> cs_keyboard.py and KeybindingWidgets.py: Add support for search by binding

files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/settings-schema.json
Allow to set different actions on `shift + click` and `shift + middle click` actions.
=> cornerbar applet: add shift + click actions settings

files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/cornerbar@cinnamon.org/settings-schema.json
To filter the desktop window from the others that should have been opacified and blurred, previously, the window title was being used to check if the name of the window was or was not equal to "Desktop", that won't work for all localizations because the title of the window "Desktop" will be translated to another thing in other languages (e.g. "Área de Trabalho" in Portuguese), so the filtering would not work.
This PR proposes instead to check the window type, which is a more reliable method to check whether the window is a desktop window.
\+ Also filter **dock** type windows (like **plank** or **latte**) they shouldn't be transparent as well on peek
=> cornerbar: Properly filter windows not to transparentize on peek blur/opacity effects

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Preserve original file permissions of all files in downloaded spice zipfile. This is an improvement on commit https://github.com/linuxmint/cinnamon/commit/42b1e53ef4ae0d26df7a8e8f588cdcfd47be2b12 which give all files the same permissions.
=> Spices.py: Preserve original file permissions of downloaded spices

data/theme/cinnamon.css
remove fixed width and adjust height.
before:
After:
=> cinnamon theme: fix expo-workspaces-name-entry

files/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/applet.js
This adds a toggle switch to the context menu of the `on-screen-keyboard@cinnamon.org` applet. This switch enables and (more importantly) disables the on-board keyboard.
=> Adds toggle switch to on-screen-keyboard@cinnamon.org (Closes #11974)

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
Replace default network connection icons with ones with a padlock when a user is connecting/connected to a VPN. This allows to quickly check if a VPN is connected by the appearance of a network connection icon.
This should resolve linuxmint/cinnamon#5527
=> Show "wired with a padlock" or "wireless with a padlock" icons when a VPN is connected

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
**Closes #11847**
This patch prevents application "Muffin" (Cinnamon's window manager) from showing up in the volume mixer of the `sound@cinnamon.org` applet when scrolling up and down with the middle mouse wheel.
Tested and working on X11/Wayland on the following versions:
- LMDE 6 (Cinnamon version: 6.0.4)
- Linux Mint 21.3 (Cinnamon version: 6.0.4)
- Latest git version of Cinnamon (compiled using mint-dev-tools)
=> sound@cinnamon.org: Prevent Muffin from showing up in volume mixer (Fixes: #11847)

files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
=> [sound@cinnamon.org] Prevents Cvc.MixerControl from being loaded more than once

js/ui/popupMenu.js
Most of the time this just makes the sliders look poor. The menu item itself isn't really doing anything on click. It just makes more sense not to apply a hover style on these items.
=> PopupSliderMenuItem: Don't track the hover state

files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
Hi!
This adds an option to remove the `[ ]` and `|` indicators on minimized/tiled windows (I'm not personally a fan, was also confusing figuring out why these were being added at first).
Setting:
Cheers
=> window-list: Remove indicators for minimized and tiled windows from window names

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
The extension reload signal was being triggered automatically in the end of the installation process, but this only should apply if the extension was already enabled before (maybe after an update of an already installed extension I guess).
fixes https://github.com/linuxmint/cinnamon/issues/12075
=> extensions: Fix auto-enable on download

files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py
Some language codes are only available as translations via their long language code format. This will check for the more precise long language code first before looking for the shorter and more general variation. This will improve translation support for how Spices modules are displayed before being installed locally.
cc @aaasoft
=> ExtensionCore.py: Check for display names in translations

docs/applets-examples/finder@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js, files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js
This prevents the view from being clicked/selected when outside of the visible viewing pane.
Closes #11123
=> Set clip_to_allocation to true for menu and notification applets

js/ui/applet.js, js/ui/dnd.js
Revert a workaround added in commit https://github.com/linuxmint/cinnamon/pull/11688/commits/c5af58b2d4ccc4258494bf7127e8097a9fb92aef that prevented a dnd bug https://github.com/linuxmint/cinnamon/pull/11665#issuecomment-1557253018
The original bug https://github.com/linuxmint/cinnamon/issues/11123 that caused this bug has now been fixed so this workaround is no longer needed.
Edit: btw, this doesn't necessarily have to be merged for cinnamon 6.2 as the workaround now effectively doesn't do anything.
=> Dnd.js: Revert bug workaround

files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
fix https://github.com/linuxmint/mint22-beta/issues/42
@mtwebster @clefebvre if you could give it a look at this, it would be nice if this was patched before the stable release.
=> cs_themes: Enable stack switcher when navigating out the theme module

data/theme/cinnamon-sass/widgets/_osd.scss, js/ui/osdWindow.js, js/ui/workspaceOsd.js
Was using the entire monitor size to place this. Use the monitors available work area instead. This will ensure the OSD's are placed the same distance above the panel regardless of the panel size.
=> OSD Windows: Use the monitor work-area to place windows on screen

data/meson.build, meson.build, meson_options.txt
Add options to disable installing wayland session and xdg-portal files. Cinnamon shouldn't advertise having wayland sessions if the rest of the packages are built without wayland support.
I didn't see a good option for handling `cinnamon-session-cinnamon` without a more significant refactor. But fortunately `cinnamon-session` aborts with an obvious error message
```
$ cinnamon-session-cinnamon --wayland
cinnamon-session-binary[25984]: CRITICAL: t+0.00369s: Unable to start session: Failed to load session "cinnamon-wayland"
```
=> Optionally install wayland session files

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
It is possible to remove Spices manually by removing the associated directories rather than using the appropriate module. This results in the bindings still being stored internally. When loading the Keyboard module and this scenario has occurred, it results in a failure due to the matching files having been removed. We leave the mappings internally so that if the matching Spice is reinstalled, the previous settings will be retained.
=> cs_keyboard.py: Skip invalid bindings

files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py
If a panel definition exists for an inactive monitor, launching the panels settings menu will fail.
In `id_or_monitor_position_used` we check if a position is used by going through monitor_layout[monitor_id]. This can result in an index out of range error if the length of monitor_layout is not greater than monitor_id. See https://github.com/linuxmint/cinnamon/issues/12378 and https://github.com/linuxmint/cinnamon/issues/12397.
To reproduce:
1. Go to the display settings menu and disable a monitor with a panel (or simply unplug a monitor with a panel)
2. Attempt to launch the panels settings menu
This implementation does not remove the panel definition and it will still be available when the monitor is re-attached.
=> cs_panel.py: Error handling for panels on unavailable monitors

data/theme/cinnamon-sass/widgets/_osd.scss, js/ui/windowManager.js
Reusing the info-osd class is convenient but doesn't always give what we want. Add a unique style class to allow theming this independently
=> windowManager: Give the resize popup it's own style class

js/ui/environment.js
Make cjs to compute the GType name for registered GObject-derived classes using the file basename and the first directory name, so that we can avoid name clashing, and ensure that no xlet will break cinnamon by registering a name that is already used (by cinnamon or by any other extension).
=> environment: Use cjs smart GObject GTypeName computation

js/ui/popupMenu.js, js/ui/windowManager.js
Currently the menu animates a distance of 1/10 the menus height/width. This leads to some menus having a bit different animation then others. Switch to using a hard coded distance instead. With the smaller distance we can also now remove the set_clip() that is being used. That hurts performance, especially on HiDpi. That was being updated on every update of the tween. It also clips out any box shadow that the theme is using on the menu as a side effect.
With the smaller amount of translation happening in the menu, slow down the speed of the animation just a bit. This results in the overall animation looking very similar to how it did before.
=> popupMenu.js: Simplify the menu animation

js/ui/layout.js
Auto hide panels do not effect a monitors work area. When using the monitor contraint to position elements on screen, they can end up overlapping with those panels. Take the area those panels will cover when shown into account.
=> layout.js: Consider auto hide panels in MonitorConstraint work area

js/ui/messageTray.js, js/ui/notificationDaemon.js
Ensuring that notification states are immutable helps prevent any unwanted or accidental modifications.
=> make notification states immutable

files/usr/share/cinnamon/cinnamon-settings/bin/capi.py
Platforms like  `arm64`/`aarch64` also use `/usr/lib64`, so don't restrict it to `x86_64`/`amd64`.
One additional path check is probably not worth enumerating all of the applicable machine names.
=> Simplify 64bit path handling in cinnamon-settings

files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
When there are more than `NUM_VISIBLE_NETWORKS` total networks, there should be exactly `NUM_VISIBLE_NETWORKS` visible networks. This pull request contains two commits aimed at fixing different scenarios in which there are more than `NUM_VISIBLE_NETWORKS` total networks but where the number of actually visible networks may be more than `NUM_VISIBLE_NETWORKS` or fewer than `NUM_VISIBLE_NETWORKS`. I was especially motivated to make these fixes because, on lower resolution displays, if many more networks than `NUM_VISIBLE_NETWORKS` are displayed, the menu may exceed the size of the screen and some networks may not be easily selectable.
=> network applet: fixes to # of visible networks

files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py
The gnome-backgrounds project uses jxl files for many backgrounds. 
https://gitlab.gnome.org/GNOME/gnome-backgrounds
Unfortunately the Cinnamon Backgrounds module doesn't render these correctly. Causing blank sections for many of the Backgrounds. The python `Image.open` call doesn't support them yet, even with libjxl installed.
This patch merely adds support for `image/jxl` files and makes sure they render correctly.
=> Fix jxl file previews in cs_background.py

files/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py, js/ui/messageTray.js
In tandem with linuxmint/cinnamon-desktop#233.
Closes #9529
=> messageTray.js and cs_notifications.py: Add an option for showing notifications in fullscreen

files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
Any applications that support/implement the
org.freedesktop.UPower.PowerProfiles system bus will now integrate with the power applet.
=> power@cinnamon.org: Add support for freedesktop.org PowerProfiles DBus

files/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py
`GTK2_RC_FILES` is an environment variable containing a colon seperated list of RC files that are used to theme GTK2 applications. This patch will write GTK2 theming to the first file in this list, if present, rather than ~/.gtkrc-2.0.
=> Respect `$GTK2_RC_FILES` when writing themes

js/ui/panel.js
The goal is to fix https://github.com/linuxmint/cinnamon-spices-extensions/issues/749 for the extension mouse-click-effects.
The extension allows the user to put an icon below its cursor pointer to perform animations or follow the cursor pointer.
I use a **St.Icon** with the **reactive** attribute **set to false** but still it is interfering when right-clicking the panel to open the panel menu, though this does not happen when right-clicking an applet to open the applet menu.
When receiving a right-click event the panel verifies if the click target was indeed the panel directly or another component before showing the menu (I suppose to avoid opening when right-clicking applets), for that, it will pick the actor in the position of the click, but even though the **St.Icon** I have it is …
=> panel.js: Only pick reactive actors on validating right click target

js/ui/appletManager.js, js/ui/modalDialog.js
Totally missed these in the first go around. Also fixes and error in the NotifyDialog.
=> appletManager: Clean up a couple more modal dialogs

data/theme/cinnamon-sass/widgets/_base.scss, data/theme/cinnamon-sass/widgets/_dialogs.scss, js/ui/main.js, js/ui/polkitAuthenticationAgent.js
Only show user choices if there is more than one available admin user and the current user is not an admin. With this support added, enable the dialog by default.
=> polkitDialog: Support multi-user selection

files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
Ref #12354.
Assignment to `_` was almost certainly unintended in the line `_ = dialog.run()`, and has been removed.
As is, the code forced `_` to be recognized as a local (see https://stackoverflow.com/questions/370357); in the case where a non-`None` value is passed, this would mean that `_` is used before assignment.
Context implies that `_` is supposed to be a globally defined function, but further implies that the result from `dialog.run` *should not* replace that value.
Most likely, the original code was assigning to `_` for debugging purposes (i.e. so that the local value could be examined in a debugger), and the name collision was unintended.
=> Fix crash when attempting to report an error in the UI with details

data/theme/cinnamon-sass/widgets/_keyboard.scss
Use em to set the button size. This allows the size to adjust when the keyboard size is changed. Also fix the boxpointer menu that holds the subkeys.
Fixes: https://github.com/linuxmint/mint22.1-beta/issues/25
=> theme: Fix missing text on virtual keyboard

data/theme/cinnamon-sass/widgets/_windowlist.scss
Fixes rounding in window previews when hovered. Also add a margin to give the window preview the same distance from the panel as menus.
https://github.com/linuxmint/mint22.1-beta/issues/23
=> theme: Fix rounding and spacing in GWL window previews

data/theme/cinnamon-sass/widgets/_dialogs.scss, js/ui/dialog.js
Fix spelling error in class name.
related: https://github.com/linuxmint/mint-themes/pull/486
At least I assume it's a mistake?
=> dialog.js: Fix spelling

js/ui/panel.js
Panel clipping occurs to prevent a hidden panel from being visible on an adjacent monitor edge. In some monitor configurations it can affect actor event picking, and the enter-events that trigger panel visibility are missed.
Regardless of the pick problem, clipping should only be necessary if:
- There's more than a single monitor.
- There is at least a partial common edge shared by two monitors.
- There is an auto- or intelligently-hidden panel enabled on that edge.
ref:
https://github.com/linuxmint/mint22.1-beta/issues/28
https://github.com/linuxmint/mint22.1-beta/issues/74
more...
=> panel.js: Only clip the panel size if necessary.

js/ui/dialog.js
Allow themes to style the dialog buttonlayout. This is a replacement for the old modal-dialog-button-box class style. Without it, themes like Numix-Cinnamon-Transparent, New-Minty, and Vertex-Maia will not be able to style the button box separately.
=> dialog.js: add style class dialog-button-box

data/meson.build, data/theme/cinnamon-sass/meson.build, data/theme/meson.build, data/theme/parse-sass.sh
`run_command` runs silently and the build log does not indicate that the command was run, or what the command was, so it's not great for build debugging. On the other hand, `custom_target` logs as a normal build target.
```
[9/113] /usr/bin/pysassc ../cinnamon-6.4.3/data/theme/cinnamon-sass/cinnamon.scss data/theme/cinnamon-sass/cinnamon.css
```
`run_command` also states that it runs in an unspecified directory, so the current script is relying on undocumented implementation/platform specific behavior. Rather than updating the script to ensure it runs in the proper directory, `custom_target` does this for us (and handles installs since it enforces the source/build separation).
Also support both pysassc and sassc (which was the reason I was in here in the first place X_X). The only …
=> [Next] Move sass compilation to its own custom target

js/ui/gestures/actions.js
This was missed during the port to the new OSD. Using gestures to change the volume was also always using the max amplified volume. Fix this to respect the users setting while we are at it.
Closes: https://github.com/linuxmint/cinnamon/issues/12646
=> gestures: Show the OSD when using gestures to change volume

js/misc/signalTracker.js, js/ui/environment.js
This provides a much easier and simpler method for managing and cleaning up signals. Have been using this locally for awhile in multiple WIP projects.
https://github.com/GNOME/gnome-shell/commit/f45ccc9143b21a51aa7677252276aec7d4220a72
=> Port dis/connectObj from gnome shell

js/ui/notificationDaemon.js
This pull request addresses issue #12777 by adding a check to avoid passing an already valid file URI to `GLib.filename_to_uri`.
=> notificationDaemon: Fix handling of `image-path` hint

files/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
Workspace switcher: Workspaces will be always displayed as empty when they are, in the “Simple buttons” display mode.
Fixes #12809
=> workspace-switcher@cinnamon.org: Workspaces will be always displayed as empty when they are

files/usr/share/cinnamon/cinnamon-settings/modules/cs_nightlight.py
This is more user-friendly than having to tweak the start and stop times, for everyone who wants to have it permanently enabled.
Depends on:
https://github.com/linuxmint/cinnamon-settings-daemon/pull/408
=> nightlight: Add schedule mode option 'always'

js/ui/settings.js
File monitor doesn't serve any useful purpose.
The only change is that a settings file will not be automatically be reloaded after being manually edited. The only place where a settings file is changed outside of `settings.js` is in `xlet-settings.py` but this calls `remoteUpdate()` method to trigger callbacks (via dbus).
If changing a setting's bound value via `settings.js` was intended to trigger it's callback, then this hasn't worked since at least 2016 (https://github.com/linuxmint/cinnamon/commit/f97a3e4677493194be23b67652f4b2b6c94c8667), so this PR makes no change in that respect. If it's desired to trigger callbacks on every change (via `settings.js`) to a setting's value  then a file monitor is an unnecessary and very inefficient way to do it anyway.
Mitigates against …
=> settings.js: remove file monitor

js/ui/messageTray.js
It seems that merely reading the `height` property of StBin before `queue-redraw` signal causes the image in the notification to disappear. This fixes the issue but whether it fixes the real cause of the bug, I'm not sure - I don't know if accessing the height property of StBin before `queue-redraw` is allowed or not supposed to have any side effects.
Fixes: https://github.com/linuxmint/cinnamon/issues/12613
=> Fix image not showing in notification when notifications are set to show at bottom of screen.

js/misc/gnomeSession.js, js/ui/polkitAuthenticationAgent.js, src/cinnamon-polkit-authentication-agent.c, src/cinnamon-polkit-authentication-agent.h
Compare Cinnamon's session id with cinnamon-session's (which should never change), and have cinnamon-session restart us if there is a mismatch.
Ref: #12669, #12728.
See: https://github.com/linuxmint/cinnamon-session/pull/184.
=> polkitAuthenticationAgent.js: Ensure Cinnamon is part of the correct login session when registering.

files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
use expected logic (local xlets override system xlets with the same name)
remove redundant gettext.gettext()
fixes: https://github.com/linuxmint/cinnamon/pull/12396#issuecomment-2600861202
=> cs_keyboard.py: use expected logic for xlet location

files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
some say that including "suspend" in the set of available battery critical actions is dangerous: power might ran out during suspend and machine state would be lost.
however:
- the really dangerous action is "do nothing", and it is still allowed in the UI. suspend might loose state, but is way way safer than "do nothing": suspend will flush all caches to disks, making sure that all recently saved data is persistent. it also forwards filesystems to a point where -though still mounted- they are effectively clean: filesystems are guaranteed to be in a sane state on-disk, even if they do not journal. running out of power during suspend is infinitely more "graceful" and safe than running out of power while the CPU is running: the latter is allowed, but the former is not. go figure...
- possible …
=> power: Add suspend option to battery-critical actions

files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
Implementation of https://github.com/orgs/linuxmint/discussions/767
Currently, when you enter a setting module from Cinnamon Settings, the title bar always says "System Settings" - no matter which setting you're in. The settings module doesn't have an indicator which setting you're in either. 
This behavior is different from when you enter the setting directly via a .desktop file or `cinnamon-settings module` from the terminal.
This PR adds the settings module name to the window title when you navigate into it.
=> cinnamon-settings: Add sidePage name to titlebar when entering

files/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py, files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
- Organizes themes into distinct categories (Mint-X, Mint-Y, etc.) with labeled separators
- Groups theme variants (Light/Dark/Darker) within each category
- Improves menu readability by fixing gray separator background issues
- Enhances theme selection UX with logical grouping and clear visual hierarchy
=> feat(themes): Implement categorized theme menus and debug tools

js/ui/panel.js
When panel is set to auto hide and panel settings (or applet settings) is opened, the panel shows for 1.5 seconds before hiding. I think that the need to show the highlighted panel while other panel settings are being changed outweighs the need to demonstrate the effect of the auto hide option.
Cf. https://github.com/linuxmint/cinnamon/pull/8659
=> panel.js: always show panel when highlighted

files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py, js/ui/main.js, meson.build
In newest glib GioUnix symbols are not anymore exposed in GioUnix, while cjs should use https://github.com/linuxmint/cjs/pull/131 it's still better to use GioUnix all the times.
~~More importantly though, when scanning the cinnamon headers, GioUnix-2.0 should be used or the APIs exposing `GDesktopAppInfo` won't work or they will be broken.~~ (this should not be  a problem here since you actually use `GMenuDesktopAppInfo` instead which is not exposed by `GioUnix`)
~~It's not included here, but it's *highly* recommended to now depend on GLib 2.86.0, or at least communicate clearly to distributors that they **must** recompile cinnamon on GLib 2.86.0 (and with these patches) to get it working with newer GLib version (or well with the newest gio introspection typelibs).~~
=> Prepare for GLib 2.86.0 typelib break
